### ISSUE TITLE
[Bug] File Not Found

### ISSUE THREAD

**Issue by WJXhhh** [Melledy/Grasscutter#1024]
java.io.FileNotFoundException: .\data\MotionStatusDatas.json (系统找不到指定的文
件。)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
        at java.base/java.io.FileReader.<init>(FileReader.java:60)
        at emu.grasscutter.game.managers.StaminaManager.StaminaRelatedNotifyHand
ler.initialize(StaminaRelatedNotifyHandler.java:83)
        at emu.grasscutter.game.managers.StaminaManager.StaminaManager.initializ
e(StaminaManager.java:50)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:134)

**Comment by WJXhhh** [comment]
我没有在开源文件的data文件夹找到这个文件。
I don't find this file in data floder of Grasscutter.git.

**Comment by SunshineVX** [comment]
你使用的是哪个分支？
Which branch did you use?

**Comment by zhaodice** [comment]
https://github.com/Grasscutters/Grasscutter/blob/e2bbc78a7c9c55a0cbb814d4755db59a8b0404a6/data/MotionStateDatas.json

**Comment by WJXhhh** [comment]
能稍微说一下这个分支从哪里找吗。

**Comment by WJXhhh** [comment]
English:How can I to find this branch?

**Comment by zhaodice** [comment]
> 能稍微说一下这个分支从哪里找吗。

你所使用的是用户自行提交的pr分支，并没有并入development，所以你找不到很正常
https://github.com/341101/Grasscutter/tree/Stamina

**Comment by zhaodice** [comment]
Actions里的实时build，并不是每一条都是来自本仓库的编译，有可能只是个还没并入的pr，需自己辨别。
