### ISSUE TITLE
[Bug] dev-world-scripts

### ISSUE THREAD

**Issue by kxmlqsql** [Melledy/Grasscutter#1026]
<ERROR:ResourceLoader> Error loading resource file: [InvestigationMonsterConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 3.358195073E9 at line 10 column 26 path $.CityId
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:242)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:232)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.Gson.fromJson(Gson.java:991)
        at com.google.gson.Gson.fromJson(Gson.java:956)
        at com.google.gson.Gson.fromJson(Gson.java:905)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:147)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:132)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:121)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:102)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:60)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:107)
Caused by: java.lang.NumberFormatException: Expected an int but was 3.358195073E9 at line 10 column 26 path $.CityId
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1204)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:240)
        ... 12 common frames omitted
怀疑是int的问题，登陆时出现（suppose to be a problem with int in dev -world- scripts when login）

**Comment by Akka0** [comment]
Are you using this res? https://github.com/Koko-boya/Grasscutter_Resources

**Comment by kxmlqsql** [comment]
yes

**Comment by kxmlqsql** [comment]
yes

**Comment by leonier-test** [comment]
> Are you using this res? https://github.com/Koko-boya/Grasscutter_Resources

I think 

```
public class InvestigationMonsterData extends GameResource {
    private int Id;
    private int CityId;
    private List<Integer> MonsterIdList;
    private List<Integer> GroupIdList;
    private int RewardPreviewId;
    private String MapMarkCreateType;
    private String MonsterCategory;
```
conflicts with
```
message InvestigationMonster {
	enum LockState {
		LOCK_NONE = 0;
		LOCK_QUEST = 1;
	}

	uint32 id = 1;
	uint32 city_id = 2;
	uint32 level = 3;
	bool is_alive = 4;
	uint32 next_refresh_time = 5;
	uint32 refresh_interval = 6;
	Vector pos = 7;
	LockState lock_state = 8;
```
The CityId in InvestigationMonsterData should be a long instead of int, Java's int is int32 and there is no proper internal uint32 support.

**Comment by KiminaNatsuki** [comment]
Closing inactive issues to clear up workspace, feel free to resubmit if this haven't been fixed yet, plus follow the issue format next time.
