### ISSUE TITLE
Help errors

### ISSUE THREAD

**Issue by nasocksok** [Melledy/Grasscutter#1077]
[09:58:22] [ERROR] Error loading resource file: [AvatarCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:130)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:117)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:107)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:51)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:93)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        ... 8 common frames omitted
[09:58:22] [INFO] Loaded 42 ReliquarySetDatas.
[09:58:22] [ERROR] Error loading resource file: [WeaponCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:130)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:117)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:107)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:51)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:93)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        ... 8 common frames omitted

[09:58:19] [ERROR] Error loading resource file: [MonsterCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:130)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:117)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:107)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:51)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:93)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        ... 8 common frames omitted

**Comment by zhaodice** [comment]
https://github.com/Koko-boya/Grasscutter_Resources

**Comment by gargarLum** [comment]
> https://github.com/Koko-boya/Grasscutter_Resources

i download BinOutput and ExcelBinOutput from your link, and put in resources, but it still same error as this question

**Comment by gszshdzz** [comment]
2.7不能用releases的jar，在actions里下载最新的jar，删数据库
（translated）2.7 You cannot use the relays of the jar, download the latest jar in the actions, delete the database
