### ISSUE TITLE
[Bug]  <ERROR:SceneScriptManager> [LUA] call trigger faile

### ISSUE THREAD

**Issue by EugenFeuer** [Melledy/Grasscutter#1094]
**Did you look for other closed issues that have the same problem?**

No same issue posted

**Describe the bug**

Logger shows exception stack after killing all mob in dungeon 4020, and there's no win effect shown

**Which branch did you use?**

Git Branch: `dev-world-scripts`
Git Hash: 5d0610b6f2c0aead04dc4a15508c545ba463ee10

**Screenshots**

**Additional context**

```
20:18:53 <ERROR:SceneScriptManager> [LUA] call trigger failed action_EVENT_GADGET_CREATE_53016,emu.grasscutter.scripts.data.ScriptArgs@47384027
org.luaj.vm2.LuaError: script:2810 vm error: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntArrayList.getInt(int)" because "this.wrapped" is null
        at org.luaj.vm2.lib.jse.JavaMethod.invokeMethod(Unknown Source)
        at org.luaj.vm2.lib.jse.JavaMethod.invoke(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.call(Unknown Source)
        at emu.grasscutter.scripts.SceneScriptManager.safetyCall(SceneScriptManager.java:338)
        at emu.grasscutter.scripts.SceneScriptManager.callScriptFunc(SceneScriptManager.java:331)
        at emu.grasscutter.scripts.SceneScriptManager.realCallEvent(SceneScriptManager.java:301)
        at emu.grasscutter.scripts.SceneScriptManager.lambda$callEvent$6(SceneScriptManager.java:286)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntArrayList.getInt(int)" because "this.wrapped" is null
        at it.unimi.dsi.fastutil.ints.IntOpenHashSet$SetIterator.nextInt(IntOpenHashSet.java:589)
        at it.unimi.dsi.fastutil.ints.IntIterator.next(IntIterator.java:43)
        at it.unimi.dsi.fastutil.ints.IntIterator.next(IntIterator.java:26)
        at com.google.protobuf.AbstractMessageLite$Builder.addAllCheckingNulls(AbstractMessageLite.java:372)
        at com.google.protobuf.AbstractMessageLite$Builder.addAll(AbstractMessageLite.java:434)
        at emu.grasscutter.net.proto.WorktopOptionNotifyOuterClass$WorktopOptionNotify$Builder.addAllOptionList(WorktopOptionNotifyOuterClass.java:634)
        at emu.grasscutter.server.packet.send.PacketWorktopOptionNotify.<init>(PacketWorktopOptionNotify.java:18)
        at emu.grasscutter.scripts.ScriptLib.SetWorktopOptionsByGroupId(ScriptLib.java:109)
        at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        ... 14 common frames omitted
```

**Comment by memetrollsXD** [comment]
Some LUA scripts are wonky and won't work, closing due to inactivity
