### ISSUE TITLE
[Bug] Got this when chat with NPCs

### ISSUE THREAD

**Issue by dianwangwin** [Melledy/Grasscutter#1102]
**Did you look for other closed issues that have the same problem?**

Yes

**Describe the bug**

 java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
        at emu.grasscutter.game.quest.QuestManager.lambda$triggerEvent$0(QuestManager.java:136)
        at emu.grasscutter.game.quest.QuestManager.forEachActiveQuest(QuestManager.java:81)
        at emu.grasscutter.game.quest.QuestManager.triggerEvent(QuestManager.java:132)
        at emu.grasscutter.server.packet.recv.HandlerNpcTalkReq.handle(HandlerNpcTalkReq.java:20)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:250)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:608)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

As Title

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by 4Benj** [comment]
<img width="193" alt="image" src="https://user-images.githubusercontent.com/5093878/170931012-9eea0607-375e-4d4f-94aa-1bbdb64574be.png">
?

**Comment by AZthemute** [comment]
Which NPC was it?
