### ISSUE TITLE
[help wanted] java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.avatar.Avatar.setCurrentEnergy()" because "this.avatar" is null

### ISSUE THREAD

**Issue by SapphireDogs** [Melledy/Grasscutter#1218]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**
The game stuck in the loading screen for almost an hour. This happen when i update the branch to 1.1.2. I've tried downloading the resources both from https://github.com/Koko-boya/Grasscutter_Resources/ and https://github.com/Dimbreath/GenshinData repeatedly but its still won't fix it. What can i do with this....?

**Which branch did you use?**
  Grasscutter version: 1.1.2-dev

**Screenshots**
![Screenshot (1246)](https://user-images.githubusercontent.com/105432821/172479231-5116151e-9c67-4bfd-8324-69e4dac31dda.png)
![Screenshot (1251)](https://user-images.githubusercontent.com/105432821/172479297-93329a7b-a968-4a88-90a1-acfa20133fc3.png)

**Additional context**
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.avatar.Avatar.setCurrentEnergy()" because "this.avatar" is null
        at emu.grasscutter.game.entity.EntityAvatar.<init>(EntityAvatar.java:49)
        at emu.grasscutter.game.world.Scene.setupPlayerAvatars(Scene.java:274)
        at emu.grasscutter.game.world.Scene.addPlayer(Scene.java:240)
        at emu.grasscutter.game.world.World.addPlayer(World.java:159)
        at emu.grasscutter.game.player.Player.onLogin(Player.java:1250)
        at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:48)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:277)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:608)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
io.jpower.kcp.netty.KcpException: State=-1 after update()
        at io.jpower.kcp.netty.UkcpServerChannel.run(UkcpServerChannel.java:398)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
io.jpower.kcp.netty.KcpException: State=-1 after update()
        at io.jpower.kcp.netty.UkcpServerChannel.updateChildKcp(UkcpServerChannel.java:491)
        at io.jpower.kcp.netty.UkcpServerChildChannel.doWrite(UkcpServerChildChannel.java:155)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:949)
        at io.jpower.kcp.netty.UkcpServerChildChannel$UkcpServerChildUnsafe.flush0(UkcpServerChildChannel.java:264)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.flush(AbstractChannel.java:913)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.flush(DefaultChannelPipeline.java:1372)
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025)
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:306)
        at emu.grasscutter.netty.KcpChannel.send(KcpChannel.java:62)
        at emu.grasscutter.server.game.GameSession.send(GameSession.java:209)
        at emu.grasscutter.server.game.GameSession.close(GameSession.java:50)
        at emu.grasscutter.netty.KcpChannel.exceptionCaught(KcpChannel.java:54)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281)
        at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:907)
        at io.jpower.kcp.netty.Utils.fireExceptionAndClose(Utils.java:25)
        at io.jpower.kcp.netty.UkcpServerChannel.handleCloseChildList(UkcpServerChannel.java:507)
        at io.jpower.kcp.netty.UkcpServerChannel.run(UkcpServerChannel.java:474)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by zhaodice** [comment]
download and make sure there are both resource folder and jar file together

**Comment by SapphireDogs** [comment]
> download and make sure there are both resource folder and jar file together

i've done this so many times but it still not fixed :')

**Comment by GanyusLeftHorn** [comment]
Have you tried creating a new account and see if that one works?

**Comment by SapphireDogs** [comment]
> Have you tried creating a new account and see if that one works?

Tried that one before and didn't work. But thankfully, i decided to give it another try just now and somehow it fixed. Thank you and sorry for such a trivial issue :)
