### ISSUE TITLE
更新了后，插件没办法正常运行是怎么回事呀

### ISSUE THREAD

**Issue by zhd1208** [Melledy/Grasscutter#1318]
插件没办法正常运行
Enabling plugin: opencommand-plugin
Exception in thread "main" java.lang.NoClassDefFoundError: emu/grasscutter/server/event/game/CommandResponseEvent
	at com.github.jie65535.opencommand.OpenCommandPlugin.onEnable(OpenCommandPlugin.java:46)
	at emu.grasscutter.plugin.PluginManager.lambda$enablePlugins$3(PluginManager.java:136)
	at java.base/java.util.HashMap.forEach(HashMap.java:1421)
	at emu.grasscutter.plugin.PluginManager.enablePlugins(PluginManager.java:134)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:167)
Caused by: java.lang.ClassNotFoundException: emu.grasscutter.server.event.game.CommandResponseEvent
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 5 more

**Comment by dianwangwin** [comment]
也许是api问题 尝试通過異常處理以解決問題

**Comment by ZXAS007** [comment]
更新插件即可解决，插件作者已发布新版本适配

**Comment by KiminaNatsuki** [comment]
> 更新插件即可解决，插件作者已发布新版本适配
