### ISSUE TITLE
[Bug] dispatch.RegionHandler

### ISSUE THREAD

**Issue by qinastar** [Melledy/Grasscutter#1344]
复现（？）：
我分离了dispatch和game服务器，连接同一数据库。
在我进入游戏后报错：
> java.lang.NullPointerException: Cannot invoke "emu.grasscutter.server.http.dispatch.RegionHandler$RegionData.getRegionQuery()" because the return value of "java.util.Map.get(Object)" is null
        at emu.grasscutter.server.http.dispatch.RegionHandler.getCurrentRegion(RegionHandler.java:173)
        at emu.grasscutter.server.packet.send.PacketPlayerLoginRsp.<init>(PacketPlayerLoginRsp.java:51)
        at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:52)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:224)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by f0re1gnKey** [comment]
手动在regions里加入{}

**Comment by qinastar** [comment]
"dispatch": {
      "regions": [
        {
          "Name": "server",
          "Title": "server",
          "Ip": "127.0.0.1",
          "Port": 22102
        },
        {
          "Name": "server2",
          "Title": "server2",
          "Ip": "127.0.0.1",
          "Port": 22103
        },
        {
          "Name": "server3",
          "Title": "server3",
          "Ip": "127.0.0.1",
          "Port": 22104
        }
      ],
      "defaultName": "server"
    }
是哪里缺少东西吗？

> 手动在regions里加入{}

**Comment by zhaodice** [comment]
运行模式修改一下，不要 HYBRID

**Comment by xciriza** [comment]
> 运行模式修改一下，不要 HYBRID

那还有什么运行模式？

**Comment by KiminaNatsuki** [comment]
Cleaning up inactive issues, plus this one didn't follow the format.
