### ISSUE TITLE
[Bug] can't show banners 

### ISSUE THREAD

**Issue by daxiwow** [Melledy/Grasscutter#1351]
07:18:32 <ERROR:ScriptLoader> Loading script .\resources\Scripts\Scene\3\scene3_
group133102769.lua failed!
javax.script.ScriptException: eval threw javax.script.ScriptException: [string "
script"]:1304: unexpected symbol 47 (/)
        at org.luaj.vm2.script.LuaScriptEngine.compile(Unknown Source)
        at emu.grasscutter.scripts.ScriptLoader.getScriptByPath(ScriptLoader.jav
a:119)
        at emu.grasscutter.scripts.data.SceneGroup.load(SceneGroup.java:91)
        at emu.grasscutter.game.world.WorldDataManager.getInvestigationGroup(Wor
ldDataManager.java:77)
        at emu.grasscutter.game.world.WorldDataManager.getInvestigationMonster(W
orldDataManager.java:98)
        at emu.grasscutter.game.world.WorldDataManager.lambda$getInvestigationMo
nstersByCityId$6(WorldDataManager.java:144)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipe
line.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipe
line.java:179)
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueSpliterator.acc
eptOnIndex(Int2ObjectOpenHashMap.java:1221)
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueSpliterator.acc
eptOnIndex(Int2ObjectOpenHashMap.java:1205)
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapSpliterator.forEa
chRemaining(Int2ObjectOpenHashMap.java:881)
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueSpliterator.for
EachRemaining(Int2ObjectOpenHashMap.java:1205)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline
.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractP
ipeline.java:499)
        at java.base/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2183
)
        at java.base/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2149
)
        at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327
)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter
.java:754)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:
373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Fo
rkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:16
55)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.ja
va:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorke
rThread.java:165)

**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by daxiwow** [comment]
![微信图片_20220623072722](https://user-images.githubusercontent.com/54258434/175175573-94803af5-3c14-4ea9-a4d0-2f6c2616f018.png)

**Comment by daxiwow** [comment]
i delete date but still this

**Comment by aemirooo** [comment]
Grasscutter version?

**Comment by daxiwow** [comment]
> 割草机版？
1.2.1  #development  44fd508

**Comment by daxiwow** [comment]
ok i fix ,u should update the game date before
