### ISSUE TITLE
[Bug] item stacks bug reoccur

### ISSUE THREAD

**Issue by trip14nm** [Melledy/Grasscutter#1385]
**Did you look for other closed issues that have the same problem?**

The same as #1328

**Describe the bug**

Bug was solved by #1333 ,but it looks like 7d709c3 reproduced it

**Which branch did you use?**

Git Hash: 7d709c3
The bug appear in Build #1401 while Build #1400 performing well

**Screenshots**

![](https://s3.bmp.ovh/imgs/2022/06/26/003c708e792b64f3.png)
![](https://s3.bmp.ovh/imgs/2022/06/26/23db06a658dd2803.png)
**Additional context**

log:
> `2022-06-26T22:53:53Z <INFO:io.javalin.Javalin> Javalin has stopped
2022-06-26T22:55:29Z <INFO:emu.grasscutter.Grasscutter> 正在启动 Grasscutter...
2022-06-26T22:55:30Z <INFO:emu.grasscutter.Grasscutter> 游戏版本：2.7.0
2022-06-26T22:55:30Z <INFO:emu.grasscutter.Grasscutter> Grasscutter 版本：1.2.2-dev-7d709c3
2022-06-26T22:55:31Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 411 AvatarSkillDatas.
2022-06-26T22:55:31Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 31 ForgeDatas.
2022-06-26T22:55:31Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 4246 FetterDatas.
2022-06-26T22:55:31Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 49 FetterCharacterCardDatas.
2022-06-26T22:55:31Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 312 AvatarTalentDatas.
2022-06-26T22:55:31Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 668 RewardPreviewDatas.
2022-06-26T22:55:31Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 168 MonsterDescribeDatas.
2022-06-26T22:55:31Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 75 AvatarSkillDepotDatas.
2022-06-26T22:55:31Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 6 CityDatas.
2022-06-26T22:55:32Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 2516 ProudSkillDatas.
2022-06-26T22:55:32Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 143 WorldAreaDatas.
2022-06-26T22:55:32Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 200 MonsterCurveDatas.
2022-06-26T22:55:32Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 497 CodexMaterialDatas.
2022-06-26T22:55:32Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 42 ReliquarySetDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 11420 QuestDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 49 TowerScheduleDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 9 AvatarFlycloakDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 335 ReliquaryAffixDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 6868 GadgetDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 60 PlayerLevelDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 123 TowerLevelDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 61 DungeonEntryDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 1230 ShopGoodsDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 515 WeatherDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 50 BattlePassRewardDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 4182 RewardDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 154 BattlePassMissionDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 24 DailyDungeonDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 10 AvatarFetterLevelDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 233 CodexAnimalDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 90 WeaponLevelDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 81 CodexReliquaryDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 297 CombineDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 350 AvatarPromoteDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 734 SceneDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 3093 NpcDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 749 EquipAffixDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 101 ReliquaryLevelDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 8 WorldLevelDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 59 AvatarCostumeDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 100 WeaponCurveDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 66 ReliquaryMainPropDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 208 CodexQuestDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 814 DungeonDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 446 FurnitureMakeConfigDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 401 GatherDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 100 AvatarCurveDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 90 AvatarLevelDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 41 TowerFloorDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 137 CodexWeaponDatas.
2022-06-26T22:55:35Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 953 WeaponPromoteDatas.
2022-06-26T22:55:36Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 7793 ItemDatas.
2022-06-26T22:55:36Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 10 HomeWorldLevelDatas.
2022-06-26T22:55:36Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 39 EnvAnimalGatherConfigDatas.
2022-06-26T22:55:36Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 40 InvestigationMonsterDatas.
2022-06-26T22:55:36Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 569 MonsterDatas.
2022-06-26T22:55:36Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 80 AvatarDatas.
2022-06-26T22:55:37Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 1508 MainQuestDatas.
2022-06-26T22:55:38Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 7 HomeworldDefaultSaveDatas.
2022-06-26T22:55:38Z <INFO:emu.grasscutter.data.ResourceLoader> Loaded 20 SceneNpcBornDatas.
2022-06-26T22:55:39Z <INFO:com.mongodb.diagnostics.logging.SLF4JLogger> Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
2022-06-26T22:55:39Z <INFO:com.mongodb.diagnostics.logging.SLF4JLogger> Opened connection [connectionId{localValue:2, serverValue:104}] to localhost:27017
2022-06-26T22:55:39Z <INFO:com.mongodb.diagnostics.logging.SLF4JLogger> Opened connection [connectionId{localValue:1, serverValue:103}] to localhost:27017
2022-06-26T22:55:39Z <INFO:com.mongodb.diagnostics.logging.SLF4JLogger> Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=94930512}
2022-06-26T22:55:40Z <INFO:com.mongodb.diagnostics.logging.SLF4JLogger> Opened connection [connectionId{localValue:3, serverValue:105}] to localhost:27017
2022-06-26T22:55:40Z <INFO:org.eclipse.jetty.util.log.Log> Logging initialized @18163ms to org.eclipse.jetty.util.log.Slf4jLog
2022-06-26T22:55:42Z <INFO:emu.grasscutter.game.dungeons.challenge.DungeonChallenge> Loaded 108 dungeon drop data entries.
2022-06-26T22:55:42Z <INFO:emu.grasscutter.game.managers.energy.EnergyManager> Energy drop data successfully loaded.
2022-06-26T22:55:42Z <INFO:emu.grasscutter.game.managers.energy.EnergyManager> Skill particle generation data successfully loaded.
2022-06-26T22:55:42Z <INFO:emu.grasscutter.server.game.GameServerPacketHandler> Registered 151 PacketHandlers
2022-06-26T22:55:43Z <INFO:emu.grasscutter.game.gacha.GachaManager> Banners successfully loaded.
2022-06-26T22:55:43Z <INFO:emu.grasscutter.game.shop.ShopManager> Shop data successfully loaded.
2022-06-26T22:55:43Z <INFO:emu.grasscutter.game.shop.ShopManager> ShopChest data successfully loaded.
2022-06-26T22:55:43Z <INFO:emu.grasscutter.game.shop.ShopManager> ShopChestBatchUse data successfully loaded.
2022-06-26T22:55:43Z <INFO:org.quartz.impl.StdSchedulerFactory> Using default implementation for ThreadExecutor
2022-06-26T22:55:43Z <INFO:org.quartz.simpl.SimpleThreadPool> Job execution threads will use class loader of thread: main
2022-06-26T22:55:43Z <INFO:org.quartz.core.SchedulerSignalerImpl> Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
2022-06-26T22:55:43Z <INFO:org.quartz.core.QuartzScheduler> Quartz Scheduler v.2.3.2 created.
2022-06-26T22:55:43Z <INFO:org.quartz.simpl.RAMJobStore> RAMJobStore initialized.
2022-06-26T22:55:43Z <INFO:org.quartz.core.QuartzScheduler> Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.
2022-06-26T22:55:43Z <INFO:org.quartz.impl.StdSchedulerFactory> Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
2022-06-26T22:55:43Z <INFO:org.quartz.impl.StdSchedulerFactory> Quartz scheduler version: 2.3.2
2022-06-26T22:55:43Z <INFO:org.quartz.core.QuartzScheduler> Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
2022-06-26T22:55:43Z <INFO:emu.grasscutter.game.drop.DropManager> Drop data successfully loaded.
2022-06-26T22:55:43Z <INFO:emu.grasscutter.game.expedition.ExpeditionManager> Expedition reward successfully loaded.
2022-06-26T22:55:44Z <INFO:emu.grasscutter.plugin.PluginManager> Loading plugin: GrasscuttersWebDashboard
2022-06-26T22:55:44Z <INFO:top.cyqi.GrasscuttersWebDashboard> [WEB控制台] 加载中...
2022-06-26T22:55:44Z <INFO:emu.grasscutter.plugin.PluginManager> Loading plugin: opencommand-plugin
2022-06-26T22:55:48Z <INFO:org.eclipse.jetty.server.Server> jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 17.0.3+7-Debian-1deb11u1
2022-06-26T22:55:49Z <INFO:org.eclipse.jetty.util.ssl.SslContextFactory> x509=X509@425f94d7(keystore_entry,h=[mydomain.com, localhost],w=[]) for Server@378c48c1[provider=null,keyStore=file:///root/genshin/keystore.p12,trustStore=null]
2022-06-26T22:55:50Z <INFO:org.eclipse.jetty.server.AbstractConnector> Started ServerConnector@45f9d394{SSL, (ssl, http/1.1)}{0.0.0.0:443}
2022-06-26T22:55:50Z <INFO:org.eclipse.jetty.server.Server> Started @27838ms
2022-06-26T22:55:50Z <INFO:express.Express> Server listening on http://0.0.0.0:443
2022-06-26T22:55:50Z <INFO:emu.grasscutter.server.http.HttpServer> [Dispatch] 服务器已在端口 443 上启动
2022-06-26T22:55:50Z <INFO:emu.grasscutter.server.game.GameServer> Grasscutter 是免费开源软件，遵循 AGPL-3.0 license。如果你是付费购买的，那你已经被骗了。项目地址：https://github.com/Grasscutters/Grasscutter
2022-06-26T22:55:50Z <INFO:emu.grasscutter.server.game.GameServer> 游戏服务器已在端口 22102 上启动
2022-06-26T22:55:50Z <INFO:emu.grasscutter.plugin.PluginManager> Enabling plugin: GrasscuttersWebDashboard
2022-06-26T22:55:50Z <INFO:top.cyqi.GrasscuttersWebDashboard> [WEB控制台] 启动完成！！
2022-06-26T22:55:50Z <INFO:top.cyqi.GrasscuttersWebDashboard> [WEB控制台] 您设置的Token是：GrasscuttersWebDashboard
2022-06-26T22:55:50Z <INFO:top.cyqi.GrasscuttersWebDashboard> [WEB控制台] 连接地址是：wss://192.168.6.90:443/Dashboard/GrasscuttersWebDashboard
2022-06-26T22:55:50Z <INFO:top.cyqi.GrasscuttersWebDashboard> [WEB控制台] 快速连接，用浏览器打开：https://liujiaqi7998.github.io/GrasscuttersWebDashboard/index.html?server=wss://192.168.6.90:443/Dashboard/GrasscuttersWebDashboard
2022-06-26T22:55:50Z <INFO:top.cyqi.GrasscuttersWebDashboard> [WEB控制台] 连接地址不要告诉任何人，建议定期更换token！！
2022-06-26T22:55:50Z <INFO:emu.grasscutter.plugin.PluginManager> Enabling plugin: opencommand-plugin
2022-06-26T22:55:50Z <INFO:com.github.jie65535.opencommand.OpenCommandPlugin> [OpenCommand] Enabled
2022-06-26T22:55:50Z <INFO:emu.grasscutter.Grasscutter> 加载完成！输入 "help" 查看命令列表
2022-06-26T22:57:23Z <INFO:emu.grasscutter.auth.DefaultAuthenticators$PasswordAuthenticator> [Dispatch] 客户端 192.168.6.90 已登录，UID 为 10001
2022-06-26T22:57:24Z <INFO:emu.grasscutter.server.http.dispatch.DispatchHandler> [Dispatch] 客户端 192.168.6.90 正在尝试登录
2022-06-26T22:57:24Z <INFO:emu.grasscutter.auth.DefaultAuthenticators$SessionKeyAuthenticator> [Dispatch] 客户端 192.168.6.90 成功交换 token
2022-06-26T22:57:24Z <INFO:emu.grasscutter.server.http.dispatch.DispatchHandler> [Dispatch] 客户端 192.168.6.90 正在尝试登录
2022-06-26T22:57:25Z <INFO:emu.grasscutter.server.http.dispatch.RegionHandler> Client 192.168.6.90 request: query_cur_region/os_usa
2022-06-26T22:57:29Z <INFO:emu.grasscutter.server.game.GameSession> 客户端 /192.168.6.97:54111 已连接
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133102769.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133001097.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group166001112.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133210023.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133001233.lua
2022-06-26T22:57:34Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133102769.lua failed!
javax.script.ScriptException: eval threw javax.script.ScriptException: [string "script"]:1304: unexpected symbol 47 (/)
	at org.luaj.vm2.script.LuaScriptEngine.compile(Unknown Source)
	at emu.grasscutter.scripts.ScriptLoader.getScriptByPath(ScriptLoader.java:119)
	at emu.grasscutter.scripts.data.SceneGroup.load(SceneGroup.java:91)
	at emu.grasscutter.game.world.WorldDataManager.getInvestigationGroup(WorldDataManager.java:77)
	at emu.grasscutter.game.world.WorldDataManager.getInvestigationMonster(WorldDataManager.java:98)
	at emu.grasscutter.game.world.WorldDataManager.lambda$getInvestigationMonstersByCityId$6(WorldDataManager.java:144)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueSpliterator.acceptOnIndex(Int2ObjectOpenHashMap.java:1221)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueSpliterator.acceptOnIndex(Int2ObjectOpenHashMap.java:1205)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapSpliterator.forEachRemaining(Int2ObjectOpenHashMap.java:881)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueSpliterator.forEachRemaining(Int2ObjectOpenHashMap.java:1205)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2183)
	at java.base/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2149)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133104394.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133001097 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133004369.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133212378.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133210023 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133004369 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group166001287.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133225105.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133003317.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133225105 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133001313.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133212378 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133101249.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133003317 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133101249 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133001229.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133104394 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133104268.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133001229 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133210237.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133001313 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133104268 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133213187.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133103325.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133213187 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133103325 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133220660.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133007239.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133210237 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133108020.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133007239 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group155005095.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133220660 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133008657.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133103640.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133008657 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133220657.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133220657 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133108020 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133002398.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133222181.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133002398 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133002259.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133222181 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133220037.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133220037 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133220497.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133103640 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133002342.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133220497 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133102652.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133002342 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133102652 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133001021.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133104304.lua
2022-06-26T22:57:34Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133002259.lua failed!
javax.script.ScriptException: eval threw javax.script.ScriptException: [string "script"]:973: unexpected symbol 47 (/)
	at org.luaj.vm2.script.LuaScriptEngine.compile(Unknown Source)
	at emu.grasscutter.scripts.ScriptLoader.getScriptByPath(ScriptLoader.java:119)
	at emu.grasscutter.scripts.data.SceneGroup.load(SceneGroup.java:91)
	at emu.grasscutter.game.world.WorldDataManager.getInvestigationGroup(WorldDataManager.java:77)
	at emu.grasscutter.game.world.WorldDataManager.getInvestigationMonster(WorldDataManager.java:98)
	at emu.grasscutter.game.world.WorldDataManager.lambda$getInvestigationMonstersByCityId$6(WorldDataManager.java:144)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueSpliterator.acceptOnIndex(Int2ObjectOpenHashMap.java:1221)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueSpliterator.acceptOnIndex(Int2ObjectOpenHashMap.java:1205)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapSpliterator.forEachRemaining(Int2ObjectOpenHashMap.java:881)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueSpliterator.forEachRemaining(Int2ObjectOpenHashMap.java:1205)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2183)
	at java.base/java.util.stream.Nodes$CollectorTask.doLeaf(Nodes.java:2149)
	at java.base/java.util.stream.AbstractTask.compute(AbstractTask.java:327)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:754)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133003543.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133003543 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133001021 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133102504.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133104304 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.ScriptLoader> Loading script ./resources/Scripts/Scene/3/scene3_group133001358.lua
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133102504 in scene 3 is loaded successfully.
2022-06-26T22:57:34Z <INFO:emu.grasscutter.scripts.data.SceneGroup> group 133001358 in scene 3 is loaded successfully.
2022-06-26T22:58:38Z <INFO:emu.grasscutter.command.CommandHandler> 正在关闭服务器...`

**Comment by Birdulon** [comment]
The positional quantity argument was removed from the give command. Quantity can now only be set using `[x<quantity>]` (previously this was an optional way of setting it). Try `/give 102 x18` or `/give 102 18x`.
