### ISSUE TITLE
[Bug] 开启代理出错了，不知道是有哪里没读到吗，帮一下

### ISSUE THREAD

**Issue by xiaosui622123** [Melledy/Grasscutter#1391]
Traceback (most recent call last):

  File "asyncio\proactor_events.py", line 820, in loop

  File "asyncio\windows_events.py", line 817, in _poll

  File "asyncio\windows_events.py", line 566, in finish_accept

OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues
Traceback (most recent call last):

  File "asyncio\windows_events.py", line 571, in accept_coro

  File "asyncio\proactor_events.py", line 820, in loop

  File "asyncio\windows_events.py", line 817, in _poll

  File "asyncio\windows_events.py", line 566, in finish_accept

OSError: [WinError 10014] 系统检测到在一个调用中尝试使用指针参数时的无效指针地址。

Please lodge a bug report at:
        https://github.com/mitmproxy/mitmproxy/issues

**Comment by zhaodice** [comment]
Please lodge a bug report at:
https://github.com/mitmproxy/mitmproxy/issues
