### ISSUE TITLE
[Bug] NullPointerException when generating and destroying a large number of enemies .

### ISSUE THREAD

**Issue by wumulong-469** [Melledy/Grasscutter#1398]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

when i used ‘Grasscutter-tools’ command ‘/spawn 21010101 800 1’ to generate 800 amount enemies.
I swam in the lake and the enemies dorped into the water and gone. in the terminal，i got the multiple same message:

```
2022-06-28T17:59:14Z <ERROR:emu.grasscutter.server.game.GameServer$1> 游戏更新时发生错误
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntArrayList.getInt(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:703)
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$ValueIterator.next(Int2ObjectOpenHashMap.java:1202)
	at emu.grasscutter.game.world.Scene.checkSpawns(Scene.java:486)
	at emu.grasscutter.game.world.Scene.onTick(Scene.java:421)
	at emu.grasscutter.game.world.World.onTick(World.java:314)
	at emu.grasscutter.server.game.GameServer.onTick(GameServer.java:233)
	at emu.grasscutter.server.game.GameServer$1.run(GameServer.java:260)
	at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
	at java.base/java.util.TimerThread.run(Timer.java:516)
```

The game seemed to be running well yet .  It seems that this bug is not fatal???

**Which branch did you use?**

Grasscutter version: 1.2.0-e5dd407a
Git Hash：e5dd407 

**Screenshots**

may something network wrong ! i can't put on the screenshots image , i am sorry about that.

**Additional context**

i deploy the server on arm64 platform .
jdk info is:
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Debian-1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Debian-1, mixed mode, sharing)

**Comment by lingzn12** [comment]
在后续开发版本解决了这个问题，请使用1.2.2最新版本试试看。

**Comment by wumulong-469** [comment]
1.2.2-dev-0141dce 没有此类异常抛出 =v=
