### ISSUE TITLE
Server Error When Logging In

### ISSUE THREAD

**Issue by Scirese** [Melledy/Grasscutter#140]
I compiled grasscutter from latest dev branch.
And uses java 16.

org.bson.codecs.configuration.CodecConfigurationException: Can't find a codec for class emu.grasscutter.game.player.PlayerBirthday.
	at org.bson.internal.CodecCache.lambda$getOrThrow$1(CodecCache.java:52)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at org.bson.internal.CodecCache.getOrThrow(CodecCache.java:51)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:64)
	at org.bson.internal.ChildCodecRegistry.get(ChildCodecRegistry.java:52)
	at dev.morphia.mapping.codec.PropertyCodecRegistryImpl$FallbackPropertyCodecProvider.get(PropertyCodecRegistryImpl.java:82)
	at dev.morphia.mapping.codec.PropertyCodecRegistryImpl.get(PropertyCodecRegistryImpl.java:58)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.specializePropertyCodecs(MorphiaCodec.java:153)
	at dev.morphia.mapping.codec.pojo.MorphiaCodec.<init>(MorphiaCodec.java:64)
	at dev.morphia.mapping.codec.MorphiaCodecProvider.get(MorphiaCodecProvider.java:60)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:57)
	at org.bson.internal.ProvidersCodecRegistry.get(ProvidersCodecRegistry.java:39)
	at com.mongodb.internal.operation.Operations.createFindOperation(Operations.java:163)
	at com.mongodb.internal.operation.Operations.find(Operations.java:153)
	at com.mongodb.internal.operation.SyncOperations.find(SyncOperations.java:93)
	at com.mongodb.client.internal.FindIterableImpl.asReadOperation(FindIterableImpl.java:236)
	at com.mongodb.client.internal.FindIterableImpl.asReadOperation(FindIterableImpl.java:40)
	at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
	at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
	at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:321)
	at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:200)
	at dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:188)
	at dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:183)
	at emu.grasscutter.database.DatabaseHelper.checkPlayerExists(DatabaseHelper.java:98)
	at emu.grasscutter.server.packet.recv.HandlerGetPlayerTokenReq.handle(HandlerGetPlayerTokenReq.java:40)
	at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:81)
	at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:234)
	at emu.grasscutter.netty.MihoyoKcpChannel.channelRead(MihoyoKcpChannel.java:43)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)

**Comment by Scirese** [comment]
This makes me stuck in the loading screen and cant get into game

**Comment by MlgmXyysd** [comment]
seems related to https://github.com/Grasscutters/Grasscutter/pull/136
CC @miyucchi

**Comment by Scirese** [comment]
> seems related to #136 CC @miyucchi

did he tested the pr before push?
At least make it working before push...

**Comment by KingRainbow44** [comment]
this issue comes from the PR, which was created presumably before the Java 16 merge.
someone will need to update this in another PR so this issue will remain open

**Comment by KingRainbow44** [comment]
the issue itself is trivial to fix, add `@Entity` above the class declaration for `PlayerBirthday`

**Comment by ghost** [comment]
@Scirese yes I tested it, but on JDK 8. Next time I'll use Java 16 to avoid these problems.
@MlgmXyysd Thanks for fix and sorry for a mistake. ;/

**Comment by ghost** [comment]
Not your fault, the dev branch was on java 8 when you made the pull request. Anyways, since it was fixed in #144, i will be closing this now.
