### ISSUE TITLE
Exception reflections.ReflectionsException: Scanner TypeAnnotationsScanner was not configured

### ISSUE THREAD

**Issue by StillMi** [Melledy/Grasscutter#148]
Exception in thread "main" org.reflections.ReflectionsException: Scanner TypeAnnotationsScanner was not configured
        at org.reflections.Store.get(Store.java:39)
        at org.reflections.Store.get(Store.java:61)
        at org.reflections.Store.get(Store.java:46)
        at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:429)
        at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:416)
        at emu.grasscutter.command.CommandMap.scan(CommandMap.java:147)
        at emu.grasscutter.command.CommandMap.<init>(CommandMap.java:19)
        at emu.grasscutter.server.game.GameServer.<init>(GameServer.java:60)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:80)
When it starts
Cannot continue

**Comment by ywnkm** [comment]
I solved this problem by updating the version of reflections
```
implementation group: 'org.reflections', name: 'reflections', version: '0.10.2'
```

**Comment by StillMi** [comment]
thank you  problem solved

**Comment by KingRainbow44** [comment]
was this issue on dev or stable?

**Comment by czy20010112** [comment]
> I solved this problem by updating the version of reflections
> 
> ```
> implementation group: 'org.reflections', name: 'reflections', version: '0.10.2'
> ```

sorry to trouble but could u please tell me how to update this? do i need to download the source code and change it by myself? or could u give me a command to update it? thanks a lot 
java version "18.0.1" 2022-04-19  centos 7.9 mongodb 4.4
Java(TM) SE Runtime Environment (build 18.0.1+10-24)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.1+10-24, mixed mode, sharing)
