### ISSUE TITLE
[Bug] Cannot invoke "emu.grasscutter.game.home.HomeSceneItem.calComfort()" because "homeRoomScene" is null

### ISSUE THREAD

**Issue by NeoMika** [Melledy/Grasscutter#1509]
at emu.grasscutter.server.packet.send.PacketHomeComfortInfoNotify.<init>(PacketHomeComfortInfoNotify.java:35)
        at emu.grasscutter.game.home.GameHome.onOwnerLogin(GameHome.java:72)
        at emu.grasscutter.game.player.Player.onLogin(Player.java:1536)
        at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:48)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:244)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by KiminaNatsuki** [comment]
Please re-submit this issue with more context / information.

**Comment by RhythmLunatic** [comment]
This seems to be caused by updating GC from 2.6 to 2.8 and player profile data being incompatible, but making a new account works fine.

**Comment by chenxuan353** [comment]
I checked the database and found that it works fine after deleting the realmList and currentRealmId for the player in the players collection.
