### ISSUE TITLE
[Bug] java.lang.IllegalArgumentException: No enum constant emu.grasscutter.net.proto.MapMarkFromTypeOuterClass.MapMarkFromType.MAP_MARK_FROM_TYPE_NOE

### ISSUE THREAD

**Issue by RTBSG** [Melledy/Grasscutter#1510]
java.lang.IllegalArgumentException: No enum constant emu.grasscutter.net.proto.MapMarkFromTypeOuterClass.MapMarkFromType.MAP_MARK_FROM_TYPE_NOE
        at java.base/java.lang.Enum.valueOf(Enum.java:273)
        at dev.morphia.mapping.codec.EnumCodec.decode(EnumCodec.java:35)
        at dev.morphia.mapping.codec.EnumCodec.decode(EnumCodec.java:16)
        at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
        at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:59)
        at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:80)
        at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:35)
        at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:71)
        at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:40)
        at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:71)
        at dev.morphia.mapping.codec.MorphiaMapPropertyCodecProvider$MapCodec.decode(MorphiaMapPropertyCodecProvider.java:85)
        at dev.morphia.mapping.codec.MorphiaMapPropertyCodecProvider$MapCodec.decode(MorphiaMapPropertyCodecProvider.java:49)
        at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
        at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:59)
        at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:80)
        at dev.morphia.mapping.codec.pojo.LifecycleDecoder.decode(LifecycleDecoder.java:51)
        at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:71)
        at com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
        at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
        at org.bson.internal.LazyCodec.decode(LazyCodec.java:48)
        at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
        at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)

**Comment by memetrollsXD** [comment]
Please re-submit this issue with more context / information

**Comment by RTBSG** [comment]
> 请重新提交此问题并提供更多上下文/信息
I have found the problem and solved it temporarily, but I still need you to make changes
