### ISSUE TITLE
[Bug] （It has been temporarily resolved）java.lang.IllegalArgumentException: No enum constant emu.grasscutter.net.proto.MapMarkFromTypeOuterClass.MapMarkFromType.MAP_MARK_FROM_TYPE_NOE

### ISSUE THREAD

**Issue by RTBSG** [Melledy/Grasscutter#1515]
java.lang.IllegalArgumentException: No enum constant emu.grasscutter.net.proto.MapMarkFromTypeOuterClass.MapMarkFromType._MAP_MARK_FROM_TYPE_NOE_
at java.base/java.lang.Enum.valueOf(Enum.java:273)
at dev.morphia.mapping.codec.EnumCodec.decode(EnumCodec.java:35)
at dev.morphia.mapping.codec.EnumCodec.decode(EnumCodec.java:16)
at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:59)
at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:80)
at dev.morphia.mapping.codec.pojo.EntityDecoder.decode(EntityDecoder.java:35)

I tried to run jar directly and compile the source code. There are the same problems above. I found that the names [map_mark_from_type_noe] and [mapmarkfromtype.map_mark_from_type_none] in the enumeration are different. But this is in the source file. I temporarily added [map_mark_from_type_noe (0)] to the source file to enter the game. I don't know where [map_mark_from_type_noe] is in the program.so  need your to modify it.
I changed the contents of this document.

src/generated/main/java/emu/grasscutter/net/proto/MapMarkFromTypeOuterClass. java

**Comment by KiminaNatsuki** [comment]
Please follow the issue format first, then feel free to make another issue.
拜託請先按照Issue格式提出問題，隨後再重發一次。
