### ISSUE TITLE
[Bug]（求助） I can't loading Grasscutter But I do all step on README_zh-CN.md (我已经按照步骤操作但还是没办法加载私服)

### ISSUE THREAD

**Issue by DuolaD** [Melledy/Grasscutter#1577]
Starting local Grasscutter server...
21:43:11 <INFO:Grasscutter> 正在启动 Grasscutter...
21:43:12 <INFO:Grasscutter> 游戏版本：2.8.0
21:43:12 <INFO:Grasscutter> Grasscutter 版本：1.2.3-dev-f3a43e9
21:43:12 <INFO:ResourceLoader> 正在加载 resources...
21:43:13 <ERROR:ResourceLoader> Unable to load quest keys.
java.lang.NullPointerException: null
        at java.base/java.io.Reader.<init>(Reader.java:168)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:76)
        at emu.grasscutter.data.DataLoader.loadReader(DataLoader.java:45)
        at emu.grasscutter.data.ResourceLoader.loadQuests(ResourceLoader.java:420)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:69)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:160)
21:43:13 <INFO:ResourceLoader> 完成加载 resources。
Exception in thread "main" java.lang.RuntimeException: Port already in use. Make sure no other process is using port 443 and try again.
        at io.javalin.Javalin.start(Javalin.java:185)
        at io.javalin.Javalin.start(Javalin.java:151)
        at io.javalin.Javalin.start(Javalin.java:138)
        at express.Express.listen(Express.java:220)
        at emu.grasscutter.server.http.HttpServer.start(HttpServer.java:136)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:192)
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:443
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
        at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at io.javalin.core.JavalinServer.start(JavalinServer.kt:63)
        at io.javalin.Javalin.start(Javalin.java:175)
        ... 5 more
Caused by: java.net.BindException: Address already in use: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
        at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:345)
        ... 13 more

**Comment by DuolaD** [comment]
This is my config.json,I not moved or do the change before:

{
  "folderStructure": {
    "resources": "./resources/",
    "data": "./data/",
    "packets": "./packets/",
    "scripts": "./resources/Scripts/",
    "plugins": "./plugins/"
  },
  "databaseInfo": {
    "server": {
      "connectionUri": "mongodb://localhost:27017",
      "collection": "grasscutter"
    },
    "game": {
      "connectionUri": "mongodb://localhost:27017",
      "collection": "grasscutter"
    }
  },
  "language": {
    "language": "zh_CN",
    "fallback": "en_US",
    "document": "EN"
  },
  "account": {
    "autoCreate": false,
    "defaultPermissions": [],
    "maxPlayer": -1
  },
  "server": {
    "debugLevel": "NONE",
    "runMode": "HYBRID",
    "http": {
      "bindAddress": "0.0.0.0",
      "accessAddress": "127.0.0.1",
      "bindPort": 443,
      "accessPort": 0,
      "encryption": {
        "useEncryption": true,
        "useInRouting": true,
        "keystore": "./keystore.p12",
        "keystorePassword": "123456"
      },
      "policies": {
        "cors": {
          "enabled": false,
          "allowedOrigins": [
            "*"
          ]
        }
      },
      "files": {
        "indexFile": "./index.html",
        "errorFile": "./404.html"
      }
    },
    "game": {
      "bindAddress": "0.0.0.0",
      "accessAddress": "127.0.0.1",
      "bindPort": 22102,
      "accessPort": 0,
      "enableConsole": true,
      "gameOptions": {
        "inventoryLimits": {
          "weapons": 2000,
          "relics": 2000,
          "materials": 2000,
          "furniture": 2000,
          "all": 30000
        },
        "avatarLimits": {
          "singlePlayerTeam": 4,
          "multiplayerTeam": 4
        },
        "sceneEntityLimit": 1000,
        "watchGachaConfig": false,
        "enableShopItems": true,
        "staminaUsage": true,
        "energyUsage": false,
        "rates": {
          "adventureExp": 1.0,
          "mora": 1.0,
          "leyLines": 1.0
        }
      },
      "joinOptions": {
        "welcomeEmotes": [
          2007,
          1002,
          4010
        ],
        "welcomeMessage": "Welcome to a Grasscutter server.",
        "welcomeMail": {
          "title": "Welcome to Grasscutter!",
          "content": "Hi there!\r\nFirst of all, welcome to Grasscutter. If you have any issues, please let us know so that Lawnmower can help you! \r\n\r\nCheck out our:\r\n\u003ctype\u003d\"browser\" text\u003d\"Discord\" href\u003d\"https://discord.gg/T5vZU6UyeG\"/\u003e\n",
          "sender": "Lawnmower",
          "items": [
            {
              "itemId": 13509,
              "itemCount": 1,
              "itemLevel": 1
            },
            {
              "itemId": 201,
              "itemCount": 99999,
              "itemLevel": 1
            }
          ]
        }
      },
      "serverAccount": {
        "avatarId": 10000007,
        "nameCardId": 210001,
        "adventureRank": 1,
        "worldLevel": 0,
        "nickName": "Server",
        "signature": "Welcome to Grasscutter!"
      }
    },
    "dispatch": {
      "regions": [],
      "defaultName": "Grasscutter"
    }
  },
  "version": 3
}

**Comment by yijiangchengming** [comment]
21:43:13 ERROR:ResourceLoader Unable to load quest keys.
Exception in thread "main" java.lang.RuntimeException: Port already in use. Make sure no other process is using port 443 and try again.
如果你会翻译的话，显然第一个错误是资源加载错误，请检测资源项是否正确放置。
第二个是端口已被占用，百度一下就知道怎么处理。

**Comment by KiminaNatsuki** [comment]
> 如果你会翻译的话，显然第一个错误是资源加载错误，请检测资源项是否正确放置。
第二个是端口已被占用，百度一下就知道怎么处理。
