### ISSUE TITLE
[Bug] Error compiling leads to exception in Grasscutter

### ISSUE THREAD

**Issue by xNissX233** [Melledy/Grasscutter#1578]
**Did you look for other closed issues that have the same problem?**
Yes.

**Describe the bug**
When compiling, I get this error:

`15:55:03 <INFO:ResourceLoader> Loading resources...
15:55:03 <ERROR:ResourceLoader> Unable to load quest keys.
java.lang.NullPointerException: null
        at java.base/java.io.Reader.<init>(Reader.java:168)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:76)
        at emu.grasscutter.data.DataLoader.loadReader(DataLoader.java:45)
        at emu.grasscutter.data.ResourceLoader.loadQuests(ResourceLoader.java:421)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:69)
        at emu.grasscutter.tools.ToolsWithLanguageOption.createGmHandbook(Tools.java:94)
        at emu.grasscutter.tools.Tools.createGmHandbook(Tools.java:36)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:98)
15:55:03 <INFO:ResourceLoader> Finished loading resources.
15:55:04 <INFO:ToolsWithLanguageOption> GM Handbook generated!
Replacing IP address in server config...
Generating CA key and certificate pair...
Generating a RSA private key
`
It finishes ok, and I have the .jar

But when trying to run Grasscutter I get this:
`<ERROR:ResourceLoader> Unable to load quest keys.
java.lang.NullPointerException: null
        at java.base/java.io.Reader.<init>(Reader.java:168)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:76)
        at emu.grasscutter.data.DataLoader.loadReader(DataLoader.java:45)
        at emu.grasscutter.data.ResourceLoader.loadQuests(ResourceLoader.java:421)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:69)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:160)
`

And a white screen when login ingame, and this:

`15:55:37 <INFO:RegionHandler> Client 127.0.0.1 request: query_cur_region/os_usa
15:55:47 <INFO:GameSession> Client connected from /127.0.0.1:55046
 java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.excels.QuestData.getId()" because "config" is null
        at emu.grasscutter.game.quest.GameQuest.setConfig(GameQuest.java:124)
        at emu.grasscutter.game.quest.QuestManager.loadFromDatabase(QuestManager.java:325)
        at emu.grasscutter.game.player.Player.loadFromDatabase(Player.java:1328)
        at emu.grasscutter.server.packet.recv.HandlerGetPlayerTokenReq.handle(HandlerGetPlayerTokenReq.java:96)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:247)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
15:56:47 <INFO:GameSession> Client disconnected from /127.0.0.1:55046
`

**Which branch did you use?**
Latest: 

  Grasscutter version: 1.2.3-dev
  Git Hash: 3ef2c081

**Additional context**
It was working fine 10 commits or so ago.

**Comment by Saint-Theana** [comment]
missing QuestEncryptionKeys.json file in data folder

**Comment by xNissX233** [comment]
> missing QuestEncryptionKeys.json file in data folder

Can you elaborate? is that my fault? do I need to add that file manually?

**Comment by Saint-Theana** [comment]
and also if there was already quests in database it waould probably cause null pointer exception.

**Comment by Saint-Theana** [comment]
> 

you can search the repo,the file exists in a commit.I dont know the detail.but just search it.

**Comment by xNissX233** [comment]
> > 
> 
> you can search the repo,the file exists in a commit.I dont know the detail.but just search it.

But if that need to be done manually, then it's a problem in the repo, isn't it?

**Comment by Saint-Theana** [comment]
and by the way even if you puted the missing file where it should be and clear the quests in database,it might also causes null pointer exception,this is what I am facing.
java.lang.NullPointerException: Cannot read field "draft_id" because "this.metaGadget" is null
        at emu.grasscutter.game.entity.EntityGadget.toProto(EntityGadget.java:221)
        at emu.grasscutter.server.packet.send.PacketSceneEntityAppearNotify.lambda$new$0(PacketSceneEntityAppearNotify.java:45)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at emu.grasscutter.server.packet.send.PacketSceneEntityAppearNotify.<init>(PacketSceneEntityAppearNotify.java:45)
        at emu.grasscutter.game.world.Scene.checkSpawns(Scene.java:557)
        at emu.grasscutter.game.world.Scene.onTick(Scene.java:430)
        at emu.grasscutter.game.world.World.onTick(World.java:319)
        at emu.grasscutter.server.game.GameServer.onTick(GameServer.java:231)
        at emu.grasscutter.server.game.GameServer$1.run(GameServer.java:263)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
> java.lang.NullPointerException: Cannot read field "draft_id" because "this.metaGadget" is null
        at emu.grasscutter.game.entity.EntityGadget.toProto(EntityGadget.java:221)
        at emu.grasscutter.server.packet.send.PacketSceneEntityAppearNotify.lambda$new$0(PacketSceneEntityAppearNotify.java:45)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at emu.grasscutter.server.packet.send.PacketSceneEntityAppearNotify.<init>(PacketSceneEntityAppearNotify.java:45)
        at emu.grasscutter.game.world.Scene.showOtherEntities(Scene.java:361)
        at emu.grasscutter.server.packet.recv.HandlerEnterSceneDoneReq.handle(HandlerEnterSceneDoneReq.java:28)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:247)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Saint-Theana** [comment]
> > > 
> > 
> > 
> > you can search the repo,the file exists in a commit.I dont know the detail.but just search it.
> 
> But if that need to be done manually, then it's a problem in the repo, isn't it?

My suggestion is waitting for some moment.

**Comment by Hartie95** [comment]
> > > 
> > 
> > 
> > you can search the repo,the file exists in a commit.I dont know the detail.but just search it.
> 
> But if that need to be done manually, then it's a problem in the repo, isn't it?

The file is only needed for 2.7+ prerendered cutscene support, not having the QuestEncryptionKeys.json file should not break anything. 
In the future it will probably be included in the grasscutter resources, instead of the data folder, but for now it needs to be placed in the data folder, if you want to support 2.7+ cutscenes.

**Comment by xNissX233** [comment]
> > > > 
> > > 
> > > 
> > > you can search the repo,the file exists in a commit.I dont know the detail.but just search it.
> > 
> > 
> > But if that need to be done manually, then it's a problem in the repo, isn't it?
> 
> The file is only needed for 2.7+ prerendered cutscene support, not having the QuestEncryptionKeys.json file should not break anything. In the future it will probably be included in the grasscutter resources, instead of the data folder, but for now it needs to be placed in the data folder, if you want to support 2.7+ cutscenes.

Then if that file is not the problem, what's it?

**Comment by Hartie95** [comment]
> and by the way even you put the missing file where it should be and clear the quests in database,it might also causes null pointer exception,this is what I am facing. java.lang.NullPointerException: Cannot read field "draft_id" because "this.metaGadget" is null at emu.grasscutter.game.entity.EntityGadget.toProto(EntityGadget.java:221) at emu.grasscutter.server.packet.send.PacketSceneEntityAppearNotify.lambda$new$0(PacketSceneEntityAppearNotify.java:45) at java.base/java.lang.Iterable.forEach(Iterable.java:75) at emu.grasscutter.server.packet.send.PacketSceneEntityAppearNotify.(PacketSceneEntityAppearNotify.java:45) at emu.grasscutter.game.world.Scene.checkSpawns(Scene.java:557) at emu.grasscutter.game.world.Scene.onTick(Scene.java:430) at emu.grasscutter.game.world.World.onTick(World.java:319) at emu.grasscutter.server.game.GameServer.onTick(GameServer.java:231) at emu.grasscutter.server.game.GameServer$1.run(GameServer.java:263) at java.base/java.util.TimerThread.mainLoop(Timer.java:566) at java.base/java.util.TimerThread.run(Timer.java:516)
> 
> > java.lang.NullPointerException: Cannot read field "draft_id" because "this.metaGadget" is null
> > at emu.grasscutter.game.entity.EntityGadget.toProto(EntityGadget.java:221)
> > at emu.grasscutter.server.packet.send.PacketSceneEntityAppearNotify.lambda$new$0(PacketSceneEntityAppearNotify.java:45)
> > at java.base/java.lang.Iterable.forEach(Iterable.java:75)
> > at emu.grasscutter.server.packet.send.PacketSceneEntityAppearNotify.(PacketSceneEntityAppearNotify.java:45)
> > at emu.grasscutter.game.world.Scene.showOtherEntities(Scene.java:361)
> > at emu.grasscutter.server.packet.recv.HandlerEnterSceneDoneReq.handle(HandlerEnterSceneDoneReq.java:28)
> > at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
> > at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:247)
> > at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
> > at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
> > at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
> > at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
> > at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
> > at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> > at java.base/java.lang.Thread.run(Thread.java:833)

That will be fixed in this pr:
https://github.com/Grasscutters/Grasscutter/pull/1579

You can also get around it for now by enabling scripts in the big world in the config file.


> > > > > 
> > > > 
> > > > 
> > > > you can search the repo,the file exists in a commit.I dont know the detail.but just search it.
> > > 
> > > 
> > > But if that need to be done manually, then it's a problem in the repo, isn't it?
> > 
> > 
> > The file is only needed for 2.7+ prerendered cutscene support, not having the QuestEncryptionKeys.json file should not break anything. In the future it will probably be included in the grasscutter resources, instead of the data folder, but for now it needs to be placed in the data folder, if you want to support 2.7+ cutscenes.
> 
> Then if that file is not the problem, what's it?

Something in the grasscutter code, maybe from the quest refactoring, you could try enabling scripts in big world for now, and see if that fixes it.

**Comment by Saint-Theana** [comment]
> > > > > 
> > > > 
> > > > 
> > > > you can search the repo,the file exists in a commit.I dont know the detail.but just search it.
> > > 
> > > 
> > > But if that need to be done manually, then it's a problem in the repo, isn't it?
> > 
> > 
> > The file is only needed for 2.7+ prerendered cutscene support, not having the QuestEncryptionKeys.json file should not break anything. In the future it will probably be included in the grasscutter resources, instead of the data folder, but for now it needs to be placed in the data folder, if you want to support 2.7+ cutscenes.
> 
> Then if that file is not the problem, what's it?

There are already two PRs that fix the problems.

**Comment by xNissX233** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > you can search the repo,the file exists in a commit.I dont know the detail.but just search it.
> > > > 
> > > > 
> > > > But if that need to be done manually, then it's a problem in the repo, isn't it?
> > > 
> > > 
> > > The file is only needed for 2.7+ prerendered cutscene support, not having the QuestEncryptionKeys.json file should not break anything. In the future it will probably be included in the grasscutter resources, instead of the data folder, but for now it needs to be placed in the data folder, if you want to support 2.7+ cutscenes.
> > 
> > 
> > Then if that file is not the problem, what's it?
> 
> There are already two PRs that fix the problems.

Oh I didn't see them, my bad. This community is so fast solving this kind of critical errors D:
