### ISSUE TITLE
[Bug] grasscutter-1.2.3-dev#122 使用指令help时报错

### ISSUE THREAD

**Issue by kkm27** [Melledy/Grasscutter#1615]
**Did you look for other closed issues that have the same problem?**

没有
**Describe the bug**

当在cmd控制台中使用指令help时报错
```
<ERROR:Grasscutter> 命令发生错误：
java.lang.annotation.AnnotationTypeMismatchException: Incorrectly typed data found for annotation element public abstract java.lang.String[] emu.grasscutter.command.Command.usage() (Found data of type java.lang.String[setconstellations [0-6/all]])
        at java.base/sun.reflect.annotation.AnnotationTypeMismatchExceptionProxy.generateException(AnnotationTypeMismatchExceptionProxy.java:59)
        at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:89)
        at jdk.proxy2/jdk.proxy2.$Proxy21.usage(Unknown Source)
        at emu.grasscutter.command.CommandHandler.getUsageString(CommandHandler.java:56)
        at emu.grasscutter.command.commands.HelpCommand.createCommand(HelpCommand.java:22)
        at emu.grasscutter.command.commands.HelpCommand.execute(HelpCommand.java:57)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:276)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:280)
        at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:387)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:212)
```
**Which branch did you use?**

grasscutter-1.2.3-dev
f73cadec
**Screenshots**

![image](https://user-images.githubusercontent.com/58660073/182674587-206a95cb-e1ec-47e4-9604-c8a88f5fa8fd.png)

**Additional context**

**Comment by ERthereal** [comment]
把你的enka插件删掉

**Comment by ERthereal** [comment]
现在能带动的好像就这3个
![image](https://user-images.githubusercontent.com/58130955/182717702-3203a19e-3dfc-4a8b-a821-c7adc3003354.png)

**Comment by Birdulon** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/5397662/182740462-3adce604-87c3-4599-8b6c-5ce3493fd9f6.png">

**Comment by KiminaNatsuki** [comment]
Please remove your plugin "SetConstellations" and try again.
