### ISSUE TITLE
[Bug] Serenitea pot building system broken

### ISSUE THREAD

**Issue by xNissX233** [Melledy/Grasscutter#1657]
**Did you look for other closed issues that have the same problem?**
Yes, and someone has reported it in the pull request that implemented Serenitea pot long time ago, but no new issues have been created.

**Describe the bug**
When trying to build inside the Serenitea pot, it doesn't work. In game version 2.7 it was working fine, but now in 2.8 it seems to be broken.
This is the server log:
> java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.home.HomeSceneItem.calComfort()" because "homeRoomScene" is null
        at emu.grasscutter.server.packet.send.PacketHomeComfortInfoNotify.<init>(PacketHomeComfortInfoNotify.java:35)
        at emu.grasscutter.server.packet.recv.HandlerHomeChangeEditModeReq.handle(HandlerHomeChangeEditModeReq.java:19)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:247)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Which branch did you use?**
  Grasscutter version:  1.2.3-dev
  Git Hash: 283a8819

**Comment by pfyy** [comment]
fixed
