### ISSUE TITLE
[Bug] The server crashs when starting

### ISSUE THREAD

**Issue by L4cache** [Melledy/Grasscutter#1687]
**Describe the bug**

The server crashs when starting.
When use https://github.com/Koko-boya/Grasscutter_Resources/tree/c6844f41c59827f6ba785847d2d4081a35441b6c
```
Exception in thread "main" java.lang.NullPointerException: Cannot read field "strings" because "desc" is null
        at emu.grasscutter.tools.Tools.lambda$createGmHandbooks$14(Tools.java:95)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.base/java.util.stream.SortedOps$SizedIntSortingSink.end(SortedOps.java:455)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateSequential(ForEachOps.java:188)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.IntPipeline.forEach(IntPipeline.java:463)
        at emu.grasscutter.tools.Tools.createGmHandbooks(Tools.java:89)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:105)
```
When use https://github.com/Koko-boya/Grasscutter_Resources/tree/6bcca98ee010a7715897651c5c9027b241dbc352
```
Exception in thread "main" java.util.NoSuchElementException: No value present
        at java.base/java.util.OptionalInt.getAsInt(OptionalInt.java:130)
        at emu.grasscutter.tools.Tools.createGmHandbooks(Tools.java:88)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:105)
```
**Which branch did you use?**

development branch
https://github.com/Grasscutters/Grasscutter/tree/36b71d01985602bef8debf33cb699c064fd62bcd

When use https://github.com/Koko-boya/Grasscutter_Resources/tree/c6844f41c59827f6ba785847d2d4081a35441b6c
![2022-08-23_030351](https://user-images.githubusercontent.com/42721712/185998955-3254c169-ceed-4ba9-a0f0-d30b8553543b.png)

When use https://github.com/Koko-boya/Grasscutter_Resources/tree/6bcca98ee010a7715897651c5c9027b241dbc352
![2022-08-23_025638](https://user-images.githubusercontent.com/42721712/185997679-e6ed98d9-62d9-44e8-8d1f-4ca9cb565040.png)

**Comment by ERthereal** [comment]
Try deleting all unnecessary files in the Grasscutter folder and recompiling the grasscutter .jar

**Comment by L4cache** [comment]
> Try deleting all unnecessary files in the Grasscutter folder and recompiling the grasscutter .jar

You are right! Turns out the "cache" folder interfered the loading. 
Seems like a different version or corrupted resource file initially caused this problem, and things never work until the cache folder is deleted.
(~QuestEncryptionKeys.json~ QuestExcelConfigData.json has great difference in size between 2.8 and 3.0 resource, so I suspect it's corrupted)

**Comment by L4cache** [comment]
[global-metadata.zip](https://github.com/Grasscutters/Grasscutter/files/9409721/global-metadata.zip)
I tried to patch metadata for 3.0 CN REL
Seems ok-ish

**Comment by ERthereal** [comment]
> [全局元数据.zip](https://github.com/Grasscutters/Grasscutter/files/9409721/global-metadata.zip)我试图修补3.0 CN REL的元数据似乎还行

Thank you, I think I need him

**Comment by Gmskjunior** [comment]
Exit

Em qua., 24 de ago. de 2022 23:45, 李四 ***@***.***> escreveu:
