### ISSUE TITLE
[Bug] Error during game update, getMonsterLevel can't invoke due to return value being null

### ISSUE THREAD

**Issue by SoftwareGuy** [Melledy/Grasscutter#1693]
**Did you look for other closed issues that have the same problem?**

Yes.

**Describe the bug**

When logged into the Grasscutter server and walking around in the area where you start off in (near a beach), I notice in the server logs that it cannot get the Monster Level of the current map (?). The error emitted is as follows:

```
17:04:12 <ERROR:GameServer$1> An error occurred during game update.
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.excels.WorldLevelData.getMonsterLevel()" because the return value of "it.unimi.dsi.fastutil.ints.Int2ObjectMap.get(int)" is null
        at emu.grasscutter.game.managers.blossom.BlossomManager.notifyIcon(BlossomManager.java:130)
        at emu.grasscutter.game.managers.blossom.BlossomManager.recycleGadgetEntity(BlossomManager.java:63)
        at emu.grasscutter.game.world.Scene.checkSpawns(Scene.java:481)
        at emu.grasscutter.game.world.Scene.onTick(Scene.java:346)
        at emu.grasscutter.game.world.World.lambda$onTick$1(World.java:336)
        at it.unimi.dsi.fastutil.ints.Int2ObjectMap.lambda$forEach$0(Int2ObjectMap.java:249)
        at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapEntrySet.fastForEach(Int2ObjectOpenHashMap.java:1027)
        at it.unimi.dsi.fastutil.ints.Int2ObjectMap.forEach(Int2ObjectMap.java:251)
        at it.unimi.dsi.fastutil.ints.Int2ObjectMaps$SynchronizedMap.forEach(Int2ObjectMaps.java:417)
        at emu.grasscutter.game.world.World.onTick(World.java:336)
        at java.base/java.util.Collection.removeIf(Collection.java:576)
        at java.base/java.util.Collections$SynchronizedCollection.removeIf(Collections.java:2135)
        at emu.grasscutter.server.game.GameServer.onTick(GameServer.java:220)
        at emu.grasscutter.server.game.GameServer$1.run(GameServer.java:249)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)
```

Resources seem to be intact and functioning. Unsure what the problem is - GI 2.8 thing?

**Which branch did you use?**
Grasscutter v1.2.3-dev
Hash: 6e35625f1a10e3f1a93df072c026ef16ed891992

**Screenshots**

![image](https://user-images.githubusercontent.com/1762115/186093993-cc229f5f-c2c0-42b4-a2e3-621a75c06436.png)

**Additional context**

Using a fresh user account, slowly migrating from my official server profile.

**Comment by SoftwareGuy** [comment]
Seems to be related to blossom. Had a fix from the discord:
```
Theo — Today at 5:12 PM
something too do with the blossom, what i found too fix that i did /setprop worldlevel 1 and so trees can spawn
```

Going to mark as fixed for now.
