### ISSUE TITLE
[Bug] Error loading resource file: [QuestExcelConfigData.json]

### ISSUE THREAD

**Issue by RC4-sys** [Melledy/Grasscutter#1705]
```
15:40:07 <INFO:Language> Loading cached TextMaps
15:40:07 <INFO:ResourceLoader> 正在加载 resources...
15:40:08 <ERROR:ResourceLoader> Error loading resource file: [QuestExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 19 column 28 path $[0].finishCondComb
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:225)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.Gson.fromJson(Gson.java:991)
        at com.google.gson.Gson.fromJson(Gson.java:956)
        at emu.grasscutter.utils.JsonUtils.loadToList(JsonUtils.java:46)
        at emu.grasscutter.utils.JsonUtils.loadToList(JsonUtils.java:51)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:125)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:116)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:105)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:67)
        at emu.grasscutter.tools.Tools.createGmHandbooks(Tools.java:35)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:105)
Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 19 column 28 path $[0].finishCondComb
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825)
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.read(TypeAdapters.java:823)
        at com.google.gson.internal.bind.TypeAdapters$EnumTypeAdapter.read(TypeAdapters.java:776)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        ... 13 common frames omitted
15:40:09 <INFO:ResourceLoader> 完成加载 resources。
Exception in thread "main" java.util.NoSuchElementException: No value present
        at java.base/java.util.OptionalInt.getAsInt(OptionalInt.java:130)
        at emu.grasscutter.tools.Tools.createGmHandbooks(Tools.java:88)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:105)
```

**Comment by Liujunhua007** [comment]
I guess this is because latest action still no surporting  3.0 resources.

**Comment by RC4-sys** [comment]
> I guess this is because latest action still no surporting 3.0 resources.

this issues was Solved,but I can't solve it in the same way
https://github.com/Grasscutters/Grasscutter/issues/1687

**Comment by Gmskjunior** [comment]
Exit

Em qui., 25 de ago. de 2022 09:53, Liujunhua007 ***@***.***>
escreveu:
