### ISSUE TITLE
[Bug] Can't reach Paimon. Class cannot be created (missing no-arg constructor) when adding quest 35100 (starting quest).

### ISSUE THREAD

**Issue by FloeHetling** [Melledy/Grasscutter#1747]
**Did you look for other closed issues that have the same problem?**
yes

**Describe the bug**
Steps:
 - Create a new character in new Mongo base of fresh installation
 - Enter the Game
 - Choose Male character / Choose Female Character (tried both)
 - On the beach, add starting quest using command:
    `<INFO:CommandMap> Command used by [FloeHetling (Player UID: 10001)]: quest add 35100`
Visual problem:
 - Can't reach Paimon since they are ~3000m away (XYZ 0,0,0)

**Which branch did you use?**
Grasscutter version: 1.3.0-1555010
https://github.com/Grasscutters/Grasscutter/commit/155501058fcce109489a19db37d0513d2235e08e (Latest 1.3.0)

**Logs**
```
  <INFO:LuaSerializer> {data_index=0, room_id=0, id=1005, alias=Paimon, script=Actor/Quest/Q352/Paimon, pos=Q351FirstClimb, scene_id=3}
  > java.lang.RuntimeException: Class cannot be created (missing no-arg constructor): sun.reflect.generics.reflectiveObjects.TypeVariableImpl
          at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:68)
          at emu.grasscutter.scripts.serializer.LuaSerializer.cacheType(LuaSerializer.java:191)
          at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:139)
          at emu.grasscutter.scripts.serializer.LuaSerializer.serializeList(LuaSerializer.java:97)
          at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:130)
          at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:161)
          at emu.grasscutter.scripts.serializer.LuaSerializer.serializeMap(LuaSerializer.java:54)
          at emu.grasscutter.scripts.serializer.LuaSerializer.toMap(LuaSerializer.java:35)
          at emu.grasscutter.game.quest.GameMainQuest.addRewindPoints(GameMainQuest.java:208)
          at emu.grasscutter.game.quest.GameMainQuest.<init>(GameMainQuest.java:80)
          at emu.grasscutter.game.quest.QuestManager.addMainQuest(QuestManager.java:178)
          at emu.grasscutter.game.quest.QuestManager.addQuest(QuestManager.java:197)
          at emu.grasscutter.command.commands.QuestCommand.execute(QuestCommand.java:34)
          at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:310)
          at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:314)
          at emu.grasscutter.game.chat.ChatSystem.tryInvokeCommand(ChatSystem.java:46)
          at emu.grasscutter.game.chat.ChatSystem.sendPrivateMessage(ChatSystem.java:141)
          at emu.grasscutter.server.packet.recv.HandlerPrivateChatReq.handle(HandlerPrivateChatReq.java:18)
          at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
          at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:247)
          at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
          at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
          at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
          at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
          at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
          at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
          at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.NoSuchMethodException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl.<init>()
          at java.base/java.lang.Class.getConstructor0(Class.java:3585)
          at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
          at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:65)
          ... 26 more
  22:59:03 <INFO:LuaSerializer> {data_index=0, room_id=0, id=1005, alias=Paimon, script=Actor/Quest/Q352/Paimon, pos=Q351FirstQuest, scene_id=3}
  > java.lang.RuntimeException: Class cannot be created (missing no-arg constructor): sun.reflect.generics.reflectiveObjects.TypeVariableImpl
          at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:68)
          at emu.grasscutter.scripts.serializer.LuaSerializer.cacheType(LuaSerializer.java:191)
          at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:139)
          at emu.grasscutter.scripts.serializer.LuaSerializer.serializeList(LuaSerializer.java:97)
          at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:130)
          at emu.grasscutter.scripts.serializer.LuaSerializer.serialize(LuaSerializer.java:161)
          at emu.grasscutter.scripts.serializer.LuaSerializer.serializeMap(LuaSerializer.java:54)
          at emu.grasscutter.scripts.serializer.LuaSerializer.toMap(LuaSerializer.java:35)
          at emu.grasscutter.game.quest.GameMainQuest.addRewindPoints(GameMainQuest.java:208)
          at emu.grasscutter.game.quest.GameMainQuest.<init>(GameMainQuest.java:80)
          at emu.grasscutter.game.quest.QuestManager.addMainQuest(QuestManager.java:178)
          at emu.grasscutter.game.quest.QuestManager.addQuest(QuestManager.java:197)
          at emu.grasscutter.command.commands.QuestCommand.execute(QuestCommand.java:34)
          at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:310)
          at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:314)
          at emu.grasscutter.game.chat.ChatSystem.tryInvokeCommand(ChatSystem.java:46)
          at emu.grasscutter.game.chat.ChatSystem.sendPrivateMessage(ChatSystem.java:141)
          at emu.grasscutter.server.packet.recv.HandlerPrivateChatReq.handle(HandlerPrivateChatReq.java:18)
          at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
          at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:247)
          at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
          at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
          at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
          at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
          at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
          at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
          at java.base/java.lang.Thread.run(Thread.java:833)
  Caused by: java.lang.NoSuchMethodException: sun.reflect.generics.reflectiveObjects.TypeVariableImpl.<init>()
          at java.base/java.lang.Class.getConstructor0(Class.java:3585)
          at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
          at com.esotericsoftware.reflectasm.ConstructorAccess.get(ConstructorAccess.java:65)
```

**Additional context**
  - Upon teleporting to 0,0,0 there's a platform under world, no Paimon visible nearby, quest cannot continue.

**Comment by Hartie95** [comment]
You need to start with quest 35104 (its the cutscene part), since its the first of the 351 series, not 35100.
Also to get a bit further in (until the use elemental skill), use these resources, since they contain a few fixes for the lua lib used by grasscutter (luaj): https://github.com/Hartie95/Grasscutter_Resources/tree/script_fixes

**Comment by FloeHetling** [comment]
Roger, I'll try that and report back. Thanks!
