### ISSUE TITLE
[Bug] 启动时错误，大量报错

### ISSUE THREAD

**Issue by awaae001** [Melledy/Grasscutter#1763]
Exception in thread "main" com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: no further information}}]
        at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:177)
        at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
        at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:127)
        at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:87)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:258)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:182)
        at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:847)
        at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:830)
        at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:825)
        at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:810)
        at dev.morphia.annotations.builders.IndexHelper.createIndex(IndexHelper.java:220)
        at dev.morphia.annotations.builders.IndexHelper.createIndex(IndexHelper.java:210)
        at dev.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:186)
        at emu.grasscutter.database.DatabaseManager.initialize(DatabaseManager.java:73)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:118)

以上是报错信息

版本
grasscutter-1.3.0.jar

所有资源正常
环境正常
每过一段时间就崩溃

**Comment by Birdulon** [comment]
Mongodb must be running before you start Grasscutter. If you have configured mongodb to use a different port, you will need to configure Grasscutter appropriately.

**Comment by awaae001** [comment]
谢谢，问题已解决
thanks for the issue resolved

**Comment by IQPILLS** [comment]
I have the same issue but pretty sure ports are the same and mongodb is running. 
Using grasscutter-1.3.2-dev-fbc0219 in Pterodactyl 

![powershell_s0h0kcuYJl](https://user-images.githubusercontent.com/72296110/192089802-0ff20c43-f76f-4f4e-b774-587211cdc0d1.png)
![powershell_PS5HTjxTZp](https://user-images.githubusercontent.com/72296110/192089852-69c9b9e2-c892-4186-a272-ad744b1c6c4a.png)

**Comment by IQPILLS** [comment]
My error message:
```
Exception in thread "main" com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]
        at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:177)
        at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:41)
        at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:127)
        at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:87)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:258)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:182)
        at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:847)
        at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:830)
        at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:825)
        at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:810)
        at dev.morphia.annotations.builders.IndexHelper.createIndex(IndexHelper.java:220)
        at dev.morphia.annotations.builders.IndexHelper.createIndex(IndexHelper.java:210)
        at dev.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:186)
        at emu.grasscutter.database.DatabaseManager.ensureIndexes(DatabaseManager.java:89)
        at emu.grasscutter.database.DatabaseManager.initialize(DatabaseManager.java:70)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:118)
```
