### ISSUE TITLE
[Bug] 尝试使用java -jar grasscutter.jar运行时报错

### ISSUE THREAD

**Issue by QwQIsHidden** [Melledy/Grasscutter#1799]
Grasscutter版本：Grasscutter version: 1.3.2-dev-a90455a7
报错内容：Exception in thread "main" java.lang.NullPointerException: Cannot read field "strings" because "desc" is null
        at emu.grasscutter.tools.Tools.lambda$createGmHandbooks$14(Tools.java:95)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.accept(ForEachOps.java:204)
        at java.base/java.util.stream.SortedOps$SizedIntSortingSink.end(SortedOps.java:455)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfInt.evaluateSequential(ForEachOps.java:188)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.IntPipeline.forEach(IntPipeline.java:463)
        at emu.grasscutter.tools.Tools.createGmHandbooks(Tools.java:89)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:106)

**Comment by wohnhier** [comment]
请问怎么解决的这个报错
