### ISSUE TITLE
Monitoring thread exceptions

### ISSUE THREAD

**Issue by yanhuo218** [Melledy/Grasscutter#191]
[21:54:13] [INFO] Starting Grasscutter...
[21:54:13] [INFO] Loaded 300 AvatarTalentDatas.
[21:54:13] [INFO] Loaded 400 AvatarSkillDatas.
[21:54:13] [INFO] Loaded 3794 FetterDatas.
[21:54:13] [INFO] Loaded 73 AvatarSkillDepotDatas.
[21:54:13] [INFO] Loaded 167 MonsterDescribeDatas.
[21:54:13] [INFO] Loaded 1 AvatarCostumeDatas.
[21:54:13] [INFO] Loaded 3032 NpcDatas.
[21:54:13] [INFO] Loaded 66 ReliquaryMainPropDatas.
[21:54:13] [INFO] Loaded 200 MonsterCurveDatas.
[21:54:13] [INFO] Loaded 717 SceneDatas.
[21:54:13] [INFO] Loaded 90 AvatarLevelDatas.
[21:54:13] [INFO] Loaded 6889 ItemDatas.
[21:54:13] [INFO] Loaded 336 AvatarPromoteDatas.
[21:54:13] [INFO] Loaded 335 ReliquaryAffixDatas.
[21:54:13] [INFO] Loaded 90 WeaponLevelDatas.
[21:54:13] [INFO] Loaded 939 WeaponPromoteDatas.
[21:54:13] [INFO] Loaded 9 AvatarFlycloakDatas.
[21:54:13] [INFO] Loaded 6626 GadgetDatas.
[21:54:13] [INFO] Loaded 100 AvatarCurveDatas.
[21:54:13] [INFO] Loaded 42 ReliquarySetDatas.
[21:54:13] [INFO] Loaded 100 WeaponCurveDatas.
[21:54:13] [INFO] Loaded 744 EquipAffixDatas.
[21:54:13] [INFO] Loaded 60 PlayerLevelDatas.
[21:54:13] [INFO] Loaded 101 ReliquaryLevelDatas.
[21:54:13] [INFO] Loaded 2420 ProudSkillDatas.
[21:54:13] [INFO] Loaded 568 MonsterDatas.
[21:54:13] [INFO] Loaded 78 AvatarDatas.
[21:54:13] [ERROR] Scene point files cannot be found, you cannot use teleport waypoints!
[21:54:13] [ERROR] Relic properties are missing weights! Please check your ReliquaryMainPropExcelConfigData or ReliquaryAffixExcelConfigData files in your ExcelBinOutput folder.
[21:54:13] [INFO] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[21:54:13] [INFO] Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:70)
        at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:143)
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:188)
        at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:144)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.ConnectException: Connection refused: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:539)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:594)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:78)
        at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:79)
        at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65)
        ... 4 common frames omitted
[21:54:13] [INFO] Cluster description not yet available. Waiting for 30000 ms before timing out
Exception in thread "main" com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused: no further information}}]
        at com.mongodb.internal.connection.BaseCluster.getDescription(BaseCluster.java:177)
        at com.mongodb.internal.connection.SingleServerCluster.getDescription(SingleServerCluster.java:42)
        at com.mongodb.client.internal.MongoClientDelegate.getConnectedClusterDescription(MongoClientDelegate.java:135)
        at com.mongodb.client.internal.MongoClientDelegate.createClientSession(MongoClientDelegate.java:95)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.getClientSession(MongoClientDelegate.java:266)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:190)
        at com.mongodb.client.internal.MongoCollectionImpl.executeCreateIndexes(MongoCollectionImpl.java:847)
        at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:830)
        at com.mongodb.client.internal.MongoCollectionImpl.createIndexes(MongoCollectionImpl.java:825)
        at com.mongodb.client.internal.MongoCollectionImpl.createIndex(MongoCollectionImpl.java:810)
        at dev.morphia.IndexHelper.createIndex(IndexHelper.java:362)
        at dev.morphia.IndexHelper.createIndex(IndexHelper.java:350)
        at dev.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:956)
        at dev.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:950)
        at emu.grasscutter.database.DatabaseManager.initialize(DatabaseManager.java:69)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:73)

**Comment by alt3ri** [comment]
Your mongodb, have you turned it on?

**Comment by yanhuo218** [comment]
> 你的mongodb，你打开了吗？

Open the
