### ISSUE TITLE
[Bug] 在搭建Grasscutter时，出现Invalid keystore format错误

### ISSUE THREAD

**Issue by lclty** [Melledy/Grasscutter#1944]
完整日志：
> root@luotianyi:/usr/local/grasscutter# java -jar grasscutter.jar
07:42:23 <INFO:Grasscutter> Starting Grasscutter...
07:42:23 <INFO:Grasscutter> Game version: 3.2.0
07:42:23 <INFO:Grasscutter> Grasscutter version: 1.4.3-5c4c62c1
07:42:23 <INFO:ResourceLoader> Loading resources...
07:42:27 <INFO:ResourceLoader> Finished loading resources.
07:42:27 <INFO:Language> Loading cached TextMaps
07:42:28 <INFO:Tools> GM Handbooks generated!
Exception in thread "main" io.javalin.core.util.JavalinException: java.io.IOException: Invalid keystore format
        at io.javalin.Javalin.start(Javalin.java:188)
        at io.javalin.Javalin.start(Javalin.java:148)
        at io.javalin.Javalin.start(Javalin.java:134)
        at emu.grasscutter.server.http.HttpServer.start(HttpServer.java:136)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:146)
Caused by: java.io.IOException: Invalid keystore format
        at java.base/sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:688)
        at java.base/sun.security.util.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:221)
        at java.base/java.security.KeyStore.load(KeyStore.java:1473)
        at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:54)
        at org.eclipse.jetty.util.ssl.SslContextFactory.loadKeyStore(SslContextFactory.java:1203)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:322)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:244)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.SslConnectionFactory.doStart(SslConnectionFactory.java:97)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.AbstractConnector.doStart(AbstractConnector.java:323)
        at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:81)
        at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:234)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.eclipse.jetty.server.Server.doStart(Server.java:401)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at io.javalin.jetty.JettyServer.start(JettyServer.kt:65)
        at io.javalin.Javalin.start(Javalin.java:174)
        ... 4 more
^C

![QQ截图20221110074409](https://user-images.githubusercontent.com/102938905/200967529-dcc86f2b-b5b9-4bcb-b047-7dec3b0c1453.png)
Google了一下，说是JDK版本与编译Keystore的JDK版本不一致，我把JDK版本从17.0.1到17.0.5都试了一遍，都不行，所以就来反馈是不是一个bug（

**Comment by z3052624057** [comment]
另外在Windows服务器上没有这个错误，我

**Comment by lclty** [comment]
刚不小心点了下 Close ，不好意思
系统是 Ubuntu 20.04.5 LTS （可能被 Alicloud 魔改过）
试了下 Windows Server 2022 ，JDK 17.0.5搭建没有什么问题

**Comment by archiveduser** [comment]
`cat keystore.p12`
看一下证书内容是不是下载失败了，我第一次下载下来是个html文件，会报这个错误。

**Comment by lclty** [comment]
> `cat keystore.p12` 看一下证书内容是不是下载失败了，我第一次下载下来是个html文件，会报这个错误。

好像是个html（
![QQ截图20221110164007](https://user-images.githubusercontent.com/102938905/201042116-1af2d9fb-131c-40d6-97f8-2f0030e397df.png)
nano :
![QQ截图20221110163841](https://user-images.githubusercontent.com/102938905/201041995-0851ee1c-5243-41a9-99e3-59fb1354fd16.png)

**Comment by lclty** [comment]
> `cat keystore.p12` 看一下证书内容是不是下载失败了，我第一次下载下来是个html文件，会报这个错误。

我再试一下吧，谢谢大哥，如果没什么问题我就close了
