### ISSUE TITLE
[Bug] Invalid DynamicFloat definition from loading AbilityModifier

### ISSUE THREAD

**Issue by WJXhhh** [Melledy/Grasscutter#2019]
**Did you look for other closed issues that have the same problem?**
No.没有

**Describe the bug**
Error is on resource loading.It's not clear to me if there's a problem with Resources.
在加载资源中发生错误，我不清楚我的资源文件是否有问题。

16:42:53 <INFO:ResourceLoader> 正在加载 resources...
16:43:05 <WARN:DataLoader> Failed to create gacha mappings.
com.google.gson.JsonSyntaxException: java.io.IOException: Invalid DynamicFloat definition - BEGIN_OBJECT
16:43:05 <INFO:Grasscutter> 正在启动 Grasscutter...
16:43:05 <INFO:Grasscutter> 游戏版本：3.2.0
16:43:05 <INFO:Grasscutter> Grasscutter 版本：1.4.3-5c4c62c1
16:43:05 <INFO:ResourceLoader> 正在加载 resources...
Exception in thread "main" com.google.gson.JsonSyntaxException: java.io.IOException: Invalid DynamicFloat definition - BEGIN_OBJECT
        at com.google.gson.Gson.fromJson(Gson.java:1006)
        at com.google.gson.Gson.fromJson(Gson.java:956)
        at emu.grasscutter.utils.JsonUtils.loadToList(JsonUtils.java:60)
        at emu.grasscutter.utils.JsonUtils.loadToList(JsonUtils.java:72)
        at emu.grasscutter.data.ResourceLoader.loadAbilityModifiers(ResourceLoader.java:263)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at emu.grasscutter.data.ResourceLoader.loadAbilityModifiers(ResourceLoader.java:252)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:62)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:111)
Caused by: java.io.IOException: Invalid DynamicFloat definition - BEGIN_OBJECT
        at emu.grasscutter.utils.JsonAdapters$DynamicFloatAdapter.read(JsonAdapters.java:42)
        at emu.grasscutter.utils.JsonAdapters$DynamicFloatAdapter.read(JsonAdapters.java:21)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.Gson.fromJson(Gson.java:991)
        ... 19 more
``
**Which branch did you use?**
  Grasscutter version: 1.4.3 Release
**Screenshots**

**Additional context**

**Comment by mcoi-dev** [comment]
3.2的jar要搭配3.2的资源文件，3.3的才能搭配3.3的文件

**Comment by mcoi-dev** [comment]
3.2文件分支好像没了

**Comment by WJXhhh** [comment]
听说是资源格式的问题，现在已经用上3.4就没问题了
