### ISSUE TITLE
[Bug] 在windows中搭建出现的报错

### ISSUE THREAD

**Issue by jgc9527** [Melledy/Grasscutter#2035]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**
 无法启动

**Which branch did you use?**

 development

**Screenshots**
 

java -jar grasscutter.jar
20:22:10 <INFO:DataLoader> Creating default '.\data\gacha\mappings.js' data
20:22:14 <INFO:Language> Generating TextMaps cache
20:22:14 <INFO:ResourceLoader> 正在加载 resources...
20:22:17 <WARN:DataLoader> Failed to create gacha mappings.
com.google.gson.JsonSyntaxException: java.io.IOException: Invalid DynamicFloat definition - BOOLEAN
20:22:17 <INFO:Grasscutter> 正在启动 Grasscutter...
20:22:18 <INFO:Grasscutter> 游戏版本：3.2.0
20:22:18 <INFO:Grasscutter> Grasscutter 版本：1.4.3-5c4c62c1
20:22:18 <INFO:ResourceLoader> 正在加载 resources...
Exception in thread "main" com.google.gson.JsonSyntaxException: java.io.IOException: Invalid DynamicFloat definition - BOOLEAN
        at com.google.gson.Gson.fromJson(Gson.java:1006)
        at com.google.gson.Gson.fromJson(Gson.java:956)
        at emu.grasscutter.utils.JsonUtils.loadToList(JsonUtils.java:60)
        at emu.grasscutter.utils.JsonUtils.loadToList(JsonUtils.java:72)
        at emu.grasscutter.data.ResourceLoader.loadAbilityModifiers(ResourceLoader.java:263)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at emu.grasscutter.data.ResourceLoader.loadAbilityModifiers(ResourceLoader.java:252)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:62)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:111)
Caused by: java.io.IOException: Invalid DynamicFloat definition - BOOLEAN
        at emu.grasscutter.utils.JsonAdapters$DynamicFloatAdapter.read(JsonAdapters.java:42)
        at emu.grasscutter.utils.JsonAdapters$DynamicFloatAdapter.read(JsonAdapters.java:21)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)        at com.google.gson.Gson.fromJson(Gson.java:991)
        ... 19 more

**Additional context**

**Comment by wang089** [comment]
你的MongoDB正常启动了吗

**Comment by Umbrozium** [comment]
Hi, having the same problem here. Not sure why it's not working. Both the "failed to create gacha mappings" and the "exception in thread main" is occuring to me as well.

**Comment by pengzhenghao** [comment]
Having the same issue.

**Comment by pengzhenghao** [comment]
The issue is solved via compiling jar by latest github branch (instead of using the release)
