### ISSUE TITLE
[Bug]在windows中搭建出现的报错 

### ISSUE THREAD

**Issue by loocul** [Melledy/Grasscutter#2036]
软件无法启动
The software failed to start
Grasscutter version:1.4.6-70e448d8
System version:Windows 10 19045.2546
Java version:17
Build java:17
Resources version:3.40

PS C:\Users\*\Desktop\Grasscutter> java -jar grasscutter-1.4.6.jar
21:18:34 <INFO:Grasscutter> 正在启动 Grasscutter...
21:18:34 <INFO:Grasscutter> 游戏版本：3.3.0
21:18:34 <INFO:Grasscutter> Grasscutter 版本：1.4.6-70e448d8
21:18:34 <INFO:ResourceLoader> 正在加载 resources...
Exception in thread "main" com.google.gson.JsonSyntaxException: java.io.IOException: Invalid DynamicFloat definition - BOOLEAN
        at com.google.gson.Gson.fromJson(Gson.java:1006)
        at com.google.gson.Gson.fromJson(Gson.java:956)
        at emu.grasscutter.utils.JsonUtils.loadToList(JsonUtils.java:63)
        at emu.grasscutter.utils.JsonUtils.loadToList(JsonUtils.java:75)
        at emu.grasscutter.data.ResourceLoader.loadAbilityModifiers(ResourceLoader.java:306)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at emu.grasscutter.data.ResourceLoader.loadAbilityModifiers(ResourceLoader.java:295)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:87)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:111)
Caused by: java.io.IOException: Invalid DynamicFloat definition - BOOLEAN
        at emu.grasscutter.utils.JsonAdapters$DynamicFloatAdapter.read(JsonAdapters.java:44)
        at emu.grasscutter.utils.JsonAdapters$DynamicFloatAdapter.read(JsonAdapters.java:23)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.Gson.fromJson(Gson.java:991)
        ... 19 more

**Comment by UIJK1** [comment]
解决了吗？

**Comment by Umbrozium** [comment]
Hi, having the same problem here. Not sure why it's not working.

**Comment by pengzhenghao** [comment]
用最新的github repo来自己编译jar，而不是使用release里的jar
