### ISSUE TITLE
[Bug] White screen on login with ver 3.4

### ISSUE THREAD

**Issue by pengzhenghao** [Melledy/Grasscutter#2059]
**Did you look for other closed issues that have the same problem?**

Yes.

**Describe the bug**

White screen and timeout after login.

**Which branch did you use?**

latest one

**Screenshots**

Error message in server:

```
23:12:24 <INFO:DispatchHandler> [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 正在尝试登录
23:12:24 <INFO:RegionHandler> Client 127.0.0.1 request: query_cur_region/os_usa
23:12:33 <INFO:GameSession> 客户端 /127.0.0.1:49299 已连接。
> java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.excels.QuestData.getId()" because "questData" is null
        at emu.grasscutter.game.quest.GameQuest.<init>(GameQuest.java:55)
        at emu.grasscutter.game.quest.GameMainQuest.addAllChildQuests(GameMainQuest.java:86)
        at emu.grasscutter.game.quest.GameMainQuest.<init>(GameMainQuest.java:78)
        at emu.grasscutter.game.quest.QuestManager.addMainQuest(QuestManager.java:178)
        at emu.grasscutter.game.quest.QuestManager.addQuest(QuestManager.java:197)
        at emu.grasscutter.game.player.PlayerProgressManager.addStatueQuestsOnLogin(PlayerProgressManager.java:186)
        at emu.grasscutter.game.player.PlayerProgressManager.onPlayerLogin(PlayerProgressManager.java:43)
        at emu.grasscutter.game.player.Player.onLogin(Player.java:1217)
        at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:48)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:93)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:222)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
****
```

**Additional context**

* I installed RSA patch (otherwise encounter 4214 bug)
* Use Fiddler to redirect traffic
* Windows Firewall already allow TCP and UDP for certain ports
* System: Win 10

Thank you!

**Comment by NotThorny** [comment]
Looks like you're trying to use resources with bad quest data, updating resources should fix it.

**Comment by pengzhenghao** [comment]
Work by replacing resources files with these:  https://gitlab.com/YuukiPS/GC-Resources/-/tree/3.4/

I will keep these issue open for those who are running latest grasscutter with 3.4 client.

We should update README / wiki to better provide reference to new user.
