### ISSUE TITLE
[Bug] ESC商城无效

### ISSUE THREAD

**Issue by Kimaru-bili** [Melledy/Grasscutter#2093]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

游戏中ESC商店无法使用 
**Which branch did you use?**

Grasscutter version: 1.4.7
**Screenshots**

**Additional context**

打开商店后服务端的报错
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.common.ItemParamData.getId()" because the return value of "emu.grasscutter.game.shop.ShopInfo.getGoodsItem()" is null
        at emu.grasscutter.server.packet.send.PacketGetShopRsp.<init>(PacketGetShopRsp.java:37)
        at emu.grasscutter.server.packet.recv.HandlerGetShopReq.handle(HandlerGetShopReq.java:16)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:93)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:222)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
![image](https://user-images.githubusercontent.com/40233772/229283893-f77b2c68-8ae5-4848-a63c-76336d5d80df.png)

**Comment by ppssvv** [comment]
delete data
