### ISSUE TITLE
erver again, I get an error

### ISSUE THREAD

**Issue by EdwinXinMa** [Melledy/Grasscutter#217]
When I start the server again, I get an error, and mongoDB starts successfully.
[13:10:42] [[34mINFO[0;39m] Opened connection [connectionId{localValue:3, serverValue:5}] to localhost:27017
[13:10:43] [[31mWARN[0;39m] [Dispatch] No SSL cert found! Falling back to HTTP server.
Exception in thread "main" java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Net.java:433)
        at sun.nio.ch.Net.bind(Net.java:425)
        at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
        at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
        at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:100)
        at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
        at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
        at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)
        at emu.grasscutter.server.dispatch.DispatchServer.start(DispatchServer.java:182)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:78)

**Comment by Tomiaocat** [comment]
don't worry

https://github.com/Grasscutters/Grasscutter/wiki/Troubleshooting#address-already-in-use-bind

**Comment by F-Unction** [comment]
Try build stable branch.
There might be some problems in the release jar.

**Comment by KingRainbow44** [comment]
this isnt a support forum, this is an issue tracker. check the discord if you need help.
