### ISSUE TITLE
[Bug] Group 133103009 suite 1 not found

### ISSUE THREAD

**Issue by FlameMaster** [Melledy/Grasscutter#2217]
<WARN:SceneScriptManager> Group 133103009 suite 1 not found
<WARN:SceneScriptManager> Group 133315201 suite 1 not found
<ERROR:SceneScriptManager> [LUA] call trigger failed in group 133104621 with action_EVENT_GROUP_LOAD_621053,emu.grasscutter.scripts.data.ScriptArgs@3d204123
org.luaj.vm2.LuaError: script:706 attempt to index ? (a nil value)
        at org.luaj.vm2.LuaValue.error(Unknown Source)
        at org.luaj.vm2.LuaValue.indexerror(Unknown Source)
        at org.luaj.vm2.LuaValue.gettable(Unknown Source)
        at org.luaj.vm2.LuaValue.get(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.call(Unknown Source)
        at emu.grasscutter.scripts.SceneScriptManager.safetyCall(SceneScriptManager.java:939)
        at emu.grasscutter.scripts.SceneScriptManager.callScriptFunc(SceneScriptManager.java:932)
        at emu.grasscutter.scripts.SceneScriptManager.callTrigger(SceneScriptManager.java:877)
        at emu.grasscutter.scripts.SceneScriptManager.handleEventForTrigger(SceneScriptManager.java:846)
        at emu.grasscutter.scripts.SceneScriptManager.realCallEvent(SceneScriptManager.java:826)
        at emu.grasscutter.scripts.SceneScriptManager.lambda$callEvent$25(SceneScriptManager.java:799)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by scooterboo** [comment]
Group 133103009 and 133315201 have suite_disk instead of normal suites.
