### ISSUE TITLE
[Bug] Help Command not working

### ISSUE THREAD

**Issue by TropicLegend** [Melledy/Grasscutter#2242]
Using Grasscutter [Version 1.6.1](https://github.com/Grasscutters/Grasscutter/releases/tag/v1.6.1)
What did I do? 
I executed /help as a player on the server
What did I expect the server to do?
Show me all commands and stuff
What actually happened?
I didn't get an answer by the server and got an error code in the grasscutter console.
`java.lang.NullPointerException: Cannot invoke "String.startsWith(String)" because "p" is null
        at emu.grasscutter.game.Account.hasPermission(Account.java:206)
        at emu.grasscutter.command.commands.HelpCommand.lambda$execute$0(HelpCommand.java:65)
        at java.base/java.util.TreeMap.forEach(TreeMap.java:1282)
        at emu.grasscutter.command.commands.HelpCommand.execute(HelpCommand.java:62)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:323)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:327)
        at emu.grasscutter.game.chat.ChatSystem.tryInvokeCommand(ChatSystem.java:44)
        at emu.grasscutter.game.chat.ChatSystem.sendPrivateMessage(ChatSystem.java:165)
        at emu.grasscutter.server.packet.recv.HandlerPrivateChatReq.handle(HandlerPrivateChatReq.java:21)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:91)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:215)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)`

**Comment by KingRainbow44** [comment]
can you try v1.6.2?

**Comment by root-mega** [comment]
is this solved
