### ISSUE TITLE
[Bug] 为什么我会出现这样的情况，大佬帮我看一下

### ISSUE THREAD

**Issue by Aharker1** [Melledy/Grasscutter#2294]
![image](https://github.com/Grasscutters/Grasscutter/assets/135404494/1e1d5de9-6b88-4635-bacb-62235bf54e2a)
为什么我会出现这样的情况，有没有人帮我解决一下

Starting local Grasscutter server...
16:20:04 <INFO:Grasscutter> 正在启动 Grasscutter...
16:20:04 <INFO:Grasscutter> 游戏版本：3.5.0
16:20:04 <INFO:Grasscutter> Grasscutter 版本：1.4.7-faf686b8
16:20:04 <INFO:ResourceLoader> 正在加载 resources...
16:20:08 <INFO:ResourceLoader> 完成加载 resources。
16:20:08 <INFO:Language> Loading cached 'TextMaps'...
16:20:08 <INFO:Language> Loading cached 'TextMaps'...
Exception in thread "main" java.lang.NullPointerException: Cannot read field "strings" because "textstrings[j]" is null
        at emu.grasscutter.tools.Tools$1.newTranslatedLine(Tools.java:80)
        at emu.grasscutter.tools.Tools$1.newTranslatedLine(Tools.java:85)
        at emu.grasscutter.tools.Tools.lambda$createGmHandbooks$4(Tools.java:108)
        at it.unimi.dsi.fastutil.ints.Int2ObjectMap.lambda$forEach$0(Int2ObjectMap.java:249)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at it.unimi.dsi.fastutil.ints.Int2ObjectMap.forEach(Int2ObjectMap.java:253)
        at emu.grasscutter.tools.Tools.createGmHandbooks(Tools.java:108)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:115)
C:\Users\QIN\Desktop\GC>

**Comment by Catta1997** [comment]
Try to use Eng language

**Comment by NDECenziken** [comment]
你要不要试试看更新一下grasscutter.jar。现在是3.7的游戏版本，gc1.6.3，可以任务

**Comment by Aharker1** [comment]
解决了，把GC的版本换成了1.5.1，就不会报错了

**Comment by KingRainbow44** [comment]
delete your textmap cache
