### ISSUE TITLE
[Bug] When i open the ESC shop,server report an error.（无法开启ESC商店） Grasscutter 1.7.1

### ISSUE THREAD

**Issue by Aiikisaraki** [Melledy/Grasscutter#2370]
The ESC shop can't open and report that:
```
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.common.ItemParamData.getId()" because the return value of "emu.grasscutter.game.shop.ShopInfo.getGoodsItem()" is null
        at emu.grasscutter.server.packet.send.PacketGetShopRsp.<init>(PacketGetShopRsp.java:35)
        at emu.grasscutter.server.packet.recv.HandlerGetShopReq.handle(HandlerGetShopReq.java:14)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:82)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:214)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
Grasscutter 1.7.1
I read the [issue#2093](https://github.com/Grasscutters/Grasscutter/issues/2093), but don't know how to repair.

![Snipaste_2023-09-16_19-46-40](https://github.com/Grasscutters/Grasscutter/assets/41433508/665ed18e-e367-4332-909f-c9f95fc5b533)

**Comment by Aiikisaraki** [comment]
And my client version is 4.0.0

**Comment by r78ik7** [comment]
Bro, how did you solve this problem? I copied ShopGoodsExcelConfigData under Resources and made the store in a strange state with a list price of 99 Mora but a normal selling price (it needs to be reloaded once in the game, which is a mechanical translation). Now, no matter what file value I change, I cannot change the reloaded price. The shop.json modified by Grasscutter's store is invalid, or it is another ShopGoodsExcelConfigData. I want to know how you solved it
