### ISSUE TITLE
How to make grasscutter run in the background?

### ISSUE THREAD

**Issue by Dituon** [Melledy/Grasscutter#238]
I tried to background the server with nohup, but I got some errors...

My Command: `nohup java -jar grasscutter.jar &`

`[[1;31mERROR[0;39m] An error occurred.
java.io.IOException: Bad file descriptor
    at java.base/java.io.FileInputStream.readBytes(Native Method)
    at java.base/java.io.FileInputStream.read(FileInputStream.java:276)
    at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:282)
    at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
    at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:270)
    at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:313)
    at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
    at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
    at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
    at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
    at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
    at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:123)
    at emu.grasscutter.Grasscutter.main(Grasscutter.java:98)`

in CentOS 8.0,  When running in the foreground everything works fine

**Comment by Mar0xy** [comment]
1. install tmux or screen
2. run tmux or screen depending on which you installed
3. cd into folder(if in a folder) and execute the jar file

you can then quit out of the ssh session and reconnect to ssh and it would be in the background and you can always reconnect to the session by using the appropriate commands

**Comment by KingRainbow44** [comment]
this isnt a support forum, this is an issue tracker. check the discord if you need help.
