### ISSUE TITLE
[Bug] 服务器搭建起来后，pc使用fiddler和mitm均在启动界面400和502

### ISSUE THREAD

**Issue by Eacgh** [Melledy/Grasscutter#2390]
<img width="1280" alt="屏幕截图 2023-09-26 190726" src="https://github.com/Grasscutters/Grasscutter/assets/77911418/8aaa21fe-2af2-4082-9175-adf4cc5e6fe5">

**Comment by Tarot-s** [comment]
on servers within china, with the firewall turned off, the server refused to connect to the host, resulting in 404 and 502 incidents

**Comment by awaae001** [comment]
检查服务器连接，检查代理软件配置

**Comment by uuzp** [comment]
你得先启动服务端，也就是【启动】旁边的那个小按钮

**Comment by 2233kkk** [comment]
me too

**Comment by 156209258y** [comment]
400访问不到   还有就是  证书mitm.it 这个网页访问不到

**Comment by staure** [comment]
错误原因：当提示错误400时，是因为在config.json配置文件中设置了 `useEncryption:true`和 `useInRouting:true` 开启了TLS加密，但由于没有配置证书、配置了证书但是没有正确导入到Windows的证书管理器中，或者证书创建时没有设置服务器IP等原因，导致原神客户端拒绝与服务器通信。
Cause of error: When error 400 is prompted, it is because `useEncryption:true` and `useInRouting:true` are set in the config.json configuration file to enable TLS encryption, but the Genshin Impact client refuses to communicate with the server because no certificate is configured, the certificate is configured but not correctly imported into the Windows certificate manager, or the server IP is not set when the certificate is created.

而当提示错误502时，是因为在 config.json 配置文件中设置了 `useEncryption:false` 和 `useInRouting:false` 关闭了TLS加密，但原神客户端又强制使用HTTPS协议。当然导致 502 错误的原因可能不止这一种原因
When error 502 is prompted, it is because `useEncryption:false` and `useInRouting:false` are set in the config.json configuration file to disable TLS encryption, but the Genshin Impact client forces the use of the HTTPS protocol. Of course, there may be more than one reason for the 502 error.

这是在Fiddler中双击左侧列表中任意一个400错误的数据包后，右侧窗口提示的详细错误信息：
This is the detailed error information displayed in the right window after double-clicking any 400 error packet in the left list in Fiddler:

HTTP ERROR 400 Invalid SNI

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 400 Invalid SNI</title>
</head>
<body><h2>HTTP ERROR 400 Invalid SNI</h2>
<table>
<tr><th>URI:</th><td>/hk4e_cn/mdk/shield/api/loadConfig</td></tr>
<tr><th>STATUS:</th><td>400</td></tr>
<tr><th>MESSAGE:</th><td>Invalid SNI</td></tr>
<tr><th>SERVLET:</th><td>-</td></tr>
<tr><th>CAUSED BY:</th><td>org.eclipse.jetty.http.BadMessageException: 400: Invalid SNI</td></tr>
</table>
<h3>Caused by:</h3><pre>org.eclipse.jetty.http.BadMessageException: 400: Invalid SNI
	at org.eclipse.jetty.server.SecureRequestCustomizer.customize(SecureRequestCustomizer.java:267)
	at org.eclipse.jetty.server.SecureRequestCustomizer.customize(SecureRequestCustomizer.java:208)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:501)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:558)
	at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:379)
	at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:146)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.tryProduce(AdaptiveExecutionStrategy.java:272)
	at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.lambda$new$0(AdaptiveExecutionStrategy.java:140)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:411)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:969)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1194)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1149)
	at java.base/java.lang.Thread.run(Thread.java:840)
</pre>
<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 11.0.15</a><hr/>

</body>
</html>

这是在Fiddler中双击左侧列表中任意一个502错误的数据包后，右侧窗口提示的详细错误信息：
This is the detailed error information displayed in the right window after double-clicking any 502 error packet in the left list in Fiddler:

[Fiddler] The connection to '192.168.66.130' failed.  <br />System.Security.SecurityException Failed to negotiate HTTPS connection with server.fiddler.network.https&gt; HTTPS handshake to 192.168.66.130 failed. System.IO.IOException 由于意外的数据包格式，握手失败。

临时解决方法：
Temporary workaround:

如果是用windows10 或者Centos、Ubuntu、Debian等搭建的本地服务器，并且只需要你自己一个人玩，则只需要修改Fiddler 抓包、重定向设置，将原神客户端的加密HTTPS请求，转换为普通的HTTP请求，跳过客户端与服务端之间的TLS加密协商、证书验证等即可解决。
If the local server is built with Windows 10 or Centos, Ubuntu, Debian, etc., and you only need to play by yourself, you only need to modify the Fiddler packet capture and redirection settings, convert the encrypted HTTPS request of the Genshin Impact client into a normal HTTP request, and skip the TLS encryption negotiation and certificate verification between the client and the server.

同时还需要在 `config.json` 配置文件中设置  `useEncryption:false` 和 `useInRouting:false` 为 `false` 禁用TLS加密。
You also need to set `useEncryption:false` and `useInRouting:false` to `false` in the `config.json` configuration file to disable TLS encryption.

以下是修改后的Fiddler抓包、重定向设置
The following are the modified Fiddler packet capture and redirection settings
```js
import Fiddler;

class Handlers {

    // 如果无法解决客户端、服务端之间的自签名证书问题，可以使用此方法暂时解决
    // 此方法会将客户端发起的HTTPS请求在特定条件下强制转换为HTTP请求
    // 此方法仅适用于本地局域网，公网环境下则必须使用HTTPS来确保客户端、服务端之间的安全
    
    // 在客户端请求发送之前进行处理
    static function OnBeforeRequest(oSession: Session) {
    
        // 检查客户端请求的主机名是否匹配指定的域名
        if (oSession.host.EndsWith(".yuanshen.com") || 
            oSession.host.EndsWith(".hoyoverse.com") || 
            oSession.host.EndsWith(".mihoyo.com") || 
            oSession.host.EndsWith(".starrails.com") || 
            (oSession.uriContains("/log") && (
                oSession.host.StartsWith("uspider.yuanshen.com") || 
                oSession.host.StartsWith("overseauspider.yuanshen.com")
        ))) {
        
            // 如果URL是HTTPS的，则将其改为HTTP
            if (oSession.isHTTPS) {
                oSession.fullUrl = oSession.fullUrl.Replace("https://", "http://");
            }
            
            // 将客户端的请求，重定向到此IP地址
            // 此IP地址就是我们的服务器地址，当然IP地址也可以改为域名
            oSession.fullUrl = oSession.fullUrl.Replace(oSession.host, "192.168.66.130:80");
        }
    }
}
```

请将IP地址和端口 192.168.66.130:80 替换为你的服务器IP和端口即可，例如替换为 127.0.0.1:443 或者 127.0.0.1:80
Please replace the IP address and port 192.168.66.130:80 with your server IP and port, for example, replace it with 127.0.0.1:443 or 127.0.0.1:80


以上可能会帮助你解决400和502报错
The above may help you solve 400 and 502 errors
