### ISSUE TITLE
[Bug] Can not open ESC shop

### ISSUE THREAD

**Issue by hellcworld** [Melledy/Grasscutter#2437]
**Did you look for other closed issues that have the same problem?**

already read.
**Describe the bug**

can not open ESC shop normally.It is empty inside.
**Which branch did you use?**

 
 Game version: 4.0.0
Grasscutter version: 1.7.3-13c40b53a

**Screenshots**

23:28:05 <ERROR:SceneScriptManager> [LUA] call trigger failed in group 133307096 with condition_EVENT_GROUP_LOAD_96008,ScriptArgs(param1=133307096, param2=0, param3=0, source_eid=0, target_eid=0, group_id=133307096, source=null, type=29)
org.luaj.vm2.LuaError: script:144 attempt to call nil
stack traceback:
        script:144: in function 'CheckIsInGroup'
        script:144: in function <script:142>
        [Java]: in ?
        at org.luaj.vm2.LuaValue.checkmetatag(Unknown Source)
        at org.luaj.vm2.LuaValue.callmt(Unknown Source)
        at org.luaj.vm2.LuaValue.call(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.call(Unknown Source)
        at emu.grasscutter.scripts.SceneScriptManager.safetyCall(SceneScriptManager.java:1004)
        at emu.grasscutter.scripts.SceneScriptManager.callScriptFunc(SceneScriptManager.java:997)
        at emu.grasscutter.scripts.SceneScriptManager.evaluateTriggerCondition(SceneScriptManager.java:933)
        at emu.grasscutter.scripts.SceneScriptManager.handleEventForTrigger(SceneScriptManager.java:905)
        at emu.grasscutter.scripts.SceneScriptManager.realCallEvent(SceneScriptManager.java:886)
        at emu.grasscutter.scripts.SceneScriptManager.lambda$callEvent$28(SceneScriptManager.java:857)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:842)
**Additional context**

![image](https://github.com/Grasscutters/Grasscutter/assets/24631863/531e20d7-fd82-4d1f-b785-d301dc54385d)

**Comment by hellcworld** [comment]
I have not changed any JSON settings.

**Comment by NotThorny** [comment]
Run the command `reload` in cmd or `/reload` in chat.
Then open the shop tab again.

**Comment by hellcworld** [comment]
> Run the command `reload` in cmd or `/reload` in chat. Then open the shop tab again.

Thanks,  will try it tonight.

**Comment by hellcworld** [comment]
Thanks,it works.  Need i run this command every time start server ?

**Comment by hellcworld** [comment]
Otherwise , the console print another error.

 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group166001287.lua
 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133402016.lua
 <ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group133316274.lua
<ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group155005321.lua
<ERROR:ScriptLoader> Could not find script at path Scene/3/scene3_group155005095.lua

**Comment by NotThorny** [comment]
Yes, and the LUA errors are due to the scene and won't cause problems with the shop. There's some other issue with the shop currently that is requiring it to be reloaded every time the server is restarted.
