### ISSUE TITLE
Plot cannot be played while running on the server[Bug] 

### ISSUE THREAD

**Issue by FlyingIceyyds** [Melledy/Grasscutter#2471]
In the same version, everything works fine when the local runtime is running, but the plot cannot be played when uploading to the server runtime, the local runtime generates json file in the cache folder, but not when the server runs, error log:

2024-01-20T16:48:59Z <ERROR:emu.grasscutter.scripts.SceneScriptManager> [LUA] call trigger failed in group 133307094 with condition_EVENT_GROUP_LOAD_94006,ScriptArgs(param1=133307094, param2=0, param3=0, source_eid=0, target_eid=0, group_id=133307094, source=null, type=29)
org.luaj.vm2.LuaError: script:123 attempt to call nil
stack traceback:
	script:123: in function <script:121>
	[Java]: in ?
	at org.luaj.vm2.LuaValue.checkmetatag(Unknown Source)
	at org.luaj.vm2.LuaValue.callmt(Unknown Source)
	at org.luaj.vm2.LuaValue.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at emu.grasscutter.scripts.SceneScriptManager.safetyCall(SceneScriptManager.java:979)
	at emu.grasscutter.scripts.SceneScriptManager.callScriptFunc(SceneScriptManager.java:972)
	at emu.grasscutter.scripts.SceneScriptManager.evaluateTriggerCondition(SceneScriptManager.java:913)
	at emu.grasscutter.scripts.SceneScriptManager.handleEventForTrigger(SceneScriptManager.java:885)
	at emu.grasscutter.scripts.SceneScriptManager.realCallEvent(SceneScriptManager.java:866)
	at emu.grasscutter.scripts.SceneScriptManager.lambda$callEvent$27(SceneScriptManager.java:837)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:842)
2024-01-20T16:48:59Z <ERROR:emu.grasscutter.scripts.SceneScriptManager> [LUA] call trigger failed in group 133307096 with condition_EVENT_GROUP_LOAD_96008,ScriptArgs(param1=133307096, param2=0, param3=0, source_eid=0, target_eid=0, group_id=133307096, source=null, type=29)
org.luaj.vm2.LuaError: script:144 attempt to call nil
stack traceback:
	script:144: in function <script:142>
	[Java]: in ?
	at org.luaj.vm2.LuaValue.checkmetatag(Unknown Source)
	at org.luaj.vm2.LuaValue.callmt(Unknown Source)
	at org.luaj.vm2.LuaValue.call(Unknown Source)
	at org.luaj.vm2.LuaClosure.execute(Unknown Source)
	at org.luaj.vm2.LuaClosure.call(Unknown Source)
	at emu.grasscutter.scripts.SceneScriptManager.safetyCall(SceneScriptManager.java:979)
	at emu.grasscutter.scripts.SceneScriptManager.callScriptFunc(SceneScriptManager.java:972)
	at emu.grasscutter.scripts.SceneScriptManager.evaluateTriggerCondition(SceneScriptManager.java:913)
	at emu.grasscutter.scripts.SceneScriptManager.handleEventForTrigger(SceneScriptManager.java:885)
	at emu.grasscutter.scripts.SceneScriptManager.realCallEvent(SceneScriptManager.java:866)
	at emu.grasscutter.scripts.SceneScriptManager.lambda$callEvent$27(SceneScriptManager.java:837)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:842)
2024-01-20T16:51:26Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Could not find script at path Scene/3/scene3_group133316134.lua
2024-01-20T16:51:27Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Could not find script at path Scene/3/scene3_group133403003.lua
2024-01-20T16:51:27Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Could not find script at path Scene/3/scene3_group155005095.lua
2024-01-20T16:51:27Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Could not find script at path Scene/3/scene3_group166001112.lua
2024-01-20T16:51:28Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Could not find script at path Scene/3/scene3_group155005321.lua
2024-01-20T16:51:28Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Could not find script at path Scene/3/scene3_group133316274.lua
2024-01-20T16:51:28Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Could not find script at path Scene/3/scene3_group133402016.lua
2024-01-20T16:51:28Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Could not find script at path Scene/3/scene3_group133403186.lua
2024-01-20T16:51:28Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Could not find script at path Scene/3/scene3_group133403513.lua
2024-01-20T16:51:29Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Could not find script at path Scene/3/scene3_group166001287.lua
2024-01-20T16:51:29Z <ERROR:emu.grasscutter.scripts.ScriptLoader> Could not find script at path Scene/3/scene3_group133402002.lua

The files on the local and server are exactly the same, It's not clear to me if this is due to low server hardware configuration?

**Comment by FlyingIceyyds** [comment]
The problem was solved, everything worked fine after replacing Resources
