### ISSUE TITLE
[Bug] 网络响应超时，是否重新登录？

### ISSUE THREAD

**Issue by TangZhX-T** [Melledy/Grasscutter#2515]
游戏进门后一直白屏，然后让重新登录

![image](https://github.com/Grasscutters/Grasscutter/assets/126883220/8433cf8b-ca8e-452c-90df-c2213a2501f3)

服务端：
16:22:26 <DEBUG:EnergyManager> Energy drop data successfully loaded.
16:22:26 <DEBUG:EnergyManager> Skill particle generation data successfully loaded.
16:22:26 <DEBUG:CombineManger> Loaded 14 reliquary decompose entries.
16:22:26 <DEBUG:GameServerPacketHandler> Registered 239 PacketHandlers
16:22:26 <DEBUG:AnnouncementTask> [Task] Announcement task enabled.
16:22:26 <DEBUG:MoonCard> [Task] MoonCard task enabled.
16:22:26 <DEBUG:GachaSystem> Banners successfully loaded.
16:22:26 <DEBUG:ShopSystem> Shop data successfully loaded.
16:22:26 <DEBUG:ShopSystem> Loaded 26 ShopChest entries.
16:22:26 <DEBUG:DropSystemLegacy> Drop data successfully loaded.
16:22:26 <DEBUG:ExpeditionSystem> Expedition reward successfully loaded.
16:22:27 <DEBUG:Language> Cache modified 1717229162639, textmap modified 1713823116000
16:22:27 <DEBUG:Language> Loading cached 'TextMaps'...
16:22:28 <WARN:FileUtils> Failed to read resource: /html/handbook.html
16:22:28 <DEBUG:FileUtils> Failed to load resource: /html/handbook.html
java.lang.NullPointerException: Cannot invoke "java.io.InputStream.readAllBytes()" because "is" is null
        at emu.grasscutter.utils.FileUtils.readResource(FileUtils.java:203)
        at emu.grasscutter.server.http.documentation.HandbookHandler.<init>(HandbookHandler.java:28)
        at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:67)
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:484)
        at emu.grasscutter.server.http.HttpServer.addRouter(HttpServer.java:145)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:141)
16:22:28 <DEBUG:Grasscutter> Set day of week to 7
16:22:28 <INFO:ResourceLoader> 正在加载 resources...
16:22:28 <DEBUG:ResourceLoader> Loaded 0 emu.grasscutter.data.binout.config.ConfigEntityAvatar entries.
16:22:29 <DEBUG:ResourceLoader> Loaded 509 emu.grasscutter.data.binout.config.ConfigEntityMonster entries.
16:22:29 <DEBUG:ResourceLoader> Loaded 509 emu.grasscutter.data.binout.config.ConfigEntityGadget entries.
16:22:31 <DEBUG:ResourceLoader> Priorities are [HIGHEST, HIGH, NORMAL, LOW, LOWEST]
16:22:33 <DEBUG:ResourceLoader> Loading resources took 2181487400ns == 2181ms
16:22:35 <DEBUG:ResourceLoader> Loaded 0 quest keys.
16:22:35 <DEBUG:ResourceLoader> Loaded 2521 MainQuestDatas.
16:22:35 <DEBUG:ResourceLoader> Loaded 1 ScriptSceneDatas.
16:22:36 <DEBUG:ResourceLoader> Loaded 11 HomeworldDefaultSaveDatas.
16:22:36 <DEBUG:ResourceLoader> Loaded 33 SceneNpcBornDatas.
16:22:37 <DEBUG:ResourceLoader> Loaded 33 SceneRouteDatas.
16:22:37 <DEBUG:ResourceLoader> Loaded BlossomConfig.
16:22:37 <DEBUG:ActivityManager> Enable 1 activities.
16:22:40 <DEBUG:ResourceLoader> Loaded 2119 gadget mappings.
16:22:40 <DEBUG:ResourceLoader> Loaded 60 subfield mappings.
16:22:40 <DEBUG:ResourceLoader> Loaded 38 drop subfield mappings.
16:22:40 <DEBUG:ResourceLoader> Loaded 13823 drop table configs.
16:22:40 <DEBUG:ResourceLoader> Loaded 773 monster mappings.
16:22:40 <DEBUG:ResourceLoader> Loaded 75 ActivityCondGroups.
16:22:40 <DEBUG:ResourceLoader> Loaded 932 group replacements.
16:22:40 <DEBUG:ResourceLoader> Loaded trial activity custom data.
16:22:40 <DEBUG:ResourceLoader> Loaded trial activity schedule custom data.
16:22:40 <DEBUG:ResourceLoader> Loaded trial avatar custom data.
16:22:40 <DEBUG:EntityControllerScriptManager> Loaded 117 gadget controllers
16:22:40 <INFO:ResourceLoader> 完成加载 resources
16:22:41 <INFO:HttpServer> [Dispatch] Dispatch 服务器启动于 127.0.0.1:443
16:22:41 <INFO:GameServer> Grasscutter 是免费开源软件，遵循 AGPL-3.0 license。
        如果你是付费购买的，那你已经被骗了。
        项目地址：https://github.com/Grasscutters/Grasscutter
16:22:41 <INFO:GameServer> 游戏服务器启动于 127.0.0.1:22102
16:22:41 <INFO:Grasscutter> 加载完成！输入 "help" 查看命令列表
**16:23:15 <INFO:RegionHandler> [Dispatch] Client 127.0.0.1 request: query_region_list
16:23:16 <INFO:DefaultAuthenticators$TokenAuthenticator> [Dispatch] 客户端 127.0.0.1 正在尝试通过 token 登录
16:23:16 <INFO:DefaultAuthenticators$TokenAuthenticator> [Dispatch] 客户端 127.0.0.1 已通过 token 登录，UID 为 10001
16:23:16 <DEBUG:AuthenticationHandler> [Dispatch] 客户端 127.0.0.1 正在尝试登录
16:23:16 <INFO:DefaultAuthenticators$SessionKeyAuthenticator> [Dispatch] 客户端 127.0.0.1 成功交换 token
16:23:16 <DEBUG:AuthenticationHandler> [Dispatch] 客户端 127.0.0.1 正在尝试登录
16:23:16 <INFO:RegionHandler> Client 127.0.0.1 request: query_cur_region/os_usa
16:23:29 <INFO:GameSession> 客户端 /127.0.0.1:52954 已连接
16:23:33 <DEBUG:SceneMeta> Successfully loaded metadata in scene 3.
16:23:33 <DEBUG:ExecRegisterDynamicGroup> Registering group 133307094
16:23:33 <DEBUG:ExecRegisterDynamicGroup> Registering group 133307096
16:23:33 <DEBUG:QuestManager> >>> Quest 46904 will be not accepted as a result of event trigger QUEST_COND_STATE_EQUAL (, 35104, 2, 0, 0, 0).
16:23:33 <DEBUG:ExecRegisterDynamicGroup> Registering group 133301172
16:23:33 <DEBUG:QuestManager> ^ Condition QUEST_COND_STATE_EQUAL has params 35104, 3 with result failure.
16:23:33 <DEBUG:QuestManager> ^ Condition QUEST_COND_STATE_NOT_EQUAL has params 31101, 3 with result failure.
16:23:33 <DEBUG:ExecRegisterDynamicGroup> Registering group 133301171
16:23:33 <DEBUG:ExecRegisterDynamicGroup> Registering group 133301168
16:23:33 <DEBUG:ExecRegisterDynamicGroup> Registering group 133301170
16:23:33 <DEBUG:ExecRegisterDynamicGroup> Registering group 133301166
16:23:33 <DEBUG:ExecRegisterDynamicGroup> Registering group 133301169
16:23:33 <DEBUG:ExecRegisterDynamicGroup> Registering group 133303657
16:23:33 <DEBUG:ExecRegisterDynamicGroup> Registering group 133301167
16:23:35 <DEBUG:SceneScriptManager> Tried to refresh group suite 2 in an unloaded and uncached group 133113002 in scene 3.
16:23:35 <DEBUG:SceneScriptManager> Refreshing group 133113002 suite 2
16:23:55 <INFO:GameSession> 客户端 /127.0.0.1:63469 已连接
16:24:11 <INFO:GameSession> 客户端 /127.0.0.1:63479 已连接
16:24:22 <INFO:GameSession> 客户端 /127.0.0.1:52954 已断开连接
16:24:42 <INFO:GameSession> 客户端 /127.0.0.1:58164 已连接
16:25:01 <INFO:GameSession> 客户端 /127.0.0.1:63479 已断开连接
16:25:12 <INFO:GameSession> 客户端 /127.0.0.1:63943 已连接
16:25:23 <INFO:DefaultAuthenticators$TokenAuthenticator> [Dispatch] 客户端 127.0.0.1 正在尝试通过 token 登录
16:25:23 <INFO:DefaultAuthenticators$TokenAuthenticator> [Dispatch] 客户端 127.0.0.1 已通过 token 登录，UID 为 10001
16:25:23 <DEBUG:AuthenticationHandler> [Dispatch] 客户端 127.0.0.1 正在尝试登录
16:25:23 <INFO:DefaultAuthenticators$SessionKeyAuthenticator> [Dispatch] 客户端 127.0.0.1 成功交换 token
16:25:23 <DEBUG:AuthenticationHandler> [Dispatch] 客户端 127.0.0.1 正在尝试登录
16:25:23 <INFO:RegionHandler> Client 127.0.0.1 request: query_cur_region/os_usa**

**Comment by HongchengQ** [comment]
先检查一下cache目录下有没有scene的cache 如果没有 你需要重新启动服务端和游戏 当游戏再次出现超时时先不要操作 直到服务端打印出一条cache已保存的消息时再关闭游戏和服务端 再次启动应该就可以正常游玩了

如果有场景的缓存 那就多尝试几次重启游戏和服务端

现在的gc就是这样 连进不去游戏都是正常现象 而且在性能占用上也非常离谱

**Comment by HongchengQ** [comment]
或者也可以尝试增加超时时间

参考这里
https://github.com/HongchengQ/SO-GC/commit/902e0bd90790b8da8b435e67ca90d6bc138916ca#diff-c542c12cc8b39df5e25920a2a9c5849f524de02c0b366f630016602a44f86c5eR139

**Comment by ZJY648** [comment]
You are my father, you are torturing me to death, father!!!
