### ISSUE TITLE
进游戏后到指定时间后就退出游戏报错The client component is running abnormally, please restart the client. Error Code:(0,11008,2195210578)

### ISSUE THREAD

**Issue by myikun** [Melledy/Grasscutter#2520]
我玩这个·的时候玩到一会大概就进个游戏走几步就报错The client component is running abnormally, please restart the
client.
Error Code:(0,11008,2195210578)

![927C8827E55560F82AEFC4E67961B7A8](https://github.com/Grasscutters/Grasscutter/assets/119678132/80129261-b462-4fc3-98a2-dd224bad36e2)
大概就是这个样子，重新下载游戏和服务端都是有这种问题，咋解决的这种问题
这个是我服务端里面的报错：
19:34:02 <INFO:GameSession> 客户端 /127.0.0.1:56223 已连接
19:34:09 <WARN:QuestManager> Questing is disabled without scripts enabled.
> java.lang.NullPointerException: Cannot invoke "emu.grasscutter.server.http.dispatch.RegionHandler$RegionData.getRegionQuery()" because the return value of "java.util.Map.get(Object)" is null
        at emu.grasscutter.server.http.dispatch.RegionHandler.getCurrentRegion(RegionHandler.java:371)
        at emu.grasscutter.server.packet.send.PacketPlayerLoginRsp.<init>(PacketPlayerLoginRsp.java:51)
        at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:75)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:82)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:234)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
19:34:40 <INFO:GameSession> 客户端 /127.0.0.1:56223 已断开连接
报错之后就是直接退出游戏，我使用的代理工具是gctools1.15.1的一个版本
游戏版本是4.7这个包别人玩着都是正常的，就我玩4.7就不对，以前也是这种报错，不知道是我电脑问题还是怎么了

**Comment by myikun** [comment]
目前发现不需要version.dll这个文件就不会闪退，但是点击大门进去就是白屏，但是又加上这个文件的话就会闪退，有打开能修复一下这个文件吗

**Comment by myikun** [comment]
有方法

**Comment by SupernovaGo** [comment]
补丁被检测到了。你要把原来的那个补丁所在的文件夹里的原补丁和新出现的文件给删了（比如version.dll.一串数字这种以及报错的log文件），并重新复制一个补丁到该文件夹里。然后断网玩就行。注意在启动游戏前就要把代理给开启
