### ISSUE TITLE
[Bug] A null pointer error was encountered while trying to shut down the DISPATCH_ONLY server

### ISSUE THREAD

**Issue by Jimmy32767255** [Melledy/Grasscutter#2532]
## Logs:
2024-10-22T16:13:23Z <INFO:emu.grasscutter.command.CommandMap> Command used by server console: stop
2024-10-22T16:13:23Z <INFO:emu.grasscutter.command.CommandHandler> 正在关闭服务器...
2024-10-22T16:13:23Z <ERROR:emu.grasscutter.Grasscutter> 命令发生错误：
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.server.game.GameServer.getPlayers()" because the return value of "emu.grasscutter.Grasscutter.getGameServer()" is null
    at emu.grasscutter.command.commands.StopCommand.execute(StopCommand.java:20)
    at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:331)
    at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:335)
    at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:351)
    at emu.grasscutter.Grasscutter.main(Grasscutter.java:187)

## Screenshot:
![71abe9b0-20bc-4a04-ae11-d5673c7343e7](https://github.com/user-attachments/assets/d9fbc511-275b-4ac7-9d99-b196ba67e806)

**Comment by lsqmuyu** [comment]
自己修

**Comment by MLChinoo** [comment]
大神有能力提issue没能力提pr是吗😋

**Comment by Jimmy32767255** [comment]
Because there are related to the pull request is merged, this issue closed.
