### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by ryan1272024** [Melledy/Grasscutter#2538]
进入游戏（进门白屏），早上正常过了一会再进就白屏了，显示uid但是没有加载条
控制台：
 14:58:27 <INFO:RegionHandler> Client xxx.xxx.xxx.xxx request: query_cur_region/os_usa
14:58:37 <INFO:GameSession> 客户端 /127.0.0.1:52235 已连接
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.world.Scene.addPlayer(emu.grasscutter.game.player.Player)" because "scene" is null
        at emu.grasscutter.game.world.World.addPlayer(World.java:217)
        at emu.grasscutter.game.player.Player.onLogin(Player.java:1413)
        at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:71)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:82)
        at emu.grasscutter.server.game.GameSession.handleReceive(GameSession.java:234)
        at emu.grasscutter.server.game.GameSessionManager$1.lambda$handleReceive$0(GameSessionManager.java:72)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:842)

**Comment by 12shankar12ravi** [comment]
@ryan1272024  I have 8 years of experience working in java , spring boot and distributed systems . Shall i check this bug , if no once started working on this , please assign it to me and share more details about this bug.
