### ISSUE TITLE
Unable to make field private final byte[]

### ISSUE THREAD

**Issue by Lynricsy** [Melledy/Grasscutter#261]
**Describe the bug**
Unable to create an account.
Console error:
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module

**To Reproduce**
When I tried to create an account by using `account create 1 1` ,an error occured.

**Expected behavior**
An account created.

**Screenshots**
![L72VFT6(A6(N5F17`SBS5AM](https://user-images.githubusercontent.com/62173814/165302134-352adaa7-3024-4123-ade1-b4c21171009d.png)

**Desktop (please complete the following information):**
 - OS: Windows 22598.200
 - Version GitHub Action Build #89

**Additional context**
account create 1 1
[20:42:19] [ERROR] Console error:
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @765d7657
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
        at dev.morphia.mapping.MappedClass.discover(MappedClass.java:562)
        at dev.morphia.mapping.MappedClass.<init>(MappedClass.java:142)
        at dev.morphia.mapping.Mapper.getMappedClass(Mapper.java:529)
        at dev.morphia.internal.PathTarget.resolveField(PathTarget.java:169)
        at dev.morphia.internal.PathTarget.resolve(PathTarget.java:126)
        at dev.morphia.internal.PathTarget.getTarget(PathTarget.java:104)
        at dev.morphia.query.FieldCriteria.<init>(FieldCriteria.java:41)
        at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:338)
        at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:334)
        at dev.morphia.query.FieldEndImpl.equalIgnoreCase(FieldEndImpl.java:102)
        at dev.morphia.query.FieldEndImpl.equalIgnoreCase(FieldEndImpl.java:44)
        at emu.grasscutter.database.DatabaseHelper.getAccountByName(DatabaseHelper.java:80)
        at emu.grasscutter.database.DatabaseHelper.createAccountWithId(DatabaseHelper.java:28)
        at emu.grasscutter.commands.ServerCommands$Account.execute(ServerCommands.java:98)
        at emu.grasscutter.commands.ServerCommands.handle(ServerCommands.java:51)
        at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:115)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:71)

**Comment by Secretboy-SMR** [comment]
what's ur jdk version??

**Comment by KingRainbow44** [comment]
this is a case of using the wrong java version on the wrong build.
run `java -version` and ensure the version you are running matches the one specified in the readme
if that doesn't work, feel free to contact us in the support [discord](https://discord.gg/T5vZU6UyeG)

**Comment by BeatMercy** [comment]
> what's ur jdk version??

i reproduce this error by using jdk-17.0.2 😂
and build with the  stable branch( commit id 207eba1af534966a0221498d41e2717d3b2f7259)
![image](https://user-images.githubusercontent.com/24759084/166657114-2993683e-15b3-4f98-b722-8e8c34486f98.png)
