### ISSUE TITLE
Unable to start the server.

### ISSUE THREAD

**Issue by Lynricsy** [Melledy/Grasscutter#279]
**Describe the bug**

java.lang.NoClassDefFoundError: javax/naming/NamingException

**To Reproduce**
`java -jar .\grasscutter-1.0.0-dev.jar`

**Expected behavior**
Server started.

**Screenshots**
![image](https://user-images.githubusercontent.com/62173814/165424402-9617f218-a12e-4855-8e4b-9d2f74ef8e36.png)

**Desktop (please complete the following information):**
 - OS: Windows 22579
 - JRE 17.0.3
 - Version Github Action Build #277

**Additional context**
```
Failed to instantiate SLF4J LoggerFactory
Reported exception:
java.lang.NoClassDefFoundError: javax/naming/NamingException
        at ch.qos.logback.classic.joran.JoranConfigurator.addInstanceRules(JoranConfigurator.java:48)
        at ch.qos.logback.core.joran.GenericConfigurator.buildInterpreter(GenericConfigurator.java:134)
        at ch.qos.logback.core.joran.JoranConfiguratorBase.buildInterpreter(JoranConfiguratorBase.java:95)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:162)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:65)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:140)
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
        at emu.grasscutter.Grasscutter.<clinit>(Grasscutter.java:28)
Caused by: java.lang.ClassNotFoundException: javax.naming.NamingException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 17 more
Exception in thread "main" java.lang.NoClassDefFoundError: javax/naming/NamingException
        at ch.qos.logback.classic.joran.JoranConfigurator.addInstanceRules(JoranConfigurator.java:48)
        at ch.qos.logback.core.joran.GenericConfigurator.buildInterpreter(GenericConfigurator.java:134)
        at ch.qos.logback.core.joran.JoranConfiguratorBase.buildInterpreter(JoranConfiguratorBase.java:95)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:162)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
        at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
        at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:65)
        at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:140)
        at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
        at emu.grasscutter.Grasscutter.<clinit>(Grasscutter.java:28)
Caused by: java.lang.ClassNotFoundException: javax.naming.NamingException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 17 more
```

**Comment by yangjiahao0036** [comment]
Me too, but what I show is another problem after clicking start in game.
![image](https://user-images.githubusercontent.com/34952645/165435846-349df4dc-8490-494e-8fc9-14002a74fe94.png)

**Comment by Lynricsy** [comment]
> Me too, but what I show is another problem after clicking start in game. ![image](https://user-images.githubusercontent.com/34952645/165435846-349df4dc-8490-494e-8fc9-14002a74fe94.png)

I have the same problem.
And I can't enter the game now.
![image](https://user-images.githubusercontent.com/62173814/165438064-65a48043-499a-4125-9247-b1f8d6335c1c.png)

**Comment by Becods** [comment]
Works fine on [Build #127](https://github.com/Grasscutters/Grasscutter/actions/runs/2230859914).
Using Zulu17.

![image.png](https://dd-static.jd.com/ddimg/jfs/t1/129462/18/21270/70463/6268c8b3Eff980fb6/323939097a23a101.png)

**Comment by Hash070** [comment]
This problem is mainly caused by high version of jdk,please run this progroam with [JDK-8u202](https://mirrors.huaweicloud.com/java/jdk/8u202-b08/) environment which is recommended by README.MD
