### ISSUE TITLE
Cant login on latest dev branch.

### ISSUE THREAD

**Issue by Scirese** [Melledy/Grasscutter#280]
Stucks at loading screen.

java.lang.IllegalArgumentException: No enum constant emu.grasscutter.net.proto.MpSettingTypeOuterClass.MpSettingType.MpSettingEnterAfterApply
        at java.base/java.lang.Enum.valueOf(Enum.java:273)
        at dev.morphia.mapping.codec.EnumCodec.decode(EnumCodec.java:35)
        at dev.morphia.mapping.codec.EnumCodec.decode(EnumCodec.java:16)
        at org.bson.codecs.DecoderContext.decodeWithChildContext(DecoderContext.java:96)
        at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeModel(EntityDecoder.java:59)
        at dev.morphia.mapping.codec.pojo.EntityDecoder.decodeProperties(EntityDecoder.java:80)
        at dev.morphia.mapping.codec.pojo.LifecycleDecoder.decode(LifecycleDecoder.java:51)
        at dev.morphia.mapping.codec.pojo.MorphiaCodec.decode(MorphiaCodec.java:71)
        at com.mongodb.internal.operation.CommandResultArrayCodec.decode(CommandResultArrayCodec.java:52)
        at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:60)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
        at org.bson.internal.LazyCodec.decode(LazyCodec.java:48)
        at org.bson.codecs.BsonDocumentCodec.readValue(BsonDocumentCodec.java:104)
        at com.mongodb.internal.operation.CommandResultDocumentCodec.readValue(CommandResultDocumentCodec.java:63)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:87)
        at org.bson.codecs.BsonDocumentCodec.decode(BsonDocumentCodec.java:42)
        at com.mongodb.internal.connection.ReplyMessage.<init>(ReplyMessage.java:51)
        at com.mongodb.internal.connection.InternalStreamConnection.getCommandResult(InternalStreamConnection.java:476)
        at com.mongodb.internal.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:366)
        at com.mongodb.internal.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:279)
        at com.mongodb.internal.connection.UsageTrackingInternalConnection.sendAndReceive(UsageTrackingInternalConnection.java:100)
        at com.mongodb.internal.connection.DefaultConnectionPool$PooledConnection.sendAndReceive(DefaultConnectionPool.java:490)
        at com.mongodb.internal.connection.CommandProtocolImpl.execute(CommandProtocolImpl.java:71)
        at com.mongodb.internal.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:253)
        at com.mongodb.internal.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:202)
        at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:118)
        at com.mongodb.internal.connection.DefaultServerConnection.command(DefaultServerConnection.java:110)
        at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:345)
        at com.mongodb.internal.operation.CommandOperationHelper.executeCommand(CommandOperationHelper.java:336)
        at com.mongodb.internal.operation.CommandOperationHelper.executeCommandWithConnection(CommandOperationHelper.java:222)
        at com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:658)
        at com.mongodb.internal.operation.FindOperation$1.call(FindOperation.java:652)
        at com.mongodb.internal.operation.OperationHelper.withReadConnectionSource(OperationHelper.java:583)
        at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:652)
        at com.mongodb.internal.operation.FindOperation.execute(FindOperation.java:80)
        at com.mongodb.client.internal.MongoClientDelegate$DelegateOperationExecutor.execute(MongoClientDelegate.java:170)
        at com.mongodb.client.internal.MongoIterableImpl.execute(MongoIterableImpl.java:135)
        at com.mongodb.client.internal.MongoIterableImpl.iterator(MongoIterableImpl.java:92)
        at dev.morphia.query.MorphiaQuery.prepareCursor(MorphiaQuery.java:321)
        at dev.morphia.query.MorphiaQuery.iterator(MorphiaQuery.java:200)
        at dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:188)
        at dev.morphia.query.MorphiaQuery.first(MorphiaQuery.java:183)
        at emu.grasscutter.database.DatabaseHelper.checkPlayerExists(DatabaseHelper.java:102)
        at emu.grasscutter.server.packet.recv.HandlerGetPlayerTokenReq.handle(HandlerGetPlayerTokenReq.java:40)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:82)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:249)
        at emu.grasscutter.netty.MihoyoKcpChannel.channelRead(MihoyoKcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

It seems like some mongodb proto related code is wrong.

**Comment by Scirese** [comment]
duplicated #273
