### ISSUE TITLE
Stable version error.The dev version cannot create an account.

### ISSUE THREAD

**Issue by qingchunnh** [Melledy/Grasscutter#334]
my java version is
java version "17.0.3" 2022-04-19 LTS
Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.3+8-LTS-111, mixed mode, sharing)

my MongoDB version is
MongoDB 5.0.8 Community

Stable:
[9:39:47] [[1;31mERROR[0;39m] Relic properties are missing weights! Please check your ReliquaryMainPropExcelConfigData or ReliquaryAffixExcelConfigData files in your ExcelBinOutput folder.
[9:39:47] [[34mINFO[0;39m] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[9:39:47] [[34mINFO[0;39m] Opened connection [connectionId{localValue:1, serverValue:59}] to localhost:27017
[9:39:47] [[34mINFO[0;39m] Opened connection [connectionId{localValue:2, serverValue:60}] to localhost:27017
[9:39:47] [[34mINFO[0;39m] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=11533600}
[9:39:47] [[34mINFO[0;39m] Opened connection [connectionId{localValue:3, serverValue:61}] to localhost:27017
[9:39:48] [[34mINFO[0;39m] [Dispatch] Dispatch server started on port 443
[9:39:48] [[34mINFO[0;39m] Registered 86 PacketHandlers
[9:39:48] [[34mINFO[0;39m] Banners successfully loaded.
Exception in thread "main" org.reflections.ReflectionsException: Scanner TypeAnnotationsScanner was not configured
        at org.reflections.Store.get(Store.java:39)
        at org.reflections.Store.get(Store.java:61)
        at org.reflections.Store.get(Store.java:46)
        at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:429)
        at org.reflections.Reflections.getTypesAnnotatedWith(Reflections.java:416)
        at emu.grasscutter.command.CommandMap.scan(CommandMap.java:147)
        at emu.grasscutter.command.CommandMap.<init>(CommandMap.java:19)
        at emu.grasscutter.server.game.GameServer.<init>(GameServer.java:60)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:80)

dev:
[9:53:34] [[34mINFO[0;39m] Opened connection [connectionId{localValue:3, serverValue:64}] to localhost:27017
[9:53:34] [[34mINFO[0;39m] [Dispatch] Dispatch server started on port 443
[9:53:35] [[34mINFO[0;39m] Registered 86 PacketHandlers
[9:53:35] [[34mINFO[0;39m] Banners successfully loaded.
[9:53:35] [[34mINFO[0;39m] Game Server started on port 22102
account create admin
[9:53:47] [[1;31mERROR[0;39m] Command error:
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @2c383e33
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at dev.morphia.mapping.MappedClass.discover(MappedClass.java:562)
        at dev.morphia.mapping.MappedClass.<init>(MappedClass.java:142)
        at dev.morphia.mapping.Mapper.getMappedClass(Mapper.java:529)
        at dev.morphia.internal.PathTarget.resolveField(PathTarget.java:169)
        at dev.morphia.internal.PathTarget.resolve(PathTarget.java:126)
        at dev.morphia.internal.PathTarget.getTarget(PathTarget.java:104)
        at dev.morphia.query.FieldCriteria.<init>(FieldCriteria.java:41)
        at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:338)
        at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:334)
        at dev.morphia.query.FieldEndImpl.equalIgnoreCase(FieldEndImpl.java:102)
        at dev.morphia.query.FieldEndImpl.equalIgnoreCase(FieldEndImpl.java:44)
        at emu.grasscutter.database.DatabaseHelper.getAccountByName(DatabaseHelper.java:81)
        at emu.grasscutter.database.DatabaseHelper.createAccountWithId(DatabaseHelper.java:28)
        at emu.grasscutter.command.commands.AccountCommand.execute(AccountCommand.java:44)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:139)
        at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:128)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:98)

I've tried reinstalling java but the problem is not solved, I've wasted 5 hours, hope for help, thanks

**Comment by 33478196** [comment]
换jdk8

**Comment by soloopooo** [comment]
This is an _issue_ tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
GitHub issue **不是技术支持论坛**。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道。

**Comment by qingchunnh** [comment]
> 换jdk8

JDK8我有但是我用的是开发版 开发版是JDK17 稳定版我使用过JDK8 202 但是就是会报错

**Comment by qingchunnh** [comment]
> This is an _issue_ tracker, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support. GitHub issue **不是技术支持论坛**。需要技术支持请去 [Discord](https://discord.gg/T5vZU6UyeG)，里面有专门的中文频道。

我在discord问了3个小时没人知道没人回我

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
