### ISSUE TITLE
BindException: Address already in use: bind

### ISSUE THREAD

**Issue by Senlinke** [Melledy/Grasscutter#345]
When I run "start.bat",  error message is as follows, I don't konw which Address I have used.....

 Opened connection [connectionId{localValue:3, serverValue:9}] to localhost:27017
Exception in thread "main" java.net.BindException: Address already in use: bind
        at sun.nio.ch.Net.bind0(Native Method)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.Net.bind(Unknown Source)
        at sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
        at sun.nio.ch.ServerSocketAdaptor.bind(Unknown Source)
        at sun.net.httpserver.ServerImpl.<init>(Unknown Source)
        at sun.net.httpserver.HttpsServerImpl.<init>(Unknown Source)
        at sun.net.httpserver.DefaultHttpServerProvider.createHttpsServer(Unknown Source)
        at com.sun.net.httpserver.HttpsServer.create(Unknown Source)
        at emu.grasscutter.server.dispatch.DispatchServer.start(DispatchServer.java:166)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:78)

**Comment by kkh66** [comment]
go discord sometime will help you

**Comment by ClayCoffee** [comment]
@longzhijie102
port 443

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.

**Comment by Senlinke** [comment]
Thank you, I kill port 433, 'start.bat' works!By the way, How to get a relic with attributes?
&nbsp;


黄柯
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月29日(星期五) 下午2:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Grasscutters/Grasscutter] BindException: Address already in use: bind (Issue #345)





 
port 443
