### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ym2102** [Melledy/Grasscutter#479]
[17:30:03] [←[34mINFO←[0;39m] Starting Grasscutter...
[17:30:04] [←[34mINFO←[0;39m] Loaded 300 AvatarTalentDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 400 AvatarSkillDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 3794 FetterDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 73 AvatarSkillDepotDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 167 MonsterDescribeDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 1 AvatarCostumeDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 3032 NpcDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 66 ReliquaryMainPropDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 200 MonsterCurveDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 717 SceneDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 90 AvatarLevelDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 6889 ItemDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 336 AvatarPromoteDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 335 ReliquaryAffixDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 90 WeaponLevelDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 939 WeaponPromoteDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 9 AvatarFlycloakDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 6626 GadgetDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 100 AvatarCurveDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 42 ReliquarySetDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 100 WeaponCurveDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 744 EquipAffixDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 60 PlayerLevelDatas.
[17:30:04] [←[34mINFO←[0;39m] Loaded 101 ReliquaryLevelDatas.
[17:30:05] [←[34mINFO←[0;39m] Loaded 2420 ProudSkillDatas.
[17:30:05] [←[34mINFO←[0;39m] Loaded 568 MonsterDatas.
[17:30:05] [←[34mINFO←[0;39m] Loaded 78 AvatarDatas.
[17:30:05] [←[1;31mERROR←[0;39m] Relic properties are missing weights! Please check your ReliquaryMainPropExcelConfigData or ReliquaryAffixExcelConfigData files in your ExcelBinOutput folder.
[17:30:06] [←[34mINFO←[0;39m] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[17:30:06] [←[34mINFO←[0;39m] Opened connection [connectionId{localValue:1, serverValue:16}] to localhost:27017
[17:30:06] [←[34mINFO←[0;39m] Opened connection [connectionId{localValue:2, serverValue:17}] to localhost:27017
[17:30:06] [←[34mINFO←[0;39m] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=41424600}
[17:30:06] [←[34mINFO←[0;39m] Opened connection [connectionId{localValue:3, serverValue:18}] to localhost:27017
[17:30:07] [←[31mWARN←[0;39m] [Dispatch] No SSL cert found! Falling back to HTTP server.
Exception in thread "main" java.net.BindException: Address already in use: bind
        at java.base/sun.nio.ch.Net.bind0(Native Method)
        at java.base/sun.nio.ch.Net.bind(Net.java:555)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
        at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:89)
        at jdk.httpserver/sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:101)
        at jdk.httpserver/sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
        at jdk.httpserver/sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
        at jdk.httpserver/com.sun.net.httpserver.HttpServer.create(HttpServer.java:150)
        at emu.grasscutter.server.dispatch.DispatchServer.start(DispatchServer.java:182)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:78)

**Comment by channile** [comment]
端口被占用

**Comment by ym2102** [comment]
> 端口被占用

how do i fix it?

**Comment by channile** [comment]
Use netstat -ano to find the program which use port443,80,  and kill it.

**Comment by ym2102** [comment]
> Use netstat -ano to find the program which use port443,80, and kill it.

nothing seems to be using those, what else can i do?

**Comment by channile** [comment]
The [wiki](https://github.com/Grasscutters/Grasscutter/wiki/Troubleshooting) has a solutions for this error.
```
This error is derived from the server being unable to bind to a certain port. The server uses ports: 8888, 443, 80, and 22102 (by default)

Potential places for error:

The dispatch (web/HTTP[S]) server has double-bounded.
One of the above ports (or any you've specified) has been bound to by another process.
Solutions:

If an SSL certificate error is logged to the console, check your keystore.p12 is in the correct place and with the correct password.
Run netstat -aon | find /i "listening" to find processes with the server ports. Then kill the process with taskkill /PID <PID>.
```
You should follow and try again.

**Comment by ym2102** [comment]
> The [wiki](https://github.com/Grasscutters/Grasscutter/wiki/Troubleshooting) has a solutions for this error.
> 
> ```
> This error is derived from the server being unable to bind to a certain port. The server uses ports: 8888, 443, 80, and 22102 (by default)
> 
> Potential places for error:
> 
> The dispatch (web/HTTP[S]) server has double-bounded.
> One of the above ports (or any you've specified) has been bound to by another process.
> Solutions:
> 
> If an SSL certificate error is logged to the console, check your keystore.p12 is in the correct place and with the correct password.
> Run netstat -aon | find /i "listening" to find processes with the server ports. Then kill the process with taskkill /PID <PID>.
> ```
> 
> You should follow and try again.

You are a lifesaver <3 its probably because the keystore.p12 file <3

**Comment by KingRainbow44** [comment]
This is an _issue tracker_, not a support forum. Please visit the [Discord](https://discord.gg/T5vZU6UyeG) for further support.
