### ISSUE TITLE
Blocked by air wall and occurred an error in dungeon Forsaken Rift

### ISSUE THREAD

**Issue by Hhehepei** [Melledy/Grasscutter#483]
When I try to enter the Forsaken Rift and start the challenge I was blocked by a wall of air and the server reports an error
![屏幕截图 2022-05-03 225702](https://user-images.githubusercontent.com/104372677/166481731-25ff5170-21cf-4d9c-bc77-a83a0a549f34.jpg)
```
[22:56:42] [ERROR] An error occurred during game update.
java.lang.IllegalArgumentException: key can not be empty
        at java.scripting/javax.script.SimpleBindings.checkKey(SimpleBindings.java:215)
        at java.scripting/javax.script.SimpleBindings.get(SimpleBindings.java:158)
        at emu.grasscutter.scripts.SceneScriptManager.callEvent(SceneScriptManager.java:372)
        at emu.grasscutter.scripts.SceneScriptManager.checkRegions(SceneScriptManager.java:270)
        at emu.grasscutter.scripts.SceneScriptManager.onTick(SceneScriptManager.java:254)
        at emu.grasscutter.game.world.Scene.onTick(Scene.java:405)
        at emu.grasscutter.game.world.World.onTick(World.java:325)
        at emu.grasscutter.server.game.GameServer.onTick(GameServer.java:189)
        at emu.grasscutter.server.game.GameServer$1.run(GameServer.java:73)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)

```
A similar problem happened in Momiji-Dyed court I was blocked by the air wall but the server did not report an error
![屏幕截图 2022-05-03 231528](https://user-images.githubusercontent.com/104372677/166482373-8002cce0-e696-42c3-ab52-c9e3fcea365d.jpg)

**Comment by Hhehepei** [comment]
After today's update I am no longer blocked by walls of air. But when I get into the Forsaken Rift. The gadgets are not generated and the server reports an error
`
[17:35:59] [ERROR] An error occurred during game update.
java.lang.IllegalArgumentException: key can not be empty
        at java.scripting/javax.script.SimpleBindings.checkKey(SimpleBindings.java:215)
        at java.scripting/javax.script.SimpleBindings.get(SimpleBindings.java:158)
        at emu.grasscutter.scripts.SceneScriptManager.callEvent(SceneScriptManager.java:403)
        at emu.grasscutter.scripts.SceneScriptManager.checkRegions(SceneScriptManager.java:287)
        at emu.grasscutter.scripts.SceneScriptManager.onTick(SceneScriptManager.java:271)
        at emu.grasscutter.game.world.Scene.onTick(Scene.java:420)
        at emu.grasscutter.game.world.World.onTick(World.java:325)
        at emu.grasscutter.server.game.GameServer.onTick(GameServer.java:189)
        at emu.grasscutter.server.game.GameServer$1.run(GameServer.java:73)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)

`
