### ISSUE TITLE
New connection issue after upgrading kcp-netty

### ISSUE THREAD

**Issue by TheOrdinaryWow** [Melledy/Grasscutter#489]
> Conv inconsistency should now properly disconnect your client now.

It seems that the problem stills after commit `commit f4e8baf1874cd12b2c37c8f177105777455e406a`, check following log please:

```
[09:32:30] [INFO] Client connected from $IP_ADDRESS
[09:32:30] [INFO] Client disconnected from $IP_ADDRESS
io.jpower.kcp.netty.KcpException: State=-1 after update()
        at io.jpower.kcp.netty.UkcpServerChannel.run(UkcpServerChannel.java:395)
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
_$IP_ADDRESS reserved for privacy._

Now on the older version (before upgrading `kcp-netty`), the client would display attempting to reconnect server), instead now it’ll display “server disconnected”.

Original issue: #341

**Comment by TheOrdinaryWow** [comment]
Solved myself. MitM forgot to add domain names.

**Comment by TheOrdinaryWow** [comment]
Problem stills. My method was just a workaround.
