### ISSUE TITLE
Error creating player object

### ISSUE THREAD

**Issue by mcoo** [Melledy/Grasscutter#491]
When I input the name of role, it happend:
```
[11:15:14] [ERROR] Error creating player object:
java.lang.NullPointerException: null
        at emu.grasscutter.game.avatar.GenshinAvatar.<init>(GenshinAvatar.java:109)
        at emu.grasscutter.game.avatar.GenshinAvatar.<init>(GenshinAvatar.java:104)
        at emu.grasscutter.server.packet.recv.HandlerSetPlayerBornDataReq.handle(HandlerSetPlayerBornDataReq.java:50)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:81)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:234)
        at emu.grasscutter.netty.MihoyoKcpChannel.channelRead(MihoyoKcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
and then
```
java.lang.NullPointerException
        at emu.grasscutter.game.World.addPlayer(World.java:160)
        at emu.grasscutter.game.GenshinPlayer.onLogin(GenshinPlayer.java:743)
        at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:44)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:81)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:234)
        at emu.grasscutter.netty.MihoyoKcpChannel.channelRead(MihoyoKcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```
in dev version
```
[13:12:18] [ERROR] Error creating player object:
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.def.AvatarData.getId()" because "data" is null
        at emu.grasscutter.game.avatar.Avatar.<init>(Avatar.java:122)
        at emu.grasscutter.game.avatar.Avatar.<init>(Avatar.java:117)
        at emu.grasscutter.server.packet.recv.HandlerSetPlayerBornDataReq.handle(HandlerSetPlayerBornDataReq.java:57)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:85)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:242)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ghost** [comment]
You have a character with an invalid id, you will need to delete it in your database.

**Comment by ItsAlbertZhang** [comment]
I got the same error today.

After changing the grasscutter to development branch, and getting resources from https://github.com/Koko-boya/Grasscutter_Resources, it works ok.

**Comment by lunaticwhat** [comment]
the best way to solve this is start with a new account / database if you can't find what's wrong in your db.
