### ISSUE TITLE
can't run in the background (used command : nohup java -jar grasscutter.jar > ./run.log &)

### ISSUE THREAD

**Issue by zgf33** [Melledy/Grasscutter#500]
May 04, 2022 2:51:23 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
[14:51:23] [[34mINFO[0;39m] Starting Grasscutter...
[14:51:24] [[34mINFO[0;39m] Loaded 47 FetterCharacterCardDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 300 AvatarTalentDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 400 AvatarSkillDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 4088 FetterDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 73 AvatarSkillDepotDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 167 MonsterDescribeDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 657 RewardPreviewDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 1 AvatarCostumeDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 699 DungeonDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 10 AvatarFetterLevelDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 24 DailyDungeonDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 3032 NpcDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 66 ReliquaryMainPropDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 200 MonsterCurveDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 717 SceneDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 90 AvatarLevelDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 4065 RewardDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 6889 ItemDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 336 AvatarPromoteDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 335 ReliquaryAffixDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 90 WeaponLevelDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 1195 ShopGoodsDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 939 WeaponPromoteDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 9 AvatarFlycloakDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 6626 GadgetDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 100 AvatarCurveDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 42 ReliquarySetDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 100 WeaponCurveDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 744 EquipAffixDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 8 WorldLevelDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 60 PlayerLevelDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 101 ReliquaryLevelDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 2420 ProudSkillDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 568 MonsterDatas.
[14:51:24] [[34mINFO[0;39m] Loaded 78 AvatarDatas.
[14:51:25] [[34mINFO[0;39m] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[14:51:25] [[34mINFO[0;39m] Opened connection [connectionId{localValue:1, serverValue:60}] to localhost:27017
[14:51:25] [[34mINFO[0;39m] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=8, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=40802679}
[14:51:25] [[34mINFO[0;39m] Opened connection [connectionId{localValue:2, serverValue:61}] to localhost:27017
[14:51:25] [[34mINFO[0;39m] Opened connection [connectionId{localValue:3, serverValue:62}] to localhost:27017
[14:51:25] [[34mINFO[0;39m] Registered 110 PacketHandlers
[14:51:25] [[34mINFO[0;39m] Banners successfully loaded.
[14:51:25] [[34mINFO[0;39m] Shop data successfully loaded.
[14:51:25] [[34mINFO[0;39m] ShopChest data successfully loaded.
[14:51:25] [[34mINFO[0;39m] ShopChestBatchUse data successfully loaded.
[14:51:26] [[34mINFO[0;39m] Using default implementation for ThreadExecutor
[14:51:26] [[34mINFO[0;39m] Job execution threads will use class loader of thread: main
[14:51:26] [[34mINFO[0;39m] Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[14:51:26] [[34mINFO[0;39m] Quartz Scheduler v.2.3.2 created.
[14:51:26] [[34mINFO[0;39m] RAMJobStore initialized.
[14:51:26] [[34mINFO[0;39m] Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[14:51:26] [[34mINFO[0;39m] Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
[14:51:26] [[34mINFO[0;39m] Quartz scheduler version: 2.3.2
[14:51:26] [[34mINFO[0;39m] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
[14:51:26] [[34mINFO[0;39m] Drop data successfully loaded.
[14:51:26] [[34mINFO[0;39m] Logging initialized @4165ms to org.eclipse.jetty.util.log.Slf4jLog
[14:51:26] [[34mINFO[0;39m] jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 17.0.3+8-LTS-111
[14:51:26] [[34mINFO[0;39m] x509=X509@7ef41ca2(keystore_entry,h=[mydomain.com, localhost],w=[]) for Server@6b3f4bd8[provider=null,keyStore=file:///root/grasscutter/keystore.p12,trustStore=null]
[14:51:27] [[34mINFO[0;39m] Started ServerConnector@242ff747{SSL, (ssl, http/1.1)}{0.0.0.0:4434}
[14:51:27] [[34mINFO[0;39m] Started @5060ms
[14:51:27] [[34mINFO[0;39m] Server listening on http://localhost:4434
[14:51:27] [[34mINFO[0;39m] [Dispatch] Dispatch server started on port 4434
[14:51:27] [[34mINFO[0;39m] Done! For help, type "help"
> [14:51:27] [[1;31mERROR[0;39m] An IO error occurred.
java.io.IOError: java.io.IOException: Bad file descriptor
	at org.jline.keymap.BindingReader.readCharacter(BindingReader.java:170)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:110)
	at org.jline.keymap.BindingReader.readBinding(BindingReader.java:61)
	at org.jline.reader.impl.LineReaderImpl.doReadBinding(LineReaderImpl.java:923)
	at org.jline.reader.impl.LineReaderImpl.readBinding(LineReaderImpl.java:956)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:651)
	at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:468)
	at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:195)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:123)
Caused by: java.io.IOException: Bad file descriptor
	at java.base/java.io.FileInputStream.read0(Native Method)
	at java.base/java.io.FileInputStream.read(FileInputStream.java:228)
	at org.jline.utils.NonBlockingInputStreamImpl.run(NonBlockingInputStreamImpl.java:216)
	at java.base/java.lang.Thread.run(Thread.java:833)
> [14:51:27] [[1;31mERROR[0;39m] An IO error occurred.

**Comment by Mashiro2000** [comment]
use `screen` command

**Comment by Mashiro2000** [comment]
If the problem is solved, please close.

**Comment by Birdulon** [comment]
Fixed by 0fb7d50acd4d3851a1c9a3531240ab6e46cb7759
