### ISSUE TITLE
Morphia error: Unable to make field private final byte[]

### ISSUE THREAD

**Issue by AdemJensen** [Melledy/Grasscutter#502]
Built on `development` branch, using `account create 1 1` command, getting following error: 

```
[15:57:51] [ERROR] Command error:
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @2c383e33
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at dev.morphia.mapping.MappedClass.discover(MappedClass.java:562)
        at dev.morphia.mapping.MappedClass.<init>(MappedClass.java:142)
        at dev.morphia.mapping.Mapper.getMappedClass(Mapper.java:529)
        at dev.morphia.internal.PathTarget.resolveField(PathTarget.java:169)
        at dev.morphia.internal.PathTarget.resolve(PathTarget.java:126)
        at dev.morphia.internal.PathTarget.getTarget(PathTarget.java:104)
        at dev.morphia.query.FieldCriteria.<init>(FieldCriteria.java:41)
        at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:338)
        at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:334)
        at dev.morphia.query.FieldEndImpl.equalIgnoreCase(FieldEndImpl.java:102)
        at dev.morphia.query.FieldEndImpl.equalIgnoreCase(FieldEndImpl.java:44)
        at emu.grasscutter.database.DatabaseHelper.getAccountByName(DatabaseHelper.java:81)
        at emu.grasscutter.database.DatabaseHelper.createAccountWithId(DatabaseHelper.java:28)
        at emu.grasscutter.command.commands.AccountCommand.execute(AccountCommand.java:44)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:139)
        at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:128)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:98)
```

Both JRE and JDK version is 17, which is specified by build.gradle in development branch... I think 17 does not work but the codes in development branch have involved some features from 17...

**Comment by ghost** [comment]
Java 17 does work, you might be getting that error because your gradle's libraries didnt update, I've had this issue before and it was because one of our dependencies (morphia) was still on its java-8 only version.

**Comment by AdemJensen** [comment]
> because your gradle's libraries didnt update

Could you tell me what command you have used for this so called 'update gradle lib'? I tried to run clean, and build again, but it still won't work...

> because one of our dependencies (morphia) was still on its java-8 only version

I checked the [Maven Central repository](https://mvnrepository.com/artifact/dev.morphia.morphia/morphia-core), the latest version is still 2.2.6, which is exactly the current version of our repo, which version are you using currently?

**Comment by AdemJensen** [comment]
Using the following command to bootstrap will resolve the issue: 

```bat
java  --add-opens java.base/java.lang=ALL-UNNAMED -jar .\grasscutter.jar
```

Reference: https://blog.csdn.net/keep_learn/article/details/120396667

Is there any extra compile flags or start-up flags you are using?

**Comment by AdemJensen** [comment]
I think I have found the issue,,, The development branch outputs jar file with name "grasscutter-\<VERSION\>-dev.jar"... So I have been using stable build all the time, ha ha...
