### ISSUE TITLE
some errors about logging in

### ISSUE THREAD

**Issue by rabbithzy** [Melledy/Grasscutter#516]
My launcher is in updating all the time. But when I launch the gane directly without launcher, I can log in successfully. However, when the game let me choose one of the twins and give a name ,it will disconnect from the local sever. What's more, can you write a concise hangbook, it will be very helpful for us.

**Comment by lunaticwhat** [comment]
might related to #491. should be better if you can provide the server log like that mentioned issue.

**Comment by fetterdragon** [comment]
I got excactly the same error and timing.

Here is my log:
[11:01:51] [INFO] Client 127.0.0.1 request: query_cur_region/os_usa
[11:02:00] [INFO] Client connected from 127.0.0.1
[11:03:02] [ERROR] Error creating player object:
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.def.AvatarData.getId()" because "data" is null
        at emu.grasscutter.game.avatar.Avatar.<init>(Avatar.java:122)
        at emu.grasscutter.game.avatar.Avatar.<init>(Avatar.java:117)
        at emu.grasscutter.server.packet.recv.HandlerSetPlayerBornDataReq.handle(HandlerSetPlayerBornDataReq.java:57)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:85)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:242)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
[11:03:02] [INFO] Client disconnected from 127.0.0.1
> because "data" is nullbecause "data" is nullbecause "data" is nullbecause "data" is nullbecause "data" is null

My database is brand new and the account is create a min ago.
