### ISSUE TITLE
[Issue] When connecting to game, it stopped

### ISSUE THREAD

**Issue by ghost** [Melledy/Grasscutter#518]
I have read and do all of the wiki say, but when i use fidder to connect from localhost, it's has stopped working
![image](https://user-images.githubusercontent.com/80608879/166700041-ef8b4408-5200-44da-8aae-303a7046c98d.png)
then in my server cli it say:
> java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at emu.grasscutter.game.player.TeamManager.getCurrentAvatarEntity(TeamManager.java:162)
        at emu.grasscutter.game.player.TeamManager.getCurrentCharacterGuid(TeamManager.java:123)
        at emu.grasscutter.server.packet.send.PacketAvatarDataNotify.<init>(PacketAvatarDataNotify.java:20)
        at emu.grasscutter.game.player.Player.onLogin(Player.java:1027)
        at emu.grasscutter.server.packet.recv.HandlerPlayerLoginReq.handle(HandlerPlayerLoginReq.java:44)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:85)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:242)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833).
Any idea for this? Thanks

**Comment by Remussn** [comment]
Got same error and fixed by deleting and re-creating account.

**Comment by 4Benj** [comment]
Has this issue been resolved with @Remussn's help?
