### ISSUE TITLE
Error creating account

### ISSUE THREAD

**Issue by Gelmezon** [Melledy/Grasscutter#577]
```
account create admin1 1000
 Command error: 
java.lang.reflect.InaccessibleObjectException: Unable to make field private final byte[] java.lang.String.value accessible: module java.base does not "opens java.lang" to unnamed module @2d1f8d76
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at dev.morphia.mapping.MappedClass.discover(MappedClass.java:562)
        at dev.morphia.mapping.MappedClass.<init>(MappedClass.java:142)
        at dev.morphia.mapping.Mapper.getMappedClass(Mapper.java:529)
        at dev.morphia.internal.PathTarget.resolveField(PathTarget.java:169)
        at dev.morphia.internal.PathTarget.resolve(PathTarget.java:126)
        at dev.morphia.internal.PathTarget.getTarget(PathTarget.java:104)
        at dev.morphia.query.FieldCriteria.<init>(FieldCriteria.java:41)
        at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:338)
        at dev.morphia.query.FieldEndImpl.addCriteria(FieldEndImpl.java:334)
        at dev.morphia.query.FieldEndImpl.equalIgnoreCase(FieldEndImpl.java:102)
        at dev.morphia.query.FieldEndImpl.equalIgnoreCase(FieldEndImpl.java:44)
        at emu.grasscutter.database.DatabaseHelper.getAccountByName(DatabaseHelper.java:81)
        at emu.grasscutter.database.DatabaseHelper.createAccountWithId(DatabaseHelper.java:28)
        at emu.grasscutter.command.commands.AccountCommand.execute(AccountCommand.java:44)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:139)
        at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:128)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:98)
```

but if  server start with code `-add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.net.util=ALL-UNNAMED` ,it will be ok

**Comment by KengHuai** [comment]
I had this problem too, how can I get the server to start with code?

**Comment by minhngoc25a** [comment]
> I had this problem too, how can I get the server to start with code?

It will be like this:
`java -jar grasscutter.jar -add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/sun.net.util=ALL-UNNAMED`

I tried to create an account in the latest dev commit build and it works fine. Download the `.jar` file [here](https://github.com/Grasscutters/Grasscutter/issues/577) and replace it with your current grasscutter.jar in your server root directory.

**Comment by ZARALEON** [comment]
> 
Sorry,I added the code,but it doesn't work...............
