### ISSUE TITLE
An error occurred when starting the Tower Dungeons challenge

### ISSUE THREAD

**Issue by StillMi** [Melledy/Grasscutter#599]
[05:02:58] [INFO] Loaded ./resources/Scripts/Scene/35732/scene35732.lua
[05:02:58] [INFO] Loaded ./resources/Scripts/Scene/35732/scene35732_block35732.lua
[05:02:59] [INFO] Loaded ./resources/Scripts/Scene/35732/scene35732_group235732001.lua
[05:02:59] [INFO] Loaded ./resources/Scripts/Scene/35732/scene35732_group235732002.lua
[05:02:59] [INFO] Loaded ./resources/Scripts/Scene/35732/scene35732_group235732003.lua
[05:02:59] [INFO] Loaded ./resources/Scripts/Scene/35732/scene35732_group235732004.lua
[05:02:59] [INFO] Loaded ./resources/Scripts/Scene/35732/scene35732_group235732005.lua
> org.luaj.vm2.LuaError: script:141 attempt to call nil
        at org.luaj.vm2.LuaValue.checkmetatag(Unknown Source)
        at org.luaj.vm2.LuaValue.callmt(Unknown Source)
        at org.luaj.vm2.LuaValue.call(Unknown Source)
        at org.luaj.vm2.LuaClosure.execute(Unknown Source)
        at org.luaj.vm2.LuaClosure.call(Unknown Source)
        at emu.grasscutter.scripts.SceneScriptManager.callEvent(SceneScriptManager.java:399)
        at emu.grasscutter.server.packet.recv.HandlerSelectWorktopOptionReq.handle(HandlerSelectWorktopOptionReq.java:28)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:85)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:248)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

The above is the error message when starting the challenge

**Comment by Akka0** [comment]
That means lua script call an unimplemented function in ScriptLib.java. Its still in development ...

Notice: Check your Tower Dungeons config file and download my version at https://discord.com/channels/965284035985305680/970935992032825364/972352235486969917
There are fields name mistakes in some version.

**Comment by StillMi** [comment]
> 这意味着 lua 脚本在 ScriptLib.java 中调用未实现的函数。它仍在开发中...
> 
> 注意：检查您的塔地牢配置文件，并在 https://discord.com/channels/965284035985305680/970935992032825364/972352235486969917 下载我的版本 某些版本中存在字段名称错误。

After I replaced the file ,Errors still occur in the latter levels

**Comment by KingRainbow44** [comment]
As there is no activity on this issue, it will be closed. Feel free to make another issue if the bug hasn't been fixed.
