### ISSUE TITLE
[Issue] System language does not start the emulator

### ISSUE THREAD

**Issue by Spellfox** [Melledy/Grasscutter#654]
After the last update whoever tries to start the emulator clean the first time, when generating the config.json file if your system language is not English you get the following error and the cmd closes right away,

`2022-05-07T20:21:31Z - Failed to load language file: pt-BR.json
java.lang.NullPointerException: null
	at java.base/java.io.Reader.<init>(Reader.java:168)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:112)
	at emu.grasscutter.utils.Utils.readFromInputStream(Utils.java:258)
	at emu.grasscutter.utils.Language.<init>(Language.java:55)
	at emu.grasscutter.utils.Language.getLanguage(Language.java:22)
	at emu.grasscutter.Grasscutter.loadLanguage(Grasscutter.java:158)
	at emu.grasscutter.Grasscutter.<clinit>(Grasscutter.java:63)
`
in some of the previous versions a language folder with two files was generated and now it is no longer generated when starting the emulator for the first time.

changing the config.json file as follows, it works again,
original
   "LocaleLanguage": "pt_BR",
   "DefaultLanguage": "en",

modified
   "LocaleLanguage": "en_US",
   "DefaultLanguage": "en_US",

**Comment by SunshineVX** [comment]
They integrated the language files into the package.It seems to have some bugs.

**Comment by zakhildev** [comment]
It's no surprise that selecting language which isn't supported raises an error. However I think that it should be handled by switching to English for example.

Edit: I have just checked on it. Already fixed in [this commit](https://github.com/Grasscutters/Grasscutter/commit/330427f5a56e01ecc494db4e042edad17f1eec40) on the development branch
