### ISSUE TITLE
Expected BEGIN_ARRAY but was BEGIN_OBJECT

### ISSUE THREAD

**Issue by zhaodice** [Melledy/Grasscutter#662]
```
[11:51:57] [INFO] Welcome to Grasscutter
[11:51:57] [INFO] To proper exit this console, use [Ctrl + C] and enter N not Y.
[11:51:57] [INFO]
[11:51:57] [INFO] Initializing...
[11:51:57] [WARN] mitmdump not found, server only mode.
[11:51:57] [INFO] Starting MongoDB daemon...
[11:51:57] [INFO] Starting server...
[11:51:59] [[34mINFO[0;39m] 正在启动 Grasscutter...
[11:52:00] [[34mINFO[0;39m] Loaded 47 FetterCharacterCardDatas.
[11:52:00] [[34mINFO[0;39m] Loaded 300 AvatarTalentDatas.
[11:52:00] [[34mINFO[0;39m] Loaded 400 AvatarSkillDatas.
[11:52:01] [[34mINFO[0;39m] Loaded 4088 FetterDatas.
[11:52:01] [[34mINFO[0;39m] Loaded 73 AvatarSkillDepotDatas.
[11:52:01] [[34mINFO[0;39m] Loaded 167 MonsterDescribeDatas.
[11:52:01] [[34mINFO[0;39m] Loaded 657 RewardPreviewDatas.
[11:52:01] [[34mINFO[0;39m] Loaded 39 TowerFloorDatas.
[11:52:01] [[34mINFO[0;39m] Loaded 1 AvatarCostumeDatas.
[11:52:01] [[34mINFO[0;39m] Loaded 782 DungeonDatas.
[11:52:01] [[34mINFO[0;39m] Loaded 10 AvatarFetterLevelDatas.
[11:52:01] [[34mINFO[0;39m] Loaded 24 DailyDungeonDatas.
[11:52:02] [[34mINFO[0;39m] Loaded 3032 NpcDatas.
[11:52:02] [[34mINFO[0;39m] Loaded 66 ReliquaryMainPropDatas.
[11:52:02] [[1;31mERROR[0;39m] Error loading resource file: [MonsterCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:130)
	at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:117)
	at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:107)
	at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:51)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:93)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 8 common frames omitted
[11:52:02] [[34mINFO[0;39m] Loaded 717 SceneDatas.
[11:52:02] [[34mINFO[0;39m] Loaded 90 AvatarLevelDatas.
[11:52:02] [[34mINFO[0;39m] Loaded 4065 RewardDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 6889 ItemDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 336 AvatarPromoteDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 335 ReliquaryAffixDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 90 WeaponLevelDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 1195 ShopGoodsDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 297 CombineDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 1 TowerLevelDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 939 WeaponPromoteDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 9 AvatarFlycloakDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 6626 GadgetDatas.
[11:52:03] [[1;31mERROR[0;39m] Error loading resource file: [AvatarCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:130)
	at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:117)
	at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:107)
	at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:51)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:93)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 8 common frames omitted
[11:52:03] [[34mINFO[0;39m] Loaded 42 ReliquarySetDatas.
[11:52:03] [[1;31mERROR[0;39m] Error loading resource file: [WeaponCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:130)
	at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:117)
	at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:107)
	at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:51)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:93)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
	at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	... 8 common frames omitted
[11:52:03] [[34mINFO[0;39m] Loaded 744 EquipAffixDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 8 WorldLevelDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 60 PlayerLevelDatas.
[11:52:03] [[34mINFO[0;39m] Loaded 101 ReliquaryLevelDatas.
[11:52:04] [[34mINFO[0;39m] Loaded 2420 ProudSkillDatas.
[11:52:04] [[34mINFO[0;39m] Loaded 568 MonsterDatas.
[11:52:04] [[34mINFO[0;39m] Loaded 78 AvatarDatas.
[11:52:04] [[1;31mERROR[0;39m] Relic properties are missing weights! Please check your ReliquaryMainPropExcelConfigData or ReliquaryAffixExcelConfigData files in your ExcelBinOutput folder.
[11:52:05] [[34mINFO[0;39m] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[11:52:05] [[34mINFO[0;39m] Opened connection [connectionId{localValue:2, serverValue:10}] to localhost:27017
[11:52:05] [[34mINFO[0;39m] Opened connection [connectionId{localValue:1, serverValue:11}] to localhost:27017
[11:52:05] [[34mINFO[0;39m] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=66159962}
[11:52:05] [[34mINFO[0;39m] Opened connection [connectionId{localValue:3, serverValue:12}] to localhost:27017
[11:52:05] [[34mINFO[0;39m] Registered 120 PacketHandlers
[11:52:05] [[34mINFO[0;39m] Banners successfully loaded.
[11:52:05] [[34mINFO[0;39m] Shop data successfully loaded.
[11:52:05] [[34mINFO[0;39m] ShopChest data successfully loaded.
[11:52:05] [[34mINFO[0;39m] ShopChestBatchUse data successfully loaded.
[11:52:06] [[34mINFO[0;39m] Using default implementation for ThreadExecutor
[11:52:06] [[34mINFO[0;39m] Job execution threads will use class loader of thread: main
[11:52:06] [[34mINFO[0;39m] Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[11:52:06] [[34mINFO[0;39m] Quartz Scheduler v.2.3.2 created.
[11:52:06] [[34mINFO[0;39m] RAMJobStore initialized.
[11:52:06] [[34mINFO[0;39m] Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[11:52:06] [[34mINFO[0;39m] Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
[11:52:06] [[34mINFO[0;39m] Quartz scheduler version: 2.3.2
[11:52:06] [[34mINFO[0;39m] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
[11:52:06] [[34mINFO[0;39m] Drop data successfully loaded.
[11:52:06] [[34mINFO[0;39m] Expedition reward successfully loaded.
[11:52:06] [[34mINFO[0;39m] Logging initialized @8445ms to org.eclipse.jetty.util.log.Slf4jLog
[11:52:06] [[34mINFO[0;39m] jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 17.0.3+7
[11:52:06] [[1;31mERROR[0;39m] Failed to start Express
```
related file: https://github.com/Dimbreath/GenshinData/blob/master/ExcelBinOutput/MonsterCurveExcelConfigData.json

**Comment by gentlespoon** [comment]
Use Kokoboya resources.

**Comment by zhaodice** [comment]
> Use Kokoboya resources.

where may I found it?

**Comment by stevenkang** [comment]
Solutions for reference:
  1. Find error json file name in source code, example “WeaponCurveExcelConfigData.json” in emu.grasscutter.data.def.MonsterCurveData
  2. Replace all curveInfos -> curveInfosMap（Match case）
  3. Rebuild source code using "gradlew build"
  4. Restart, All done

**Comment by zhaodice** [comment]
> 2\. curveInfosMap

thank you very mush, it does work
