### ISSUE TITLE
运行时出现的错误，

### ISSUE THREAD

**Issue by zxl-qq927489674** [Melledy/Grasscutter#667]
```
[13:35:17] [ERROR] Crypto error.
java.lang.ArithmeticException: / by zero
        at emu.grasscutter.utils.Crypto.xor(Crypto.java:27)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:190)
        at emu.grasscutter.netty.MihoyoKcpChannel.channelRead(MihoyoKcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by SunshineVX** [comment]
能不能详细一点，什么情况下出现的错误？可以正常进行游戏吗

**Comment by zxl-qq927489674** [comment]
部署到远程服务器端运行，登陆后，加载游戏出现此错误。
<img width="961" alt="image" src="https://user-images.githubusercontent.com/81957406/167283800-b0d9de65-267d-4ac9-ab6e-c2bd28ed0d75.png">

**Comment by zxl-qq927489674** [comment]
> 不能正常进行游戏吗？

我将Grasscutters部署到远程服务器，登陆完后应该正常出现加载页面。却只出现UID的空白页面。查看服务器端出现了此错误

**Comment by arthasxkyang** [comment]
加密出错？看看配置文件的证书密码有没有填

**Comment by lunaticwhat** [comment]
try to add `"KeystorePassword": "123456"` in config.json

**Comment by zxl-qq927489674** [comment]
> 

没有效果，一样的报错

**Comment by arthasxkyang** [comment]
你的 config.json 全文发一下？

**Comment by zxl-qq927489674** [comment]
> 你的 config.json 全文发一下？

```
{
  "DatabaseUrl": "mongodb://localhost:27017",
  "DatabaseCollection": "grasscutter",
  "RESOURCE_FOLDER": "./resources/",
  "DATA_FOLDER": "./data/",
  "PACKETS_FOLDER": "./packets/",
  "DUMPS_FOLDER": "./dumps/",
  "KEY_FOLDER": "./keys/",
  "RunMode": "HYBRID",
  "GameServer": {
    "Name": "Test",
    "Ip": "0.0.0.0",
    "PublicIp": "IP隐藏一下哈.244",
    "Port": 22102,
    "DispatchServerDatabaseUrl": "mongodb://localhost:27017",
    "DispatchServerDatabaseCollection": "grasscutter",
    "LOG_PACKETS": false,
    "InventoryLimitWeapon": 2000,
    "InventoryLimitRelic": 2000,
    "InventoryLimitMaterial": 2000,
    "InventoryLimitFurniture": 2000,
    "InventoryLimitAll": 30000,
    "MaxAvatarsInTeam": 4,
    "MaxAvatarsInTeamMultiplayer": 4,
    "MaxEntityLimit": 1000,
    "WatchGacha": false,
    "WelcomeEmotes": [
      2007,
      1002,
      4010
    ],
    "WelcomeMotd": "Welcome to Grasscutter emu",
    "Game": {
      "ADVENTURE_EXP_RATE": 1.0,
      "MORA_RATE": 1.0,
      "DOMAIN_DROP_RATE": 1.0
    }
  },
  "DispatchServer": {
    "Ip": "0.0.0.0",
    "PublicIp": "IP隐藏一下哈.244",
    "Port": 443,
    "KeystorePath": "./keystore.p12",
    "KeystorePassword": "123456",
    "UseSSL": true,
    "AutomaticallyCreateAccounts": false,
    "GameServers": []
  }
}
```

**Comment by zxl-qq927489674** [comment]
问题解决了，是JDK版本问题，我的是1.8_271，所以不行。需要17.0.2

**Comment by lonelil** [comment]
I am having the same issue, but I only have JDK 17 installed.
