### ISSUE TITLE
[Issue] getWeapon return null value

### ISSUE THREAD

**Issue by SmokeMercy** [Melledy/Grasscutter#674]
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.inventory.GameItem.getGuid()" because the return value of "emu.grasscutter.game.avatar.Avatar.getWeapon()" is null
        at emu.grasscutter.server.packet.send.PacketSceneTeamUpdateNotify.<init>(PacketSceneTeamUpdateNotify.java:27)
        at emu.grasscutter.server.packet.recv.HandlerSceneInitFinishReq.handle(HandlerSceneInitFinishReq.java:42)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:86)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:250)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by sth4nothing** [comment]
Did you encounter this bug:
> Error loading resource file: [WeaponCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:932)
        at com.google.gson.Gson.fromJson(Gson.java:897)
        at com.google.gson.Gson.fromJson(Gson.java:846)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:130)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:117)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:107)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:51)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:93)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        ... 8 common frames omitted

**Comment by AZthemute** [comment]
I got this bug earlier when experimenting with invalid/unused characters like 10000001 (Kate) and switching to them.

You can modify the database to switch to another character in your party.

**Comment by SmokeMercy** [comment]
> Did you encounter this bug:
> 
> > Error loading resource file: [WeaponCurveExcelConfigData.json]
> > com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
> > at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
> > at com.google.gson.Gson.fromJson(Gson.java:932)
> > at com.google.gson.Gson.fromJson(Gson.java:897)
> > at com.google.gson.Gson.fromJson(Gson.java:846)
> > at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:130)
> > at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:117)
> > at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:107)
> > at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:51)
> > at emu.grasscutter.Grasscutter.main(Grasscutter.java:93)
> > Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
> > at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
> > at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
> > at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
> > at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
> > at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
> > ... 8 common frames omitted



> Did you encounter this bug:
> 
> > Error loading resource file: [WeaponCurveExcelConfigData.json]
> > com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
> > at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
> > at com.google.gson.Gson.fromJson(Gson.java:932)
> > at com.google.gson.Gson.fromJson(Gson.java:897)
> > at com.google.gson.Gson.fromJson(Gson.java:846)
> > at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:130)
> > at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:117)
> > at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:107)
> > at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:51)
> > at emu.grasscutter.Grasscutter.main(Grasscutter.java:93)
> > Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
> > at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:349)
> > at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
> > at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
> > at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
> > at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
> > ... 8 common frames omitted

yes,i got this,but it can still start

**Comment by SmokeMercy** [comment]
> I got this bug earlier when experimenting with invalid/unused characters like 10000001 (Kate) and switching to them.
> 
> You can modify the database to switch to another character in your party.

I re-established the account and the problem remained

**Comment by ProgrammerXy** [comment]
Hi, I had the same problem, I checked the logs and found that the service had a problem with the config file while initializing, so I changed the source of the config file, from https://github.com/Dimbreath/GenshinData/tree/ a83df7fcbcc26b2fc3d2918354caaaf223a40611 Changed to https://github.com/Koko-boya/Grasscutter_Resources This problem is solved, hope it can help you

**Comment by MoeRoach** [comment]
> Hi, I had the same problem, I checked the logs and found that the service had a problem with the config file while initializing, so I changed the source of the config file, from https://github.com/Dimbreath/GenshinData/tree/ a83df7fcbcc26b2fc3d2918354caaaf223a40611 Changed to https://github.com/Koko-boya/Grasscutter_Resources This problem is solved, hope it can help you

This works for me, and I'm pretty sure this will work for others too.
Coz I track down the whole process of starting with a brand new account, and find where the real problem is.

The exception show up because the ItemData never add to the avatar, the "putItem" function returned silently without actually put the starting weapon to inventory.
And the reason is that the "ItemType" of the weapon remains "ITEM_NONE" when executing "putItem" function, when I see this in the log info, I quickly understand the real problem is about the "WeaponExcelConfigData.json" file itself.

Open up those two files from https://github.com/Dimbreath/GenshinData/tree/ and https://github.com/Koko-boya/Grasscutter_Resources, compare them with each other and the problem will show up.

The very first character of every single data field key is different, for example, when grasscutter need "ItemType" in the data structure, the json file form https://github.com/Dimbreath/GenshinData/tree/ gave us "itemType".

So the solution is simple, use the files from https://github.com/Koko-boya/Grasscutter_Resources
Or change the first character of every data field key in every json file, which may need some coding :p

**Comment by SmokeMercy** [comment]
> > Hi, I had the same problem, I checked the logs and found that the service had a problem with the config file while initializing, so I changed the source of the config file, from https://github.com/Dimbreath/GenshinData/tree/ a83df7fcbcc26b2fc3d2918354caaaf223a40611 Changed to https://github.com/Koko-boya/Grasscutter_Resources This problem is solved, hope it can help you
> 
> This works for me, and I'm pretty sure this will work for others too. Coz I track down the whole process of starting with a brand new account, and find where the real problem is.
> 
> The exception show up because the ItemData never add to the avatar, the "putItem" function returned silently without actually put the starting weapon to inventory. And the reason is that the "ItemType" of the weapon remains "ITEM_NONE" when executing "putItem" function, when I see this in the log info, I quickly understand the real problem is about the "WeaponExcelConfigData.json" file itself.
> 
> Open up those two files from https://github.com/Dimbreath/GenshinData/tree/ and https://github.com/Koko-boya/Grasscutter_Resources, compare them with each other and the problem will show up.
> 
> The very first character of every single data field key is different, for example, when grasscutter need "ItemType" in the data structure, the json file form https://github.com/Dimbreath/GenshinData/tree/ gave us "itemType".
> 
> So the solution is simple, use the files from https://github.com/Koko-boya/Grasscutter_Resources Or change the first character of every data field key in every json file, which may need some coding :p

thanks much more,its work.i can play this game again,ヽ(✿ﾟ▽ﾟ)ノ
