### ISSUE TITLE
[Bug] many command feedbacks are improper

### ISSUE THREAD

**Issue by SunshineVX** [Melledy/Grasscutter#677]
**Describe the bug**

As the screenshots.   Also,some commands aren't working. 
**Which branch did you use?**

development
**Screenshots**

![图片](https://user-images.githubusercontent.com/41134981/167290727-45aa6dc6-63ab-4615-a490-1f5b9560c819.png)

**Additional context**

**Comment by SunshineVX** [comment]
The language file seems to be unable to modify these prompts.

**Comment by AZthemute** [comment]
The last one is intentional as far as I know, but the others are definitely not working as intended.

Can you tell us the EXACT commands you used to generate these responses?

**Comment by Lynricsy** [comment]
> The last one is intentional as far as I know, but the others are definitely not working as intended.
> 
> Can you tell us the EXACT commands you used to generate these responses?

I have the same problem at the latest development branch.Commands like `stats` can cause this issue.

**Comment by AZthemute** [comment]
> > The last one is intentional as far as I know, but the others are definitely not working as intended.
> > Can you tell us the EXACT commands you used to generate these responses?
> 
> I have the same problem at the latest development branch.Commands like `stats` can cause this issue.

![image](https://user-images.githubusercontent.com/104761702/167294025-7356135d-d4c9-4166-878f-b7cb978c4438.png)
Is this what you're seeing?

**Comment by SunshineVX** [comment]
> The last one is intentional as far as I know, but the others are definitely not working as intended.
> 
> Can you tell us the EXACT commands you used to generate these responses?
![{9%A$FW9PN%DZ51G 9`OB_F](https://user-images.githubusercontent.com/41134981/167294442-d452d7c2-b0c8-4367-bd27-8706ebe60ba1.png)


This appears when using /setfetterlevel.
![FKFY4GC9IC@4HM%`XONGFY9](https://user-images.githubusercontent.com/41134981/167294493-b485ce8c-0155-48a3-bdf9-144cbc6e32d7.png)

This appears when using /changescene.
![}K277C)D6GOXS05I3 F1D0T](https://user-images.githubusercontent.com/41134981/167294537-ed3af82b-c788-4c2d-9a93-e1f2aea5614d.png)

And these appear when using /stats.

**Comment by SunshineVX** [comment]
![D_@4EBG22M5LRY$ BGU6R6I](https://user-images.githubusercontent.com/41134981/167294593-3e52ccfe-8277-40c9-b27a-462af8ecf990.png)
Also when using /position
`[19:29:39] [ERROR] Failed to format string: commands.position.success
java.util.IllegalFormatConversionException: f != java.lang.String
        at java.base/java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4442)
        at java.base/java.util.Formatter$FormatSpecifier.printFloat(Formatter.java:2976)
        at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2924)
        at java.base/java.util.Formatter.format(Formatter.java:2689)
        at java.base/java.util.Formatter.format(Formatter.java:2625)
        at java.base/java.lang.String.formatted(String.java:4202)
        at emu.grasscutter.utils.Language.translate(Language.java:35)
        at emu.grasscutter.command.commands.PositionCommand.execute(PositionCommand.java:23)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:226)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:230)
        at emu.grasscutter.game.managers.ChatManager.sendPrivateMessage(ChatManager.java:37)
        at emu.grasscutter.server.packet.recv.HandlerPrivateChatReq.handle(HandlerPrivateChatReq.java:18)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:86)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:250)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)`
this happened

**Comment by SunshineVX** [comment]
All command descriptions are not displayed properly.

**Comment by Mateoust** [comment]
自行构建一个jar或者从这里下载一个最新版本[https://ci.grasscutter.ga/job/Grasscutter-Dev/](https://ci.grasscutter.ga/job/Grasscutter-Dev/),再尝试是否问题依旧存在。

Build a jar yourself or download the latest version from here [https://ci.grasscutter.ga/job/Grasscutter-Dev/](https://ci.grasscutter.ga/job/Grasscutter-Dev/), and try again Whether the problem still exists.

**Comment by SunshineVX** [comment]
> 自行构建一个jar或者从这里下载一个最新版本https://ci.grasscutter.ga/job/Grasscutter-Dev/,再尝试是否问题依旧存在。
> 
> Build a jar yourself or download the latest version from here https://ci.grasscutter.ga/job/Grasscutter-Dev/, and try again Whether the problem still exists.

Okay,now only /stats and /position have something wrong.

**Comment by Mateoust** [comment]
> 好的，现在只有 /stats 和 /position 有问题。

我提交了一个Pr，请尝试一下问题是否存在。
I submitted a Pull request, please try to see if the problem persists.

如果可以的话，麻烦检查一下所有命令以发现更多问题
If you can, please check all the commands to find more problems

**Comment by SunshineVX** [comment]
> > 好的，现在只有 /stats 和 /position 有问题。
> 
> 我提交了一个Pr，请尝试一下问题是否存在。 I submitted a Pull request, please try to see if the problem persists.
> 
> 如果可以的话，麻烦检查一下所有命令以发现更多问题 If you can, please check all the commands to find more problems

![图片](https://user-images.githubusercontent.com/41134981/167417781-e6544d22-8990-49ae-a04e-a8f413599035.png)
![图片](https://user-images.githubusercontent.com/41134981/167417798-f16e687e-60ec-4b19-8008-6d533b23f6ec.png)
好像/stats的反馈还是不太对，这两个应该分别显示最大生命和火元素伤害加成。
Well,it seems that /stats is still not quite right.
![图片](https://user-images.githubusercontent.com/41134981/167419135-c4b3b0e3-aafd-4bc2-9dae-12d7856ad9cd.png)
而且，发送邮件设置标题阶段的提示有误，应该是/sendmail 而不是/send。
And,there is an error in the prompt when setting the header of the email.It should be '/sendmail' instead of '/send'.
