### ISSUE TITLE
[Bug] 添加三星圣遗物会报错（但实际添加成功），此外如何添加五星圣遗物？

### ISSUE THREAD

**Issue by mengdalida** [Melledy/Grasscutter#727]
**Describe the bug**

** 使用的命令  give @Uid  71345 1 20**   

控制台此处 会报错 ，但实际添加成功，添加成功的圣遗物都为3星，

**Which branch did you use?**

Stable branch

**Screenshots**

java.util.MissingFormatArgumentException: Format specifier '%s'
        at java.base/java.util.Formatter.format(Formatter.java:2688)
        at java.base/java.util.Formatter.format(Formatter.java:2625)
        at java.base/java.lang.String.formatted(String.java:4202)
        at emu.grasscutter.utils.Language.translate(Language.java:35)
        at emu.grasscutter.command.commands.GiveCommand.execute(GiveCommand.java:127)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:226)
        at emu.grasscutter.command.CommandMap.invoke(CommandMap.java:230)
        at emu.grasscutter.Grasscutter.startConsole(Grasscutter.java:201)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:129)
[17:50:27] [INFO] 已将 %s 等级 %s %s 个给予 %s

**Additional context**

**此外想了解下，如何添加5星的圣遗物**

**Comment by zhaodice** [comment]
English recommended

**Comment by don1103** [comment]
物品ID错了吧
前两位是套装编号，3号位是星级，4号位是部件，5号位是词缀数。
71345即冰封套，3星，生之花，5条词缀。但不存在第5条词缀。

**Comment by mengdalida** [comment]
> 物品ID错了吧 前两位是套装编号，3号位是星级，4号位是部件，5号位是词缀数。 71345即冰封套，3星，生之花，5条词缀。但不存在第5条词缀。
Readme 里 是这样 **give [uid] <物品ID|物品名称> [数量] [等级] [精炼等级]**
所以正确的命令是什么？ 71344 : 历经风雪的思念  
_give @uid 71344(物品名称)1(数量) 20(等级)_  没问题啊

**Comment by jie65535** [comment]
获取圣遗物请使用 `/giveart` 指令
Give Artifact, please use the `/giveart` command
`/giveart 71344 21`

**Comment by mengdalida** [comment]
> 获取圣遗物请使用 `/giveart` 指令 Give Artifact, please use the `/giveart` command `/giveart 71344 21`
我又试了下，实际命令应该是
**/giveart 71344(Id)  1(数量) 20(等级)**
