### ISSUE TITLE
[Issue] 进入游戏后卡死，服务端报错

### ISSUE THREAD

**Issue by Easonqsp** [Melledy/Grasscutter#729]
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.inventory.GameItem.getGuid()" because the return value of "emu.grasscutter.game.avatar.Avatar.getWeapon()" is null
        at emu.grasscutter.server.packet.send.PacketSceneTeamUpdateNotify.<init>(PacketSceneTeamUpdateNotify.java:27)
        at emu.grasscutter.server.packet.recv.HandlerSceneInitFinishReq.handle(HandlerSceneInitFinishReq.java:42)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:86)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:250)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by XihuanAL** [comment]
maybe you need to use java17

**Comment by MoeRoach** [comment]
Json file problem, use the resources files in this repo: https://github.com/Koko-boya/Grasscutter_Resources to replace yours.

**Comment by Easonqsp** [comment]
Well, it didn't work at all.

**Comment by MoeRoach** [comment]
> Well, it didn't work at all.

你看看resources\ExcelBinOutput目录下的WeaponExcelConfigData.json文件的内容，如果里面那些字段名都是小写字母的，那就说明文件依然不对

比如说第三行的WeaponType，错误的文件里会写weaponType，开头字母小写，这样的json文件就读不到服务端里
所以你可以再检查检查

**Comment by Easonqsp** [comment]
好了，我把东西都删了再重新搞就好了

**Comment by kaister3** [comment]
why this happen

> > Well, it didn't work at all.
> 
> 你看看resources\ExcelBinOutput目录下的WeaponExcelConfigData.json文件的内容，如果里面那些字段名都是小写字母的，那就说明文件依然不对
> 
> 比如说第三行的WeaponType，错误的文件里会写weaponType，开头字母小写，这样的json文件就读不到服务端里 所以你可以再检查检查

请问这问题为什么发生？是否官方 json file 更新？
