### ISSUE TITLE
Exception when restart server

### ISSUE THREAD

**Issue by MlgmXyysd** [Melledy/Grasscutter#73]
Restarting (stop & start) the server when the player is online will bring up spam
```
java.io.IOException: Conv inconsistency
        at io.jpower.kcp.netty.Ukcp.input(Ukcp.java:147)
        at io.jpower.kcp.netty.UkcpServerChildChannel.kcpInput(UkcpServerChildChannel.java:201)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:591)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by memetrollsXD** [comment]
Explanation: Ah that’s cuz there’s a new KCP thing, but client is trying to connect to old one. So it goes on until client gives up and reconnects

**Comment by TheOrdinaryWow** [comment]
I had the same problem as well, but I met this when I was in game.

**Comment by KingRainbow44** [comment]
this is a known bug with KCP netty, i *believe* this is out of our control, so i will be closing this issue.
