### ISSUE TITLE
[Issue] After logging to the server, I can't do anything. Logs and screenshot are as follows.

### ISSUE THREAD

**Issue by HyperLYP** [Melledy/Grasscutter#732]
`F:\GI_private_server\Latest\Grasscutter>java -jar grasscutter-1.1.0.jar
[19:06:44] [INFO] 正在启动 Grasscutter...
[19:06:44] [INFO] Loaded 47 FetterCharacterCardDatas.
[19:06:44] [INFO] Loaded 300 AvatarTalentDatas.
[19:06:44] [INFO] Loaded 400 AvatarSkillDatas.
[19:06:44] [INFO] Loaded 4088 FetterDatas.
[19:06:44] [INFO] Loaded 73 AvatarSkillDepotDatas.
[19:06:44] [INFO] Loaded 167 MonsterDescribeDatas.
[19:06:44] [INFO] Loaded 657 RewardPreviewDatas.
[19:06:44] [INFO] Loaded 39 TowerFloorDatas.
[19:06:44] [INFO] Loaded 1 AvatarCostumeDatas.
[19:06:44] [INFO] Loaded 782 DungeonDatas.
[19:06:44] [INFO] Loaded 10 AvatarFetterLevelDatas.
[19:06:44] [INFO] Loaded 24 DailyDungeonDatas.
[19:06:45] [INFO] Loaded 3032 NpcDatas.
[19:06:45] [INFO] Loaded 66 ReliquaryMainPropDatas.
[19:06:45] [ERROR] Error loading resource file: [MonsterCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:225)
        at com.google.gson.Gson.fromJson(Gson.java:991)
        at com.google.gson.Gson.fromJson(Gson.java:956)
        at com.google.gson.Gson.fromJson(Gson.java:905)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:130)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:117)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:107)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:51)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:93)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        ... 8 common frames omitted
[19:06:45] [INFO] Loaded 717 SceneDatas.
[19:06:45] [INFO] Loaded 90 AvatarLevelDatas.
[19:06:45] [INFO] Loaded 4065 RewardDatas.
[19:06:45] [INFO] Loaded 6889 ItemDatas.
[19:06:45] [INFO] Loaded 336 AvatarPromoteDatas.
[19:06:45] [INFO] Loaded 335 ReliquaryAffixDatas.
[19:06:45] [INFO] Loaded 90 WeaponLevelDatas.
[19:06:45] [INFO] Loaded 1195 ShopGoodsDatas.
[19:06:45] [INFO] Loaded 297 CombineDatas.
[19:06:45] [INFO] Loaded 1 TowerLevelDatas.
[19:06:45] [INFO] Loaded 939 WeaponPromoteDatas.
[19:06:45] [INFO] Loaded 9 AvatarFlycloakDatas.
[19:06:45] [INFO] Loaded 6626 GadgetDatas.
[19:06:45] [ERROR] Error loading resource file: [AvatarCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:225)
        at com.google.gson.Gson.fromJson(Gson.java:991)
        at com.google.gson.Gson.fromJson(Gson.java:956)
        at com.google.gson.Gson.fromJson(Gson.java:905)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:130)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:117)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:107)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:51)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:93)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        ... 8 common frames omitted
[19:06:45] [INFO] Loaded 42 ReliquarySetDatas.
[19:06:45] [ERROR] Error loading resource file: [WeaponCurveExcelConfigData.json]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:225)
        at com.google.gson.Gson.fromJson(Gson.java:991)
        at com.google.gson.Gson.fromJson(Gson.java:956)
        at com.google.gson.Gson.fromJson(Gson.java:905)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:130)
        at emu.grasscutter.data.ResourceLoader.loadFromResource(ResourceLoader.java:117)
        at emu.grasscutter.data.ResourceLoader.loadResources(ResourceLoader.java:107)
        at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:51)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:93)
Caused by: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 4 column 6 path $.curveInfos[0]
        at com.google.gson.stream.JsonReader.beginArray(JsonReader.java:350)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:172)
        at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
        ... 8 common frames omitted
[19:06:45] [INFO] Loaded 744 EquipAffixDatas.
[19:06:45] [INFO] Loaded 8 WorldLevelDatas.
[19:06:45] [INFO] Loaded 60 PlayerLevelDatas.
[19:06:45] [INFO] Loaded 101 ReliquaryLevelDatas.
[19:06:45] [INFO] Loaded 2420 ProudSkillDatas.
[19:06:45] [INFO] Loaded 568 MonsterDatas.
[19:06:45] [INFO] Loaded 78 AvatarDatas.
[19:06:45] [ERROR] Relic properties are missing weights! Please check your ReliquaryMainPropExcelConfigData or ReliquaryAffixExcelConfigData files in your ExcelBinOutput folder.
[19:06:46] [INFO] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms'}
[19:06:46] [INFO] Opened connection [connectionId{localValue:1, serverValue:68}] to localhost:27017
[19:06:46] [INFO] Opened connection [connectionId{localValue:2, serverValue:69}] to localhost:27017
[19:06:46] [INFO] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=13, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=16182500}
[19:06:46] [INFO] Opened connection [connectionId{localValue:3, serverValue:70}] to localhost:27017
[19:06:46] [INFO] Registered 120 PacketHandlers
[19:06:46] [INFO] Banners successfully loaded.
[19:06:46] [INFO] Shop data successfully loaded.
[19:06:46] [INFO] ShopChest data successfully loaded.
[19:06:46] [INFO] ShopChestBatchUse data successfully loaded.
[19:06:46] [INFO] Using default implementation for ThreadExecutor
[19:06:46] [INFO] Job execution threads will use class loader of thread: main
[19:06:46] [INFO] Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[19:06:46] [INFO] Quartz Scheduler v.2.3.2 created.
[19:06:46] [INFO] RAMJobStore initialized.
[19:06:46] [INFO] Scheduler meta-data: Quartz Scheduler (v2.3.2) 'DefaultQuartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[19:06:46] [INFO] Quartz scheduler 'DefaultQuartzScheduler' initialized from default resource file in Quartz package: 'quartz.properties'
[19:06:46] [INFO] Quartz scheduler version: 2.3.2
[19:06:46] [INFO] Scheduler DefaultQuartzScheduler_$_NON_CLUSTERED started.
[19:06:46] [INFO] Drop data successfully loaded.
[19:06:46] [INFO] Expedition reward successfully loaded.
[19:06:46] [INFO] Logging initialized @2956ms to org.eclipse.jetty.util.log.Slf4jLog
[19:06:46] [INFO] jetty-9.4.35.v20201120; built: 2020-11-20T21:17:03.964Z; git: bdc54f03a5e0a7e280fab27f55c3c75ee8da89fb; jvm 17.0.2+8-86
[19:06:46] [INFO] x509=X509@77bb916f(keystore_entry,h=[mydomain.com, localhost],w=[]) for Server@5a48d186[provider=null,keyStore=file:///F:/GI_private_server/Latest/Grasscutter/keystore.p12,trustStore=null]
[19:06:46] [INFO] Started ServerConnector@4264beb8{SSL, (ssl, http/1.1)}{0.0.0.0:443}
[19:06:46] [INFO] Started @3319ms
[19:06:46] [INFO] Server listening on http://localhost:443
[19:06:46] [INFO] [Dispatch] 服务器已在端口 443 上启动
[19:06:46] [INFO] 加載完成！输入 "help" 查看命令列表
[19:06:47] [INFO] Grasscutter 是免费开源软件。如果你是付费购买的，那已经被骗了。Github：https://github.com/Grasscutters/Grasscutter
[19:06:47] [INFO] 游戏服务器已在端口 22102 上启动
[19:07:03] [INFO] [Dispatch] Client [0:0:0:0:0:0:0:1] request: query_region_list
[19:07:03] [INFO] [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 正在尝试使用令牌登录
[19:07:03] [INFO] [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 已通过令牌登录，UID为 10001
[19:07:04] [INFO] [Dispatch] 客户端 [0:0:0:0:0:0:0:1] 交换令牌成功
[19:07:04] [INFO] Client 127.0.0.1 request: query_cur_region/os_usa
[19:08:58] [INFO] 客户端已连接至 192.168.31.32
> java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.inventory.GameItem.getGuid()" because the return value of "emu.grasscutter.game.avatar.Avatar.getWeapon()" is null
        at emu.grasscutter.server.packet.send.PacketSceneTeamUpdateNotify.<init>(PacketSceneTeamUpdateNotify.java:27)
        at emu.grasscutter.server.packet.recv.HandlerSceneInitFinishReq.handle(HandlerSceneInitFinishReq.java:42)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:86)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:250)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
[19:10:19] [INFO] 客户端 192.168.31.32 已断开连接`

**Comment by HyperLYP** [comment]
![QQ图片20220509191545](https://user-images.githubusercontent.com/63620765/167399382-b0c0f94b-4634-46cf-bb74-d38ee029d7f7.png)

**Comment by HyperLYP** [comment]
Could you please tell me how to deal with it? Thanks~

**Comment by Mateoust** [comment]
Check your resources folder
You can use the files here：[Koko-boya/Grasscutter_Resources](https://github.com/Koko-boya/Grasscutter_Resources)

**Comment by MoeRoach** [comment]
Json file problem, use this repo: https://github.com/Koko-boya/Grasscutter_Resources

**Comment by HyperLYP** [comment]
> 

Thank you very much ~

**Comment by lunaticwhat** [comment]
Have you solved your problem @HyperLYP ? 
If yes you help us close the issue !

**Comment by HyperLYP** [comment]
> Have you solved your problem @HyperLYP ? If yes you help us close the issue !

ok i will close it soon.
