### ISSUE TITLE
[Bug] NullPointerException error after pr #746

### ISSUE THREAD

**Issue by mcxiaoke** [Melledy/Grasscutter#759]
1. when game started ,grasscutter got errors:
2. tower dungeon empty floors, latest dev branch, after https://github.com/Grasscutters/Grasscutter/pull/746 @Akka0 

error message: 
```
java.lang.NullPointerException: Cannot invoke "emu.grasscutter.data.def.TowerScheduleData.getSchedules()" because the return value of "emu.grasscutter.game.tower.TowerScheduleManager.getCurrentTowerScheduleData()" is null
	at emu.grasscutter.game.tower.TowerScheduleManager.getScheduleFloors(TowerScheduleManager.java:47)
	at emu.grasscutter.server.packet.send.PacketTowerAllDataRsp.<init>(PacketTowerAllDataRsp.java:33)
	at emu.grasscutter.server.packet.recv.HandlerTowerAllDataReq.handle(HandlerTowerAllDataReq.java:16)
	at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:86)
	at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:250)
	at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by NeoMika** [comment]
the same problem

**Comment by Akka0** [comment]
use the res at here https://github.com/Koko-boya/Grasscutter_Resources/

**Comment by mcxiaoke** [comment]
error because @Akka0  modified data file here:  https://github.com/Koko-boya/Grasscutter_Resources/pull/2/files and no one noticed, but standard data (many people use this) is here https://github.com/Dimbreath/GenshinData now two resources are different @Melledy 

extracted raw data should not be modified.

**Comment by mcxiaoke** [comment]
solved

**Comment by 582856** [comment]
So how should it be repaired
