### ISSUE TITLE
[Issue] error with message "[WARN] Failed to load language file: en.json"

### ISSUE THREAD

**Issue by GeorgeLZH0913** [Melledy/Grasscutter#793]
[02:10:11] [WARN] Failed to load language file: en.json
java.lang.NullPointerException: null
        at java.base/java.io.Reader.<init>(Reader.java:168)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:112)
        at emu.grasscutter.utils.Utils.readFromInputStream(Utils.java:258)
        at emu.grasscutter.utils.Language.<init>(Language.java:55)
        at emu.grasscutter.utils.Language.getLanguage(Language.java:22)
        at emu.grasscutter.Grasscutter.loadLanguage(Grasscutter.java:158)
        at emu.grasscutter.Grasscutter.<clinit>(Grasscutter.java:63)
Exception in thread "main" java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.has(String)" because "object" is null
        at emu.grasscutter.utils.Language.get(Language.java:83)
        at emu.grasscutter.utils.Language.translate(Language.java:32)
        at emu.grasscutter.utils.Utils.startupCheck(Utils.java:184)
        at emu.grasscutter.Grasscutter.<clinit>(Grasscutter.java:66)

**Comment by Moeriko** [comment]
would appreciate if you checked pinned in #support

**Comment by legends-killer** [comment]
Could you please give out your solution? I have the same problem as you.

**Comment by GeorgeLZH0913** [comment]
> Could you please give out your solution? I have the same problem as you.

你是用的Linux服务器吗？要注意在Grasscutter的根目录下运行

**Comment by seeoneco** [comment]
楼主最后解决问题了吗，我出现了跟你一样的问题
