### ISSUE TITLE
[Issue] 

### ISSUE THREAD

**Issue by akbarazmal** [Melledy/Grasscutter#812]
**Did you look for other closed issues that have the same problem?**
Yes, but there was only two person in #support that has the same problem as me and still no solution.

**Describe the issue**
Exception in thread "main" java.lang.NullPointerException: Cannot read the array length because "local2" is null
        at emu.grasscutter.tools.Tools.getAvailableLanguage(Tools.java:45)
        at emu.grasscutter.tools.Tools.getLanguageOption(Tools.java:60)
        at emu.grasscutter.tools.Tools.createGachaMapping(Tools.java:39)
        at emu.grasscutter.server.dispatch.DispatchServer.start(DispatchServer.java:457)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:109)

**Which version did you use?**
The latest one, Grasscutter | v1.1.0

**Screenshots**
[1652259228337](https://user-images.githubusercontent.com/81921451/167812011-2bad674c-83c3-4b49-abfc-4796d987ef47.jpg)

**Additional context**
Idk if it's related or not, but right before this I got the "Failed to load language file: xx-XX.json" and went ahead to edit the config.json like the pinned message says.

**Comment by pengtb** [comment]
same problem

**Comment by pengtb** [comment]
It seems that it is needed to copy all the files in [https://github.com/Koko-boya/Grasscutter_Resources](url) to the resources folder, not only the **BinOutput** & **ExcelBinOutput** as the readme or log says. The wiki [https://github.com/Grasscutters/Grasscutter/wiki/Running#starting-the-server](url) seems correct instead.
