### ISSUE TITLE
[Issue] 

### ISSUE THREAD

**Issue by UDSaUDHASASDIHADS** [Melledy/Grasscutter#818]
**Did you look for other closed issues that have the same problem?**

**Describe the issue**

Cannot invoke "emu.grasscutter.game.world.SpawnDataEntry$SpawnGroupEntry.getSpawns()" because "entry" is null
**Which version did you use?**
dev-quests

**Screenshots**

![N72K$6_KQ$F@`61D _PKUN](https://user-images.githubusercontent.com/62532106/167847472-636b9fb9-1eb8-4c69-8ba7-04e6ee93138b.png)
**Additional context**

"C:\Program Files\Java\jdk-17.0.3\bin\java.exe" "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.2\lib\idea_rt.jar=58379:C:\Program Files\JetBrains\IntelliJ IDEA 2021.3.2\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\Admin\Desktop\Grasscutter-quest\out\production\classes;C:\Users\Admin\Desktop\Grasscutter-quest\out\production\resources;C:\Users\Admin\Desktop\Grasscutter-quest\lib\fastutil-mini-8.5.6.jar;C:\Users\Admin\Desktop\Grasscutter-quest\lib\java-express.jar;C:\Users\Admin\Desktop\Grasscutter-quest\lib\kcp-netty-1.5.0.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-classic\1.2.9\7d495522b08a9a66084bf417e70eedf95ef706bc\logback-classic-1.2.9.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.reflections\reflections\0.10.2\b638d7ca0e0fe0146b60a0e7ba232ad852a73b31\reflections-0.10.2.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\dev.morphia.morphia\morphia-core\2.2.6\8dd21dd7e49cc78d8e726e236bdcd28510ad776a\morphia-core-2.2.6.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.quartz-scheduler\quartz\2.3.2\18a6d6b5a40b77bd060b34cb9f2acadc4bae7c8a\quartz-2.3.2.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.36\6c62681a2f655b49963a5983b8b0950a6120ae14\slf4j-api-1.7.36.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-core\1.2.9\cdaca0cf922c5791a8efa0063ec714ca974affe3\logback-core-1.2.9.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.jline\jline\3.21.0\2bf6f2311356f309fda0412e9389d2499346b5a1\jline-3.21.0.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.jline\jline-terminal-jna\3.21.0\ed51f283abaef01b6a215e6fb69e86afea410499\jline-terminal-jna-3.21.0.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\net.java.dev.jna\jna\5.10.0\7cf4c87dd802db50721db66947aa237d7ad09418\jna-5.10.0.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-all\4.1.71.Final\8c89f16505b815e966bb1d4bf4681bdd3701b8b1\netty-all-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\com.google.code.gson\gson\2.9.0\8a1167e089096758b49f9b34066ef98b2f4b37aa\gson-2.9.0.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\com.google.protobuf\protobuf-java\3.18.2\17e444501d7ed8dd1f6348f5bc0ad627200defa8\protobuf-java-3.18.2.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.greenrobot\eventbus-java\3.3.1\74487b0caceca6fcd1aff45d41a9cdc6910d7f5a\eventbus-java-3.3.1.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.danilopianini\java-quadtree\0.1.9\3eb9cde063327dfefa62e281f7858b44d6d90006\java-quadtree-0.1.9.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.quartz-scheduler\quartz-jobs\2.3.2\b2223bd809ffc77d41a2739fde85b822e59be2fe\quartz-jobs-2.3.2.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.luaj\luaj-jse\3.0.1\99245b2df284805e1cb835e9be47c243f9717511\luaj-jse-3.0.1.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.javassist\javassist\3.28.0-GA\9a958811a88381bb159cc2f5ed79c34a45c4af7a\javassist-3.28.0-GA.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\com.google.code.findbugs\jsr305\3.0.2\25ea2e8b0c338a877313bd4672d3fe056ea78f0d\jsr305-3.0.2.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\com.github.spotbugs\spotbugs-annotations\3.1.9\2ef5127efcc1a899aab8c66d449a631c9a99c469\spotbugs-annotations-3.1.9.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.mongodb\mongodb-driver-legacy\4.2.2\26df40b6d9e8ccb823c29dcf23ba284e41c9bf16\mongodb-driver-legacy-4.2.2.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.mongodb\mongodb-driver-sync\4.2.2\701dc782a41912284c21a76b35e96473550fa5cf\mongodb-driver-sync-4.2.2.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.github.classgraph\classgraph\4.8.78\87ced5cc1843e8c1736d9abc4a481e75558edddb\classgraph-4.8.78.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\net.bytebuddy\byte-buddy\1.11.3\c2a818c3b71127167edff8b9dd1caa946f1c8c49\byte-buddy-1.11.3.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\13.0\919f0dfe192fb4e063e7dacadee7f8bb9a2672a9\annotations-13.0.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\com.zaxxer\HikariCP-java7\2.4.13\3e441eddedb374d4de8e3abbb0c90997f51cc97b\HikariCP-java7-2.4.13.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\com.mchange\c3p0\0.9.5.4\a21a1d37ae0b59efce99671544f51c34ed1e8def\c3p0-0.9.5.4.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\com.mchange\mchange-commons-java\0.2.15\6ef5abe5f1b94ac45b7b5bad42d871da4fda6bbc\mchange-commons-java-0.2.15.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.jline\jline-terminal\3.21.0\47579f05a0002f9c561cb10dcf2f744976c49ac\jline-terminal-3.21.0.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-buffer\4.1.71.Final\258d8d0ae50a6dc86cb7e8bf4a0599a19c4d81a6\netty-buffer-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec\4.1.71.Final\f9c240be81796f4161f842ed5a50159635e4b621\netty-codec-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-dns\4.1.71.Final\c83d4c0249a46a72c7517a1fed73034b01909a8c\netty-codec-dns-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-haproxy\4.1.71.Final\c87961e46e4954a1bd08ab56a75dc4e0896cba2c\netty-codec-haproxy-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-http\4.1.71.Final\8348b70fc1122d53c9d610b1142d427e0498c254\netty-codec-http-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-http2\4.1.71.Final\4183c2585fbb39e8b1fa0be4df555b547f388224\netty-codec-http2-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-memcache\4.1.71.Final\11cd190efc6630276c9ef7987818908b4969f76\netty-codec-memcache-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-mqtt\4.1.71.Final\7f1ece34442b861146a2df537c75d6c7fb3429\netty-codec-mqtt-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-redis\4.1.71.Final\2957506e7956762c385368f2eebdc15995dc3723\netty-codec-redis-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-smtp\4.1.71.Final\6410470024a9a3d0180ffffb425369758f85270a\netty-codec-smtp-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-socks\4.1.71.Final\5805dc9258561523d86194c71f27f073d8290def\netty-codec-socks-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-stomp\4.1.71.Final\32ecfa00d63f13ebf6abc49d90db8c93acb6a61e\netty-codec-stomp-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-codec-xml\4.1.71.Final\14582c55d9c2cf2152a9e75f64e4ddf947011d69\netty-codec-xml-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-common\4.1.71.Final\34ef24f5297849007b8e9ae1884606fd95ef35d4\netty-common-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-handler\4.1.71.Final\fff73340583f277dd74c7145aa748c72f75a71d\netty-handler-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-tcnative-classes\2.0.46.Final\9937a832d9c19861822d345b48ced388b645aa5f\netty-tcnative-classes-2.0.46.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-handler-proxy\4.1.71.Final\67eb43b6306d1dbc5ccc3ba03a38d9209b6ecc42\netty-handler-proxy-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-resolver\4.1.71.Final\d4b5377a9bf78015125d5da070b48a4d8d85433e\netty-resolver-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-resolver-dns\4.1.71.Final\89e15f63a6d93ff392cf61704fc6a8361252ae6b\netty-resolver-dns-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport\4.1.71.Final\c7d0d89b26b844fabfba68093945fb2703d89761\netty-transport-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-rxtx\4.1.71.Final\c4016b4611a62babfb5da937fbcdc1e046bc27df\netty-transport-rxtx-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-sctp\4.1.71.Final\473decc08e25a56ad4b4ae7b67efaac7f320738f\netty-transport-sctp-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-udt\4.1.71.Final\33cd943c7ad645e6c3f1f6ac3a3bd24a0e967a37\netty-transport-udt-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-classes-epoll\4.1.71.Final\c82ed86945dc91fcbacdad7660746657429a67ad\netty-transport-classes-epoll-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-native-unix-common\4.1.71.Final\d7adb0d02ce6bb20a792600b52e353aec65dae86\netty-transport-native-unix-common-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-classes-kqueue\4.1.71.Final\198df3a7c43c8e7b2c41c8ae9cf3175c30945e0b\netty-transport-classes-kqueue-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-resolver-dns-classes-macos\4.1.71.Final\e4ff273f3bbe438f39b0ba14ee1d981a86b17845\netty-resolver-dns-classes-macos-4.1.71.Final.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.mongodb\mongodb-driver-core\4.2.2\1b67153f73a3bcaa94b204cd40543e377ccd7c02\mongodb-driver-core-4.2.2.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.mongodb\bson\4.2.2\56413d45800ef7391bb038095996f1a659cd8a80\bson-4.2.2.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-native-epoll\4.1.71.Final\39cbedb9312eae8d9e4622c313f22dfef4106149\netty-transport-native-epoll-4.1.71.Final-linux-aarch_64.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-native-epoll\4.1.71.Final\2241265a918eddaace47d238422950cc17370571\netty-transport-native-epoll-4.1.71.Final-linux-x86_64.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-native-kqueue\4.1.71.Final\70e613f1023e6118097a6431b5c4608605453679\netty-transport-native-kqueue-4.1.71.Final-osx-aarch_64.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-transport-native-kqueue\4.1.71.Final\a7e9bbf9c30db70d5b22ed4c8208b156fcf9cc89\netty-transport-native-kqueue-4.1.71.Final-osx-x86_64.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-resolver-dns-native-macos\4.1.71.Final\63c9f402684ed981ff254d9ba16fe2433ba38b7e\netty-resolver-dns-native-macos-4.1.71.Final-osx-aarch_64.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\io.netty\netty-resolver-dns-native-macos\4.1.71.Final\5f43a8f5d1af42d98d1ed69d8c30f77b4a602747\netty-resolver-dns-native-macos-4.1.71.Final-osx-x86_64.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\com.google.guava\guava\31.1-jre\60458f877d055d0c9114d9e1a2efb737b4bc282c\guava-31.1-jre.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\com.google.guava\failureaccess\1.0.1\1dcf1de382a0bf95a3d8b0849546c88bac1292c9\failureaccess-1.0.1.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\com.google.guava\listenablefuture\9999.0-empty-to-avoid-conflict-with-guava\b421526c5f297295adef1c886e5246c39d4ac629\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\org.checkerframework\checker-qual\3.12.0\d5692f0526415fcc6de94bb5bfbd3afd9dd3b3e5\checker-qual-3.12.0.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\com.google.errorprone\error_prone_annotations\2.11.0\c5a0ace696d3f8b1c1d8cc036d8c03cc0cbe6b69\error_prone_annotations-2.11.0.jar;C:\Users\Admin\.gradle\caches\modules-2\files-2.1\com.google.j2objc\j2objc-annotations\1.3\ba035118bc8bac37d7eff77700720999acd9986d\j2objc-annotations-1.3.jar emu.grasscutter.Grasscutter
20:09:45 <INFO:Grasscutter> 正在启动 Grasscutter...
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2081 column 40 path $[15].Default.modifiers..onAdded[0].amount
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:225)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:991)
	at com.google.gson.Gson.fromJson(Gson.java:956)
	at emu.grasscutter.data.ResourceLoader.loadAbilityModifiers(ResourceLoader.java:270)
	at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:59)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:96)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 2081 column 40 path $[15].Default.modifiers..onAdded[0].amount
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214)
	... 21 more
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 4960 column 40 path $[25].Default.modifiers..onThinkInterval[2].amount
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:225)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.Gson.fromJson(Gson.java:991)
	at com.google.gson.Gson.fromJson(Gson.java:956)
	at emu.grasscutter.data.ResourceLoader.loadAbilityModifiers(ResourceLoader.java:270)
	at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:59)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:96)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 4960 column 40 path $[25].Default.modifiers..onThinkInterval[2].amount
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:214)
	... 21 more
20:09:47 <INFO:ResourceLoader> Loaded 47 FetterCharacterCardDatas.
20:09:47 <INFO:ResourceLoader> Loaded 300 AvatarTalentDatas.
20:09:47 <INFO:ResourceLoader> Loaded 400 AvatarSkillDatas.
20:09:47 <INFO:ResourceLoader> Loaded 4088 FetterDatas.
20:09:47 <INFO:ResourceLoader> Loaded 73 AvatarSkillDepotDatas.
20:09:47 <INFO:ResourceLoader> Loaded 167 MonsterDescribeDatas.
20:09:47 <INFO:ResourceLoader> Loaded 657 RewardPreviewDatas.
20:09:47 <INFO:ResourceLoader> Loaded 39 TowerFloorDatas.
20:09:47 <INFO:ResourceLoader> Loaded 2 TowerScheduleDatas.
20:09:47 <INFO:ResourceLoader> Loaded 57 AvatarCostumeDatas.
20:09:48 <INFO:ResourceLoader> Loaded 699 DungeonDatas.
20:09:48 <INFO:ResourceLoader> Loaded 10 AvatarFetterLevelDatas.
20:09:48 <INFO:ResourceLoader> Loaded 24 DailyDungeonDatas.
20:09:48 <INFO:ResourceLoader> Loaded 3032 NpcDatas.
20:09:48 <INFO:ResourceLoader> Loaded 66 ReliquaryMainPropDatas.
20:09:48 <INFO:ResourceLoader> Loaded 200 MonsterCurveDatas.
20:09:48 <INFO:ResourceLoader> Loaded 717 SceneDatas.
20:09:48 <INFO:ResourceLoader> Loaded 90 AvatarLevelDatas.
20:09:48 <INFO:ResourceLoader> Loaded 4065 RewardDatas.
20:09:48 <INFO:ResourceLoader> Loaded 6889 ItemDatas.
20:09:48 <INFO:ResourceLoader> Loaded 336 AvatarPromoteDatas.
20:09:48 <INFO:ResourceLoader> Loaded 335 ReliquaryAffixDatas.
20:09:48 <INFO:ResourceLoader> Loaded 90 WeaponLevelDatas.
20:09:48 <INFO:ResourceLoader> Loaded 1195 ShopGoodsDatas.
20:09:48 <INFO:ResourceLoader> Loaded 297 CombineDatas.
20:09:48 <INFO:ResourceLoader> Loaded 117 TowerLevelDatas.
20:09:48 <INFO:ResourceLoader> Loaded 939 WeaponPromoteDatas.
20:09:48 <INFO:ResourceLoader> Loaded 9 AvatarFlycloakDatas.
20:09:49 <INFO:ResourceLoader> Loaded 6626 GadgetDatas.
20:09:49 <INFO:ResourceLoader> Loaded 100 AvatarCurveDatas.
20:09:49 <INFO:ResourceLoader> Loaded 42 ReliquarySetDatas.
20:09:49 <INFO:ResourceLoader> Loaded 100 WeaponCurveDatas.
20:09:49 <INFO:ResourceLoader> Loaded 744 EquipAffixDatas.
20:09:49 <INFO:ResourceLoader> Loaded 8 WorldLevelDatas.
20:09:49 <INFO:ResourceLoader> Loaded 60 PlayerLevelDatas.
20:09:49 <INFO:ResourceLoader> Loaded 101 ReliquaryLevelDatas.
20:09:49 <INFO:ResourceLoader> Loaded 2420 ProudSkillDatas.
20:09:49 <INFO:ResourceLoader> Loaded 568 MonsterDatas.
20:09:49 <INFO:ResourceLoader> Loaded 78 AvatarDatas.
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "emu.grasscutter.game.world.SpawnDataEntry$SpawnGroupEntry.getSpawns()" because "entry" is null
	at emu.grasscutter.data.ResourceLoader.loadSpawnData(ResourceLoader.java:340)
	at emu.grasscutter.data.ResourceLoader.loadAll(ResourceLoader.java:65)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:96)

**Comment by zhaodice** [comment]
full update resources folder but database, don't overwrite directly.

**Comment by KingRainbow44** [comment]
As there is no activity on this issue, it will be closed. Feel free to make another issue if the bug hasn't been fixed.
