### ISSUE TITLE
[Issue] Quest Error

### ISSUE THREAD

**Issue by cxfm666** [Melledy/Grasscutter#856]
issue
When performing Quest with ID 4115801, the console throws an error and the in-game plot jams without reaction
Jar Version
Grasscutter version: 1.1.1-dev-quests
Error Info
java.lang.NullPointerException: Cannot read the array length because the return value of "emu.grasscutter.data.custom.QuestConfigData$SubQuestConfigData.getFinishCond()" is null
        at emu.grasscutter.game.quest.QuestManager.lambda$triggerEvent$0(QuestManager.java:131)
        at emu.grasscutter.game.quest.QuestManager.forEachActiveQuest(QuestManager.java:76)
        at emu.grasscutter.game.quest.QuestManager.triggerEvent(QuestManager.java:128)
        at emu.grasscutter.server.packet.recv.HandlerNpcTalkReq.handle(HandlerNpcTalkReq.java:19)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:250)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)
java.lang.NullPointerException: Cannot read the array length because the return value of "emu.grasscutter.data.custom.QuestConfigData$SubQuestConfigData.getFinishCond()" is null
        at emu.grasscutter.game.quest.QuestManager.lambda$triggerEvent$0(QuestManager.java:131)
        at emu.grasscutter.game.quest.QuestManager.forEachActiveQuest(QuestManager.java:76)
        at emu.grasscutter.game.quest.QuestManager.triggerEvent(QuestManager.java:128)
        at emu.grasscutter.server.packet.recv.HandlerNpcTalkReq.handle(HandlerNpcTalkReq.java:19)
        at emu.grasscutter.server.game.GameServerPacketHandler.handle(GameServerPacketHandler.java:88)
        at emu.grasscutter.server.game.GameSession.onMessage(GameSession.java:250)
        at emu.grasscutter.netty.KcpChannel.channelRead(KcpChannel.java:43)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:603)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by cxfm666** [comment]
Sorry I have a poor English, but I use Bing translate for translation

**Comment by BedamatiMohanty** [comment]
Ok no issues as aternity or any other translator that is useful or compatible to your region

**Comment by ChikaKawasure** [comment]
怎样能下载到文件？

**Comment by KingRainbow44** [comment]
As there is no activity on this issue, it will be closed. Feel free to make another issue if the bug hasn't been fixed.
