### ISSUE TITLE
[Bug] Aways disconnect from server when playing game first

### ISSUE THREAD

**Issue by zhaodice** [Melledy/Grasscutter#899]
```
[04:24:49] [INFO] Client connected from 172.17.0.7                                            
> java.io.IOException: Conv inconsistency                                                     
        at io.jpower.kcp.netty.Ukcp.input(Ukcp.java:142)                                      
        at io.jpower.kcp.netty.UkcpServerChildChannel.kcpInput(UkcpServerChildChannel.java:202
)                                                                                             
        at io.jpower.kcp.netty.UkcpServerChannel$UkcpServerUnsafe.read(UkcpServerChannel.java:
591)                                                                                          
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)        
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:65
8)                                                                                            
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)       
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)                       
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.
java:986)                                                                                     
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)          
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:3
0)                                                                                            
        at java.base/java.lang.Thread.run(Thread.java:833)
```
![aaa](https://user-images.githubusercontent.com/63996691/168457268-e0f67b1c-5eb6-471f-8cf4-d2e08aba0a20.PNG)

**Comment by zhaodice** [comment]
it looks like disconnection by server forwardly

**Comment by zhaodice** [comment]
I have tried a lot of times, it always shows: `connect -> play animation -> disconnected from server`

**Comment by zhaodice** [comment]
I think I can changed this program:
https://github.com/szhnet/kcp-netty/blob/master/kcp-netty/src/main/java/io/jpower/kcp/netty/Ukcp.java

LINE: 78
```
public void input(ByteBuf data) throws IOException {
      int ret = kcp.input(data);
      switch (ret) {
          case -1:
              throw new IOException("No enough bytes of head");
          case -2:
              throw new IOException("No enough bytes of data");
          case -3:
              throw new IOException("Mismatch cmd");
          case -4:
              throw new IOException("Conv inconsistency");
          default:
              break;
      }
  }
}
```
DELETE this IOException logic in case of kicking from server when packet loss

**Comment by ghost** [comment]
Those errors in the kcp function you copied are there for a good reason.

As for your problem, please update your grasscutter resources folder.

**Comment by zhaodice** [comment]
> Those errors in the kcp function you copied are there for a good reason.
> 
> As for your problem, please update your grasscutter resources folder.

It does work when I run server locally , but I move server to remote network it shows error
I connected server after trying too much , the ping is 100ms-200ms.
I think it caused by a bit of packet loss
Peculiarly, when I connect successfully, it will be very stable,  the disconnection always emerge in just login

**Comment by zhaodice** [comment]
> Those errors in the kcp function you copied are there for a good reason.
> 
> As for your problem, please update your grasscutter resources folder.

I resolved it, please visit: https://github.com/Melledy/kcp-netty/pull/1
