### ISSUE TITLE
[Issue] failed to load language file: en-CA.json

### ISSUE THREAD

**Issue by geokitfx** [Melledy/Grasscutter#903]
**Did you look for other closed issues that have the same problem?**
Didn't find any with my specific issue

**Describe the issue**
Cant start the server because the jar failed to load the language file en-CA.json

**Which version did you use?**
  Grasscutter version: 1.1.0 
  The Pre-made server jar
  Git Hash: I do not know

**Scr
![GENSHINPS](https://user-images.githubusercontent.com/46139326/168458291-9224655d-475a-4596-8444-47907d4e39c4.PNG)
eenshots**

**Additional context**

G:\GENSHINPS>"C:\Program Files\Java\jdk-17.0.3.1\bin\java" -jar grasscutter-1.1.0.jar
[23:11:22] [WARN] Failed to load language file: en-CA.json
java.lang.NullPointerException: null
        at java.base/java.io.Reader.<init>(Reader.java:168)
        at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:112)
        at emu.grasscutter.utils.Utils.readFromInputStream(Utils.java:258)
        at emu.grasscutter.utils.Language.<init>(Language.java:55)
        at emu.grasscutter.utils.Language.getLanguage(Language.java:22)
        at emu.grasscutter.Grasscutter.loadLanguage(Grasscutter.java:158)
        at emu.grasscutter.Grasscutter.<clinit>(Grasscutter.java:63)
[23:11:23] [WARN] Failed to read file: .\keys\dispatchKey.bin
[23:11:23] [WARN] Failed to read file: .\keys\secretKey.bin
[23:11:23] [WARN] Failed to read file: .\keys\secretKeyBuffer.bin
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonObject.has(String)" because "object" is null
        at emu.grasscutter.utils.Language.get(Language.java:83)
        at emu.grasscutter.utils.Language.translate(Language.java:32)
        at emu.grasscutter.Grasscutter.main(Grasscutter.java:89)

G:\GENSHINPS>Pause
Press any key to continue . . .

**Comment by geokitfx** [comment]
Figured out a fix, I set
"LocaleLanguage": "en_CA",
To
 "LocaleLanguage": "en_US",
 in config.json
