### ISSUE TITLE
[Issue] java.io.FileNotFoundException: ./data/TowerSchedule.json (No such file or directory)

### ISSUE THREAD

**Issue by moenuclear** [Melledy/Grasscutter#942]
at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/java.io.FileReader.<init>(FileReader.java:60)
	at emu.grasscutter.game.tower.TowerScheduleManager.load(TowerScheduleManager.java:28)
	at emu.grasscutter.game.tower.TowerScheduleManager.<init>(TowerScheduleManager.java:22)
	at emu.grasscutter.server.game.GameServer.<init>(GameServer.java:89)
	at emu.grasscutter.server.game.GameServer.<init>(GameServer.java:62)
	at emu.grasscutter.Grasscutter.main(Grasscutter.java:117)

**Comment by moenuclear** [comment]
Seems to tell me that this ”TowerSchedule.json“ is missing , who can give me one?

**Comment by durkkkkkkk** [comment]
Create a new file name TowerSchedule.json then paste the code given below:
or just look at the github page located at "data" directory.
{
    "scheduleId" : 1,
    "scheduleStartTime" : "2022-05-01T00:00:00+08:00",
    "nextScheduleChangeTime" : "2022-05-30T00:00:00+08:00"
}
