### ISSUE TITLE
在做任务时出现错误

### ISSUE THREAD

**Issue by daxiwow** [Melledy/Grasscutter#951]
10:16:43 <ERROR:GameServer$1> 游戏更新时发生错误
java.lang.IllegalArgumentException: key can not be empty
        at java.scripting/javax.script.SimpleBindings.checkKey(SimpleBindings.ja
va:215)
        at java.scripting/javax.script.SimpleBindings.get(SimpleBindings.java:15
8)
        at emu.grasscutter.scripts.SceneScriptManager.callEvent(SceneScriptManag
er.java:411)
        at emu.grasscutter.scripts.SceneScriptManager.checkRegions(SceneScriptMa
nager.java:312)
        at emu.grasscutter.scripts.SceneScriptManager.onTick(SceneScriptManager.
java:296)
        at emu.grasscutter.game.world.Scene.onTick(Scene.java:415)
        at emu.grasscutter.game.world.World.onTick(World.java:314)
        at emu.grasscutter.server.game.GameServer.onTick(GameServer.java:218)
        at emu.grasscutter.server.game.GameServer$1.run(GameServer.java:245)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:566)
        at java.base/java.util.TimerThread.run(Timer.java:516)

**Comment by HongJian-Yang** [comment]
有剧情任务嘛, 我进去咋啥都没有

**Comment by kivet3** [comment]
> 有剧情任务嘛，我进去咋啥都没有

的确是没有任何任务的，不过你可以通过控制台去添加
