### ISSUE TITLE
[Bug]  编译时候出错Exception in thread "main" javax.net.ssl.SSLException: Received fatal alert: protocol_versio

### ISSUE THREAD

**Issue by 2563411574** [Melledy/Grasscutter#977]
**Did you look for other closed issues that have the same problem?**

**Describe the bug**

**Which branch did you use?**

**Screenshots**

**Additional context**

**Comment by 2563411574** [comment]
root@ced60fa4ef13:/Grasscutter# ./gradlew jar
Downloading https://services.gradle.org/distributions/gradle-7.4.2-bin.zip

Exception in thread "main" javax.net.ssl.SSLException: Received fatal alert: protocol_version
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
        at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1989)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1096)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1342)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1369)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1353)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1341)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
        at org.gradle.wrapper.Download.downloadInternal(Download.java:67)
        at org.gradle.wrapper.Download.download(Download.java:52)
        at org.gradle.wrapper.Install$1.call(Install.java:62)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

**Comment by Becods** [comment]
```
Received fatal alert: protocol_version
```

Usually you are using the wrong version of java.

Or maybe it's the network that's causing it.

You may need some **magic**.

**Comment by 2563411574** [comment]
> ```
> Received fatal alert: protocol_version
> ```
> 
> Usually you are using the wrong version of java.
> 
> Or maybe it's the network that's causing it.
> 
> You may need some **magic**.

那有木有docker版呢 我创建了一个docker镜像 依赖JAVA SDK 8 但是貌似不能成功跑起来 跑起来时候报错如下
./grasscutter-1.1.0.jar: line 1: $'PK\003\004': command not found
./grasscutter-1.1.0.jar: line 2: $'\b\bim\261T\002': command not found
K-*��ϳR0�3���M���u�I,.�RH�-�K/2�KKJR���l^.^.PK: No such file or directory
./grasscutter-1.1.0.jar: line 4: syntax error near unexpected token `)'
./grasscutter-1.1.0.jar: line 4:dm�T��%W
␍�Y��P�,��z�{4�'���fh]���%6E�r�A�S*#� �\O���<Y�DB�W+]1���*⎼9W��<⎼�*=≠ͬ�␊�$WorldPlayerReviveReq$Builder.class�Yy`����&�ݝH8�Ah�����TBH�   Ƅ&�Zq��63��,�Pk��V{�mU<����ր`Ezhk�a/{�V�=<ZjO�h�7;�Lvg��n��#o���}����}o��׏<����H�_F1J�^��Ȫ�����|st3o�W�%
         ��␌�␍4�≥�)▒����⎻A�60L�┘"��AK�°5┘D�X�J▒X_ղQ٬�����ԭ!␌␉Z┼
                                                               ␉,Δ0NF�3�≤D�\�P2?J�.◆(���&�2L�1Q M�U�┤�␊���└��'

**Comment by happyjonny** [comment]
> > ```
> > Received fatal alert: protocol_version
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Usually you are using the wrong version of java.
> > Or maybe it's the network that's causing it.
> > You may need some **magic**.
> 
> 那有木有docker版呢 我创建了一个docker镜像 依赖JAVA SDK 8 但是貌似不能成功跑起来 跑起来时候报错如下 ./grasscutter-1.1.0.jar: line 1: $'PK\003\004': command not found ./grasscutter-1.1.0.jar: line 2: $'\b\bim\261T\002': command not found K-*��ϳR0�3���M���u�I,.�RH�-�K/2�KKJR���l^.^.PK: No such file or directory ./grasscutter-1.1.0.jar: line 4: syntax error near unexpected token `)' ./grasscutter-1.1.0.jar: line 4:dm�T��%W ␍�Y��P�,��z�{4�'���fh]���%6E�r�A�S*#� �\O���<Y�DB�W+]1���*⎼9W��<⎼�*=≠ͬ�␊�$WorldPlayerReviveReq$Builder.class�Yy`����&�ݝH8�Ah�����TBH� Ƅ&�Zq��63��,�Pk��V{�mU<����ր`Ezhk�a/{�V�=<ZjO�h�7;�Lvg��n��#o���}����}o��׏<����H�_F1J�^��Ȫ�����|st3o�W�% ��␌�␍4�≥�)▒����⎻A�60L�┘"��AK�°5┘D�X�J▒X_ղQ٬�����ԭ!␌␉Z┼ ␉,Δ0NF�3�≤D�\�P2?J�.◆(���&�2L�1Q M�U�┤�␊���└��'

不要整其他花里胡哨的, 就用guide中说的java版本 Java SE - 17

**Comment by Eveink** [comment]
我根据你的报错看纯粹就是网络不好，没把构建工具https://services.gradle.org/distributions/gradle-7.4.2-bin.zip 下载回来。建议挂个梯子或者换运营商重试。

**Comment by memetrollsXD** [comment]
Closed due to inactivity
